'use strict';
const fs=require('node:fs'),path=require('node:path');
const {atomicJSON,readJSON}=require('../../orchestrator/files.cjs');
const root=process.env.FACTORY_WORKER_ROOT,id=require('./proposal.json').game_id;
const file=path.join(root,'autonomy/.provider/ledger.json');
const ledger=fs.existsSync(file)?readJSON(file):{operations:{}};
let cumulative=0;
const operations=Object.values(ledger.operations).map(o=>{const a=o.accounted||o.reserved;cumulative+=a.estimated_cost;return {operation_id:o.operation_id,operation:o.operation_id.includes('/repair/')?'repair':'build',version:o.version,model:o.provider.replace('openai-responses/',''),state:o.state,response_id:o.response_id,input_tokens:o.accounted?.input_tokens??null,output_tokens:o.accounted?.output_tokens??null,estimated_cost:a.estimated_cost,cumulative_estimated_cost:Number(cumulative.toFixed(8)),cost_basis:o.accounted?'reported usage × conservative configured rates':'reservation; usage not yet confirmed',error_code:o.error_code||null};});
const mf=path.join(root,`autonomy/jobs/${id}/manifest.json`),m=fs.existsSync(mf)?readJSON(mf):null;
const summary={schema:'playjolt-first-real-game/1',game_id:id,model:'gpt-5.6-terra',run_id:process.env.GITHUB_RUN_ID,runner_commit:process.env.GITHUB_SHA,operations,total_calls:operations.length,total_estimated_cost:Number(cumulative.toFixed(8)),billed_cost:null,model_source:'real OpenAI provider, no injected mock',factory:m?{state:m.state,version:m.version,repair_attempt:m.repair_attempt,qa_status:m.qa_status,quality_status:m.quality_status,source_hash:m.source_hash,failure_reasons:m.failure_reasons}:null,production_authorized:false};
if(operations.length>6||cumulative>2+1e-9)throw Error('commissioning_budget_violation');
atomicJSON(path.join(root,'commissioning-summary.json'),summary);console.log(JSON.stringify(summary,null,2));
if(!m||!['RC_READY','REJECTED'].includes(m.state))process.exitCode=2;
