'use strict';
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const {hash,atomicJSON,readJSON}=require('../orchestrator/files.cjs');
const {validateProposal}=require('../commissioning/spec-gate.cjs');
const product=require('../qa/product-contract.cjs');
const commercial=require('../qa/commercial/contract.cjs');
const {Factory}=require('../orchestrator/engine.cjs');
const {FileStore}=require('../orchestrator/store.cjs');
const {AutonomousWorker}=require('../worker/runtime.cjs');
const {DockerQA}=require('../isolation/docker-qa.cjs');
const {OpenAIProvider}=require('../providers/openai.cjs');
const families=require('./families.cjs');

function context(){
  const requestPath=process.env.PLAYJOLT_REQUEST_PATH;
  if(!requestPath)throw Error('PLAYJOLT_REQUEST_PATH required');
  const request=readJSON(path.resolve(requestPath)),dir=path.dirname(path.resolve(requestPath));
  const def=readJSON(path.join(dir,'candidate.json'));
  if(request.game_id!==def.game_id||request.candidate!==def.title)throw Error('candidate_request_mismatch');
  if(request.production_authorized!==false||request.auto_commission!==true)throw Error('candidate_authorization_invalid');
  return {request,def,dir,...families.build(def)};
}
function appendRegistry(file,entry){const data=readJSON(file);data.entries=data.entries.filter(x=>x.id!==entry.id);data.entries.push(entry);atomicJSON(file,data);fs.chmodSync(file,0o644);}
function installReviewData(ctx){
  const oracleFile=path.join(ROOT,'qa/reviewed',ctx.oracle_id+'.json');atomicJSON(oracleFile,ctx.model);fs.chmodSync(oracleFile,0o644);
  appendRegistry(path.join(ROOT,'qa/reviewed/registry.json'),{id:ctx.oracle_id,file:ctx.oracle_id+'.json',sha256:hash(ctx.model),scope:'candidate',game_id:ctx.def.game_id,contract_sha256:hash(ctx.productContract),reviewed_by:'PlayJolt trusted autonomous family compiler',rationale:'Generated only from a checked-in reviewed family constructor; no provider output can modify oracle structure, contract gates or authority limits.'});
  appendRegistry(path.join(ROOT,'qa/commercial/reviewed/registry.json'),{id:ctx.commercial_id,scope:'candidate',contract_sha256:hash(ctx.commercialContract),product_contract_sha256:hash(ctx.productContract),reviewed_by:'PlayJolt trusted autonomous family compiler',rationale:'Generated only from reviewed commercial regions and state anchors in the trusted family constructor.'});
  product.review(ctx.productContract);commercial.review(ctx.commercialContract,ctx.productContract);
}
async function prepare(){
  const ctx=context(),root=path.resolve(process.env.FACTORY_WORKER_ROOT||'');
  if(!root||!process.env.RUNNER_TEMP||!root.startsWith(path.resolve(process.env.RUNNER_TEMP)+path.sep))throw Error('dedicated_runner_root_required');
  fs.rmSync(root,{recursive:true,force:true});fs.mkdirSync(root,{recursive:true});
  installReviewData(ctx);
  const commissioningPolicy=readJSON(path.join(ROOT,'commissioning/policy.json'));
  const gate=validateProposal(ctx.proposal,{policy:commissioningPolicy,catalog:readJSON(path.join(ROOT,'commissioning/catalog.json'))});
  if(!gate.passed)throw Error('spec_gate_failed '+JSON.stringify(gate.errors));
  const settings={commissioning:true,release_candidates:false,base_ref:'main',pricing:{input_per_million:4,output_per_million:18,as_of:new Date().toISOString().slice(0,10)},per_game:{max_provider_calls:ctx.request.authorized_provider_calls,max_input_tokens:500000,max_output_tokens:120000,max_estimated_cost:ctx.request.estimated_usd_ceiling,max_wall_clock_minutes:60},global:{daily_provider_call_limit:ctx.request.authorized_provider_calls,daily_cost_limit:ctx.request.estimated_usd_ceiling,max_concurrent_builds:1},request:{max_input_tokens:100000,max_output_tokens:20000,timeout_ms:300000,max_response_bytes:1048576,max_file_bytes:131072,max_files:24},isolation:{cpus:1,memory_mb:1024,pids:128,timeout_ms:300000},polling:{interval_ms:2000,max_backoff_ms:30000,max_polls:20,max_jobs:1}};
  const cp=JSON.parse(JSON.stringify(readJSON(path.join(ROOT,'control-plane/policy.json'))));
  Object.assign(cp,{mode:'autonomous-cycle-one-candidate',intake_enabled:true,auto_rc_enabled:false,max_active_jobs:1,max_daily_new_jobs:1});
  Object.assign(cp.kill_switches,{release_candidates:true,production_shipping:true,marketing_promotion:true});
  const auth={schema:'playjolt-auto-cycle/1',game_id:ctx.def.game_id,model:'gpt-5.6-terra',user_authorized:true,authorization_basis:'Explicit auto_commission request generated by the trusted autonomous intake workflow; bounded by resolver and per-game settings.',max_generations:ctx.request.authorized_provider_calls,max_repairs:5,estimated_usd_ceiling:ctx.request.estimated_usd_ceiling,production_authorized:false,base_commit:process.env.GITHUB_SHA||null};
  for(const [n,d] of Object.entries({'proposal.json':ctx.proposal,'spec-gate.json':gate,'worker-config.json':settings,'control-policy.json':cp,'authorization.json':auth,'oracle.json':ctx.model,'candidate-definition.json':ctx.def}))atomicJSON(path.join(root,n),d);
  await new Factory({store:new FileStore(root)}).create(gate.factory_spec);
  console.log(JSON.stringify({preflight:'PASS',game_id:ctx.def.game_id,title:ctx.def.title,family:ctx.def.family,runtime:ctx.request.runtime,oracle_hash:hash(ctx.model),product_hash:hash(ctx.productContract),commercial_hash:hash(ctx.commercialContract),warnings:gate.warnings},null,2));
}
function reviews(){
  const ctx=context(),root=path.resolve(process.env.FACTORY_WORKER_ROOT||'');
  if(!root||!fs.existsSync(path.join(root,'proposal.json')))throw Error('recovered_worker_root_required');
  installReviewData(ctx);
  const stored=readJSON(path.join(root,'proposal.json'));
  if(stored.game_id!==ctx.def.game_id||hash(readJSON(path.join(root,'oracle.json')))!==hash(ctx.model)||hash(stored.product_contract)!==hash(ctx.productContract)||hash(stored.commercial_contract)!==hash(ctx.commercialContract))throw Error('recovery_contract_mismatch');
  console.log(JSON.stringify({reviews:'PASS',game_id:ctx.def.game_id,family:ctx.def.family,permissions:'0644'},null,2));
}
async function run(){
  const ctx=context(),root=process.env.FACTORY_WORKER_ROOT,settings=readJSON(path.join(root,'worker-config.json')),policyFile=path.join(root,'control-policy.json');
  installReviewData(ctx);
  const worker=new AutonomousWorker({root,settings,policyFile,provider:new OpenAIProvider(),qa:new DockerQA({limits:settings.isolation})});
  const result=await worker.runOnce();atomicJSON(path.join(root,'worker-result.json'),result);console.log(JSON.stringify(result,null,2));
  if(!['RC_READY','REJECTED'].includes(result.status))process.exitCode=2;
}
function summarize(){
  const ctx=context(),root=process.env.FACTORY_WORKER_ROOT,ledgerFile=path.join(root,'autonomy/.provider/ledger.json'),ledger=fs.existsSync(ledgerFile)?readJSON(ledgerFile):{operations:{}};
  const ops=Object.values(ledger.operations).filter(x=>x.game_id===ctx.def.game_id).sort((a,b)=>a.started_at-b.started_at).map(o=>({operation_id:o.operation_id,version:o.version,state:o.state,response_id:o.response_id,input_tokens:o.accounted?.input_tokens??null,output_tokens:o.accounted?.output_tokens??null,estimated_cost:(o.accounted||o.reserved)?.estimated_cost??null,error_code:o.error_code||null}));
  const m=readJSON(path.join(root,'autonomy/jobs',ctx.def.game_id,'manifest.json')),total=ops.reduce((n,o)=>n+(o.estimated_cost||0),0);
  const summary={schema:'playjolt-auto-cycle-summary/1',game_id:ctx.def.game_id,title:ctx.def.title,family:ctx.def.family,runtime:ctx.request.runtime,runner_commit:process.env.GITHUB_SHA,run_id:process.env.GITHUB_RUN_ID,operations:ops,total_calls:ops.length,total_estimated_cost:Number(total.toFixed(8)),factory:{state:m.state,version:m.version,repair_attempt:m.repair_attempt,technical_qa_status:m.technical_qa_status,product_qa_status:m.product_qa_status,commercial_qa_status:m.commercial_qa_status,quality_status:m.quality_status,source_hash:m.source_hash,failure_reasons:m.failure_reasons},production_authorized:false};
  atomicJSON(path.join(root,'commissioning-summary.json'),summary);console.log(JSON.stringify(summary,null,2));
}
async function main(){
  const cmd=process.argv[2];
  if(cmd==='prepare')return prepare();
  if(cmd==='reviews')return reviews();
  if(cmd==='run')return run();
  if(cmd==='summarize')return summarize();
  throw Error('usage prepare|reviews|run|summarize');
}
if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1;});
module.exports={main,prepare,reviews,run,summarize,context};
