'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const C=require('../measurement/contract.js'),{makeHandler}=require('../api/event.js');
const code=fs.readFileSync(path.join(__dirname,'../arcade3/telemetry.js'),'utf8');
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
function event(p={}){return {schema:C.SCHEMA,event_id:id(1),session_id:id(2),event:'game_start',path:'/challengers/play?game=core-pins',source:'instagram',source_raw:'ig',medium:'social',campaign:'',content:'link_in_bio',props:{game:'core-pins',ranked:false},...p};}
function tab(search='',store={},extra={}){
 let n=100;const output=[],listeners={},url=new URL('https://vibe-arcade-dun.vercel.app/descent'+search);
 const sandbox={URL,URLSearchParams,Date,Blob,Set,location:{href:url.href,origin:url.origin,hostname:url.hostname,pathname:url.pathname,search:url.search},crypto:{randomUUID:()=>id(++n)},sessionStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]},localStorage:{getItem:()=>null},document:{referrer:'',addEventListener:(e,f)=>listeners[e]=f},navigator:{sendBeacon:(u,b)=>{output.push(b);return true;}},fetch:()=>{throw Error('no network')},...extra};sandbox.window=sandbox;vm.runInNewContext(code,sandbox);return {sandbox,output,store,listeners,events:async()=>Promise.all(output.map(async b=>JSON.parse(await b.text())))};
}
for(const [a,b] of [['ig','instagram'],['IG','instagram'],['yt','youtube'],['tt','tiktok'],['th','threads'],['facebook','facebook']])test('normalizes channel '+a,()=>assert.equal(C.source(a),b));
for(const [p,g] of [['/descent','gyro-drop'],['/descent/','gyro-drop'],['/games/core-pins','core-pins'],['/games/nova-merge/','nova-merge'],['/challengers/play?game=core-pins','core-pins'],['/challengers/play?game=nova-merge','nova-merge'],['/games/orbit-sprint/index.html','orbit-sprint'],['/','']])test('route '+p,()=>assert.equal(C.gameFor(p)||'',g));
test('bio tags cannot become a per-video conversion',()=>{const x=C.clean(event({campaign:'flag_challenge',content:'dd_fc01',medium:'profile'}));assert.equal(x.scope,'channel_only');assert.equal(x.source_raw,'ig');assert.equal(x.source,'instagram');});
test('recorded Instagram link stays channel-only',()=>{const x=C.clean(event());assert.equal(x.scope,'channel_only');assert.equal(x.campaign,'');});
test('tagged link is not an attribution proof',()=>assert.equal(C.clean(event({medium:'organic_social',campaign:'flag_challenge_pilot_20260920',content:'cp_fc01'})).scope,'content_tagged'));
test('direct and referrer classes survive double cleaning',()=>{for(const source of ['direct','google','instagram']){const b=C.clean(event({source,source_raw:'',medium:'',content:'',campaign:''}));assert.equal(b.source,source);assert.equal(JSON.stringify(C.clean(b)),JSON.stringify(b));assert.equal(b.scope,source==='direct'?'unattributed':'channel_only');}});
test('referrer query and identity not stored',()=>{const a=C.attribution('', 'https://www.google.com/search?q=private+text');assert.equal(a.source,'google');assert(!JSON.stringify(a).includes('private'));});
test('strips credentials, scores and personal fields',()=>{const b=event({password:'secret',token:'ljp_private',referrer:'https://a.test/?email=private',path:'/community?password=private',props:{game:'gyro-drop',score:123,password:'secret',handle:'private',country:'KR'}});const wire=JSON.stringify(C.clean(b));for(const s of ['secret','private','123','KR','referrer','password','handle'])assert(!wire.includes(s));});
test('invalid campaign strings dropped',()=>{const x=C.clean(event({campaign:'a@b.com',content:'<img/onerror=1>'}));assert.equal(x.campaign,'');assert.equal(x.content,'');});
for(const bad of [[],null,{},event({event:'password'}),event({session_id:'abc'}),event({event_id:'x'})])test('invalid event rejected '+JSON.stringify(bad)?.slice(0,40),()=>assert.throws(()=>C.clean(bad)));
test('one page view across two client APIs',async()=>{const t=tab();t.sandbox.LJTelemetry.track('page_view','gyro-drop','v');t.sandbox.VibeAnalytics.track('page_view',{});assert.equal((await t.events()).filter(e=>e.event==='page_view').length,1);});
test('replay requires a subsequent game_start',async()=>{const t=tab();t.sandbox.LJTelemetry.track('game_start','gyro-drop','v');t.sandbox.LJTelemetry.track('game_finish','gyro-drop','v');t.sandbox.LJTelemetry.track('game_finish','gyro-drop','v');t.sandbox.LJTelemetry.track('game_start','gyro-drop','v');const es=await t.events();assert.equal(es.filter(e=>e.event==='replay').length,1);assert.equal(es.filter(e=>e.event==='game_finish').length,1);const s=es.filter(e=>e.event==='game_start');assert.notEqual(s[0].attempt_id,s[1].attempt_id);});
test('acquisition survives navigation',()=>{const store={};tab('?utm_source=ig&utm_medium=social&utm_content=link_in_bio',store);const id1=JSON.parse(store.lj4_acquisition).id;tab('?game=core-pins',store);assert.equal(JSON.parse(store.lj4_acquisition).id,id1);assert.equal(JSON.parse(store.lj4_acquisition).a.source,'instagram');});
test('new campaign clears old content',()=>{const store={};tab('?utm_source=threads&utm_campaign=pilot&utm_content=cp_fc01',store);tab('?utm_source=youtube&utm_campaign=new',store);assert.equal(JSON.parse(store.lj4_acquisition).a.content,'');});
test('expired session resets counters',()=>{const store={lj4_acquisition:JSON.stringify({id:id(77),last:Date.now()-1900000,a:C.attribution(''),starts:{'gyro-drop':3}})};tab('',store);assert.notEqual(JSON.parse(store.lj4_acquisition).id,id(77));assert.equal(JSON.parse(store.lj4_acquisition).starts['gyro-drop'],undefined);});
for(const mode of ['capture=1','qa=1','internal=1'])test('excluded '+mode,()=>{const t=tab('?'+mode);t.sandbox.LJTelemetry.track('game_start','gyro-drop','v');assert.equal(t.output.length,0);assert(!t.store.lj4_acquisition);});
for(const p of ['webdriver','globalPrivacyControl','doNotTrack'])test('honors '+p,()=>{const t=tab('',{},{navigator:{[p]:p==='doNotTrack'?'1':true}});assert.equal(t.output.length,0);assert(!t.store.lj4_acquisition);});
test('internal exclusion persists',()=>{const store={};tab('?internal=1',store);assert(tab('',store).sandbox.LJTelemetry.excluded);tab('?internal=0',store);assert.equal(tab('',store).sandbox.LJTelemetry.excluded,false);});
test('blocked storage cannot break setup',()=>{const t=tab('',{},{sessionStorage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}},localStorage:{getItem(){throw Error('blocked')}}});assert(t.sandbox.LJTelemetry.track);});
test('legacy bridge drops persistent visitor ID',()=>assert(!fs.readFileSync(path.join(__dirname,'../analytics.js'),'utf8').includes('vibe_session_id')));
function request(body=event()){return {method:'POST',headers:{origin:C.ORIGIN,'content-type':'application/json'},body};}
function response(){return {code:0,headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},json(d){this.data=d;return this;},end(){return this;}};}
test('collector sends only cleaned data',async()=>{let sent;const res=response();await makeHandler(async(u,o)=>{sent=JSON.parse(o.body);return {ok:true,status:204};})(request(event({password:'password'})),res);assert.equal(res.code,204);assert(!JSON.stringify(sent).includes('password'));assert.equal(res.data,undefined);});
test('failed sink is not successful storage',async()=>{const res=response();await makeHandler(async()=>({ok:false,status:500}),{warn(){}})(request(),res);assert.equal(res.code,503);});
for(const patch of [{method:'GET'},{headers:{}},{headers:{origin:'https://evil.invalid','content-type':'application/json'}},{headers:{origin:C.ORIGIN,'content-type':'text/plain'}},{body:{...event(),pad:'x'.repeat(5000)}}])test('reject request '+JSON.stringify(patch).slice(0,55),async()=>{const res=response();await makeHandler(async()=>assert.fail('no upstream'))({...request(),...patch},res);assert(res.code>=400);});
for(const e of C.EVENTS)test('legacy accepted, not persisted: '+e,async()=>{const res=response(),logs=[];await makeHandler(async()=>assert.fail('legacy not stored'),{log:(...v)=>logs.push(v)})(request({event:e,password:'no logging'}),res);assert.equal(res.code,204);assert(!JSON.stringify(logs).includes('password'));});
