const {chromium}=require('playwright');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');
const games=['reaction-rush','perfect-timing','dont-press'];const R=require('../arcade3/core.js');
(async()=>{const server=spawn('python3',['-m','http.server','8787','--directory',path.resolve(__dirname,'..')],{stdio:'ignore'});let browser;
try{await new Promise(r=>setTimeout(r,900));browser=await chromium.launch({headless:true});fs.mkdirSync('arcade3-qa',{recursive:true});
for(const viewport of [{width:1440,height:1120},{width:390,height:844}])for(const game of games){
 const context=await browser.newContext({viewport,isMobile:viewport.width<500,hasTouch:viewport.width<500});const errors=[];
 await context.route('**/community/client.js',route=>route.fulfill({contentType:'text/javascript',body:`window.LoopCommunity={authenticated:false,profile:null,flag:()=>'',config:async()=>({seed:125904,rankedGames:${JSON.stringify(games.map(g=>({game:g,version:R.CONFIG[g].version})))}})};`}));
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8787/arcade3/play.html?game='+game);await page.locator('#start').click();await page.waitForTimeout(1900);
 if(game==='reaction-rush'){const pos=await page.evaluate(()=>{const s=LoopJoltSnapshot().state;return ArcadeRules.targetPosition(s,s.targets[0]);});const box=await page.locator('#game').boundingBox();await page.mouse.click(box.x+pos.x*box.width/1000,box.y+pos.y*box.height/1000);}else if(game==='perfect-timing')await page.locator('#game').click();else{await page.locator('#action').dispatchEvent('pointerdown');await page.waitForTimeout(100);await page.locator('#action').dispatchEvent('pointerup');}
 await page.waitForTimeout(300);assert((await page.evaluate(()=>LoopJoltSnapshot().state.tick))>0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);await page.screenshot({path:`arcade3-qa/${game}-${viewport.width}.png`,fullPage:true});await page.locator('#pause').click();assert(await page.locator('#resume').isVisible());await page.locator('#resume').click();assert(!(await page.evaluate(()=>LoopJoltSnapshot().paused)));await page.locator('#motion').click();await page.locator('#sound').click();assert.deepEqual(errors,[]);await context.close();console.log('UI PASS',game,viewport.width);
}
// Real client bridge with fully mocked authentication and a server-replay endpoint.
for(const game of games){
 const ctx=await browser.newContext();const page=await ctx.newPage();const requests=[];let finishResult=null;
 await page.addInitScript(()=>sessionStorage.setItem('loopjolt_google_session_v1',JSON.stringify({token:'QA-only-not-a-Google-token',expires:Date.now()+3600000})));
 await ctx.route('**/functions/v1/loopjolt-community*',async route=>{const u=new URL(route.request().url()),action=u.searchParams.get('action');let result;if(action==='config')result={loginReady:true,seed:125904,rankedGames:games.map(g=>({game:g,version:R.CONFIG[g].version}))};else if(action==='profile')result={profile:{handle:'TestPilot',country:'KR'}};else if(action==='start'){requests.push('start');result={runId:'11111111-1111-4111-8111-111111111111',game,version:R.CONFIG[game].version,seed:125904};}else if(action==='finish'){const body=route.request().postDataJSON();finishResult=R.replay(game,125904,body.actions,body.ticks);requests.push('finish');result={saved:true,score:finishResult.score};}else result={};await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type'},body:JSON.stringify(result)});});
 await page.goto('http://127.0.0.1:8787/arcade3/play.html?game='+game);await page.waitForFunction(()=>document.querySelector('#identity').textContent.includes('TestPilot'));await page.clock.install();await page.locator('#start').click();await page.clock.runFor(2000);
 if(game==='reaction-rush'){const box=await page.locator('#game').boundingBox();const pos=await page.evaluate(()=>{const s=LoopJoltSnapshot().state;return ArcadeRules.targetPosition(s,s.targets[0]);});await page.mouse.click(box.x+pos.x*box.width/1000,box.y+pos.y*box.height/1000);}
 else if(game==='perfect-timing')await page.locator('#game').click();
 await page.clock.runFor(62000);await page.waitForFunction(()=>document.querySelector('#saveState').textContent.startsWith('Verified'));assert.deepEqual(requests,['start','finish']);assert(finishResult&&Number.isInteger(finishResult.score));assert(!(await page.locator('#start').isDisabled()));console.log('MOCKED RANKED FLOW PASS',game,finishResult.score);await ctx.close();
}
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
