/* QA only: virtual frame clock, normal input, actual core/render/controller. No live writes. */
'use strict';
const {chromium}=require(process.env.PW_MODULE||'playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {bot,pick}=require('./astra-pilot.cjs'),root=path.resolve(__dirname,'../games/astra-sentinel'),out=process.env.QA_OUT||'/tmp/astra-qa';fs.mkdirSync(out,{recursive:true});
const report={checks:[],networkWrites:0,game:'astra-sentinel',version:'astra-v1',scope:'isolated browser, not human playtest'};
const fixture=`(()=>{let t=1000,n=0,q=new Map(),memory=new Map();window.__writes=0;window.__store=memory;Object.defineProperty(performance,'now',{value:()=>t});window.requestAnimationFrame=f=>{q.set(++n,f);return n;};window.cancelAnimationFrame=i=>q.delete(i);window.__frame=(count=1)=>{for(let i=0;i<count;i++){t+=1000/60;let a=[...q.values()];q.clear();for(const f of a)f(t);}};Object.defineProperty(window,'localStorage',{value:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>{memory.set(k,v);__writes++;}}});})();`;
async function load(browser,width=1280,query=''){
const ctx=await browser.newContext({viewport:{width,height:1000},isMobile:width<600,hasTouch:width<600}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>{if(r.request().method()==='POST')report.networkWrites++;return r.abort();});
// Offline text loading changes no game logic. Native local routes have a separate test.
await p.goto('about:blank'+query);await p.setContent(fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,'').replace(/<link[^>]*>/g,''));await p.addStyleTag({content:fs.readFileSync(path.join(root,'style.css'),'utf8')});await p.addScriptTag({content:fixture});for(const f of ['core.js','art.js','app.js'])await p.addScriptTag({content:fs.readFileSync(path.join(root,f),'utf8')});await p.addScriptTag({content:'window.__pilot='+bot.toString()+';window.__pick='+pick.toString()+';'});await p.evaluate(()=>__frame(1));return{ctx,p,errors};}
async function shot(p,name){let done=false;const pump=(async()=>{while(!done){await p.evaluate(()=>__frame(1)).catch(()=>{});await new Promise(r=>setTimeout(r,35));}})();try{await p.screenshot({path:path.join(out,name+'.png'),fullPage:true,timeout:15000,animations:'disabled'});}finally{done=true;await pump;}}
async function check(name,fn){console.log('RUN '+name);await fn();report.checks.push(name);fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(report,null,2));console.log('PASS '+name);}
const stepPilot=async(p,count)=>p.evaluate(count=>{for(let i=0;i<count;i++){const s=AstraDiagnostics.snapshot().state;if(s.phase!=='playing')break;const a=__pilot(s);for(const [code,active] of [['KeyA',a.x<-.27],['KeyD',a.x>.27],['KeyW',a.y<-.27],['KeyS',a.y>.27]])window.dispatchEvent(new KeyboardEvent(active?'keydown':'keyup',{code,bubbles:true}));if(a.dash)window.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true}));__frame(1);}},count);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});try{
for(const width of [360,390,768,1280])await check('entry / controls / pause at '+width,async()=>{const {p,ctx,errors}=await load(browser,width);assert(await p.locator('#play').isEnabled());assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.tick),0);if(width===390||width===1280)await shot(p,'entry-'+width);await p.click('#play');await p.keyboard.down('KeyD');await p.evaluate(()=>__frame(20));await p.keyboard.up('KeyD');assert((await p.evaluate(()=>AstraDiagnostics.snapshot().state.player.x))>370);await p.click('#dash');await p.evaluate(()=>__frame(1));assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.dashes),1);await p.click('#pause');const before=await p.evaluate(()=>AstraDiagnostics.snapshot().state);await p.evaluate(()=>__frame(120));assert.deepEqual(await p.evaluate(()=>AstraDiagnostics.snapshot().state),before);await p.click('#resume');await p.evaluate(()=>__frame(5));assert(!await p.evaluate(()=>AstraDiagnostics.snapshot().paused));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(errors,[]);await ctx.close();});
await check('nine gates / real offered upgrades / three guardians / victory',async()=>{const {p,ctx,errors}=await load(browser,1280,'?capture=1');await p.click('#play');let clears=0,seenBoss=new Set();for(let n=0;n<200;n++){await stepPilot(p,180);let snap=await p.evaluate(()=>AstraDiagnostics.snapshot());const s=snap.state;const boss=s.enemies.find(e=>e.boss&&e.warning===0);if(boss&&!seenBoss.has(boss.boss)){await shot(p,'guardian-'+boss.boss);seenBoss.add(boss.boss);}if(s.phase==='upgrade'){clears++;assert(s.tier===clears);assert(await p.locator('#upgradeDialog').isVisible());if(clears===1||clears===6)await shot(p,'evolution-'+clears);const oldTick=s.tick;await p.evaluate(()=>__frame(12));assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.tick),oldTick);const selected=await p.evaluate(()=>__pick(AstraDiagnostics.snapshot().state));await p.locator('[data-upgrade="'+selected+'"]').click();assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.stage),clears+1);}else if(s.phase==='dead'||s.phase==='victory')break;}
const end=await p.evaluate(()=>AstraDiagnostics.snapshot());fs.writeFileSync(path.join(out,'full-playthrough.json'),JSON.stringify({phase:end.state.phase,tier:end.state.tier,stage:end.state.stage,ticks:end.state.tick,hp:end.state.player.hp,score:end.state.score,kills:end.state.kills,upgrades:end.state.upgrades,clears,seenBoss:[...seenBoss],normalInputOnly:true,capture:true},null,2));assert.equal(end.state.phase,'victory');assert.equal(clears,8);assert.equal(seenBoss.size,3);assert.equal(end.state.tier,9);assert(await p.locator('#resultDialog').isVisible());assert((await p.locator('#resultNote').textContent()).includes('No device record'));assert.equal(await p.evaluate(()=>__writes),0);await shot(p,'victory-desktop');await p.click('#again');assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.tier),0);assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.stage),1);assert.deepEqual(errors,[]);await ctx.close();});
await check('mobile tap-drag / upgrade card fit / result local persistence',async()=>{const {p,ctx,errors}=await load(browser,390);await p.click('#play');const b=await p.locator('#game').boundingBox();await p.mouse.move(b.x+b.width*.5,b.y+b.height*.5);await p.mouse.down();await p.mouse.move(b.x+b.width*.72,b.y+b.height*.5);const x=await p.evaluate(()=>AstraDiagnostics.snapshot().state.player.x);await p.evaluate(()=>__frame(10));assert((await p.evaluate(()=>AstraDiagnostics.snapshot().state.player.x))>x);await p.mouse.up();for(let i=0;i<30;i++){await stepPilot(p,120);if(await p.evaluate(()=>AstraDiagnostics.snapshot().state.phase==='upgrade'))break;}assert(await p.locator('#upgradeDialog').isVisible());await shot(p,'evolution-mobile');for(const choice of await p.locator('.choice').all()){const r=await choice.boundingBox();assert(r.width>=40&&r.height>=44&&r.x>=0&&r.x+r.width<=391);}await p.locator('.choice').first().click();await p.evaluate(()=>{for(const code of ['KeyA','KeyD','KeyW','KeyS'])window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));});for(let i=0;i<120;i++){await p.evaluate(()=>__frame(120));const phase=await p.evaluate(()=>AstraDiagnostics.snapshot().state.phase);if(phase==='upgrade')await p.locator('.choice').first().click();if(phase==='dead'||phase==='victory')break;}assert(await p.locator('#resultDialog').isVisible());await shot(p,'result-mobile');assert((await p.evaluate(()=>JSON.parse(__store.get('loopjolt_astra_v1')).best))>0);assert(!/not saved/.test(await p.locator('#resultNote').textContent()));assert.deepEqual(errors,[]);await ctx.close();});
await check('tab hidden pauses without running unseen / resume',async()=>{const {p,ctx}=await load(browser,390);await p.click('#play');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert(await p.locator('#pauseDialog').isVisible());const tick=await p.evaluate(()=>AstraDiagnostics.snapshot().state.tick);await p.evaluate(()=>__frame(90));assert.equal(await p.evaluate(()=>AstraDiagnostics.snapshot().state.tick),tick);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'));});await p.click('#resume');await p.evaluate(()=>__frame(3));assert((await p.evaluate(()=>AstraDiagnostics.snapshot().state.tick))>tick);await ctx.close();});
assert.equal(report.networkWrites,0);report.passed=true;
}finally{await browser.close();fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(report,null,2));}})().catch(e=>{report.passed=false;report.error=e.stack;fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(report,null,2));console.error(e);process.exitCode=1;});
