const {chromium}=require('playwright');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const path=require('node:path');
(async()=>{const root=path.resolve(__dirname,'..');const server=spawn('python3',['-m','http.server','8765','--directory',root],{stdio:'ignore'});let browser;
try{await new Promise(r=>setTimeout(r,1000));browser=await chromium.launch({headless:true});
for(const [name,size] of [['desktop',{width:1366,height:1000}],['mobile',{width:390,height:844}]]){
 const context=await browser.newContext({viewport:size,isMobile:name==='mobile',hasTouch:name==='mobile'});const errors=[];
 await context.route('**/analytics.js',route=>route.fulfill({contentType:'text/javascript',body:'window.VibeAnalytics={track:()=>{}}'}));
 await context.route('**/functions/v1/loopjolt-community*',route=>route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify(route.request().url().includes('action=config')?{loginReady:false,clientId:'',version:'orbit-v1',seed:125904}:{rows:[]})}));
 let page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/games/orbit-sprint/');await page.locator('#start').click();await page.waitForTimeout(800);await page.locator('#jump').dispatchEvent('pointerdown');await page.waitForTimeout(600);assert(Number((await page.locator('#score').innerText()).replaceAll(',',''))>0);await page.locator('#pause').click();assert.equal(await page.locator('#pause').innerText(),'Resume');await page.locator('#pause').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.close();
 page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/community/');await page.waitForTimeout(500);assert(await page.locator('#empty').isVisible());assert(await page.locator('#login').isDisabled());assert.equal(await page.locator('#country option').count(),250);await page.getByRole('button',{name:'Country standings',exact:true}).click();assert((await page.locator('#rule').innerText()).includes('10 distinct'));assert.deepEqual(errors,[]);console.log(name+' browser smoke PASS');await context.close();
}
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
