const {chromium}=require('playwright');const assert=require('node:assert/strict');const {spawn,execFileSync}=require('node:child_process');const path=require('node:path');
const root=path.resolve(__dirname,'..');execFileSync('npm',['ci','--ignore-scripts','--no-audit','--no-fund'],{cwd:root,stdio:'inherit'});execFileSync(process.execPath,['scripts/build-flags.cjs'],{cwd:root,stdio:'inherit'});
async function flag(page,selector,code='KR'){await page.waitForFunction(({selector,code})=>{const i=document.querySelector(selector+' img.lj-flag');return i&&i.dataset.country===code&&i.complete&&i.naturalWidth>0;},{selector,code});assert.equal(await page.locator(selector+' img.lj-flag').first().getAttribute('src'),'/assets/flags/7.5.0/'+code.toLowerCase()+'.svg');}
(async()=>{const server=spawn('python3',['-m','http.server','8765','--directory',root],{stdio:'ignore'});let browser;try{await new Promise(r=>setTimeout(r,900));browser=await chromium.launch({headless:true});
for(const [name,viewport]of[['desktop',{width:1366,height:1000}],['mobile',{width:390,height:844}]]){const ctx=await browser.newContext({viewport,isMobile:name==='mobile',hasTouch:name==='mobile'}),errors=[],external=[];ctx.on('request',r=>{if(r.resourceType()==='image'&&!r.url().startsWith('http://127.0.0.1:8765/'))external.push(r.url());});await ctx.route('**/api/event',r=>r.fulfill({status:204,body:''}));await ctx.route('**/analytics.js',r=>r.fulfill({contentType:'text/javascript',body:'window.VibeAnalytics={track:()=>{}}'}));
await ctx.route('**/functions/v1/loopjolt-community*',r=>{const u=new URL(r.request().url()),a=u.searchParams.get('action'),game=u.searchParams.get('game'),scope=u.searchParams.get('scope');let data;
if(a==='config')data={loginReady:false,seed:125904,rankedGames:[{game:'orbit-sprint',version:'orbit-v1',title:'Orbit Sprint'},{game:'perfect-timing',version:'pt-sky-v1',title:'Perfect Timing · Skyforge'}]};else if(a==='profile')data={profile:{handle:'TestPilot',country:'KR'}};else if(scope==='nations')data={mode:game==='all'?'overall':'game',rankedGameCount:2,rows:[{rank:1,country_code:'KR',points:game==='all'?2000:592,contributors:1,players:1}]};else data={mode:game==='all'?'overall':'game',rows:[{rank:1,handle:'TestPilot',country_code:'KR',score:592,points:2000,games_played:2}]};return r.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type'},body:JSON.stringify(data)});});
let p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/games/orbit-sprint/');await p.locator('#start').click();await p.waitForTimeout(800);await p.locator('#jump').dispatchEvent('pointerdown');await p.waitForTimeout(500);assert(Number((await p.locator('#score').innerText()).replaceAll(',',''))>0);await p.locator('#pause').click();assert.equal(await p.locator('#pause').innerText(),'Resume');await p.close();
p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/community/?game=perfect-timing');await flag(p,'#rows tr');assert((await p.locator('#rows tr').innerText()).includes('592'));assert(!(await p.locator('#accountDialog').isVisible()));await p.locator('#leagueIdentity').click();assert(await p.locator('#login').isDisabled());assert.equal(await p.locator('#country option').count(),250);await p.locator('#closeAccount').click();
await p.getByRole('button',{name:'Country standings',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#nameHeader').textContent==='Country');await flag(p,'#rows tr');await p.getByRole('button',{name:'Players',exact:true}).click();await p.selectOption('#gameFilter','all');await p.waitForFunction(()=>document.querySelector('#scoreHeader').textContent==='Championship pts');await flag(p,'#rows tr');assert((await p.locator('#rows tr').innerText()).includes('2,000'));await p.locator('#toggleFilters').click();await p.selectOption('#countryFilter','JP');await flag(p,'#countryFilterFlagPreview','JP');assert.equal(new URL(p.url()).searchParams.get('scope'),'country');
await p.evaluate(()=>sessionStorage.setItem('loopjolt_google_session_v1',JSON.stringify({token:'QA-not-a-real-token',expires:Date.now()+3600000})));await p.goto('http://127.0.0.1:8765/community/?panel=profile');await p.waitForFunction(()=>document.querySelector('#accountTitle').textContent.includes('TestPilot'));await flag(p,'#accountTitle');await p.locator('#profileDetails>summary').click();await flag(p,'#countryFlagPreview');await p.selectOption('#country','US');await flag(p,'#countryFlagPreview','US');await p.selectOption('#country','');assert.equal(await p.locator('#countryFlagPreview img').count(),0);
const safe=await p.evaluate(()=>{const n=document.createElement('div');LoopCommunity.renderFlagLabel(n,'../../bad','<img src=x onerror=alert(1)>');return{images:n.querySelectorAll('img').length,text:n.textContent};});assert.equal(safe.images,0);assert(safe.text.includes('<img'));await p.keyboard.press('Escape');assert(!(await p.locator('#accountDialog').isVisible()));assert.equal(await p.locator('#leagueIdentity').evaluate(n=>n===document.activeElement),true);
for(const[url,selector]of[['/games/orbit-sprint/','#playerLink'],['/arcade3/play.html?game=reaction-rush','#identity'],['/arcade3/play.html?game=perfect-timing','#identity'],['/arcade3/play.html?game=dont-press','#identity']]){await p.goto('http://127.0.0.1:8765'+url);await p.waitForFunction(s=>document.querySelector(s).textContent.includes('TestPilot'),selector);await flag(p,selector);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
await ctx.route('**/assets/flags/7.5.0/br.svg',r=>r.abort());await p.evaluate(()=>{const n=document.createElement('div');n.id='fallback';document.body.append(n);LoopCommunity.renderFlagLabel(n,'BR','SafePilot');});await p.waitForFunction(()=>document.querySelector('#fallback .lj-flag-placeholder')?.textContent==='BR');assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await ctx.close();console.log(name+' identity/image/game smoke PASS');}
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
