const {test}=require('node:test');const assert=require('node:assert/strict');const R=require('../challengers/core.js');
function simulate(game,bot,seed=123456){const s=R.create(game,seed),actions=[];while(s.alive){const a=bot?.(s)||null;if(a){actions.push([s.tick,...a]);}R.step(s,a);}return{s,actions,replay:R.replay(game,seed,actions,s.tick)};}
test('all challenger configs are distinct and bounded',()=>{assert.deepEqual(Object.keys(R.CONFIG),['gyro-drop','core-pins','nova-merge']);for(const [g,c] of Object.entries(R.CONFIG)){assert(c.ticks<=5400);assert.match(c.version,/v1$/);assert.equal(R.create(g,1).game,g);}});
test('same seed creates identical initial states',()=>{for(const g of Object.keys(R.CONFIG))assert.deepEqual(R.create(g,42),R.create(g,42));});
test('different seeds change generated challenges',()=>{assert.notDeepEqual(R.create('gyro-drop',1).rings,R.create('gyro-drop',2).rings);assert.notDeepEqual(R.create('core-pins',1).hazards,R.create('core-pins',2).hazards);assert.notEqual(R.create('nova-merge',1).rng,R.create('nova-merge',2).rng);});
test('gyro controlled bot can chain falls and replay exactly',()=>{const out=simulate('gyro-drop',s=>{if(s.tick>=s.nextBounce-18){const r=s.rings[s.ring];if(!r)return null;const target=R.mod(-r.gap,3600),raw=R.mod(target-s.rotation+1800,3600)-1800,delta=Math.max(-180,Math.min(180,raw));return delta?['turn',delta]:null;}return null;});assert(out.s.falls>8);assert.equal(out.replay.score,out.s.score);assert.equal(out.replay.maxCombo,out.s.maxCombo);});
test('core pins scores only clean throws and replay matches',()=>{const out=simulate('core-pins',s=>{if(s.tick%24)return null;const hit=R.mod(900-s.rotation,3600),blocked=s.pins.some(p=>R.dist(p,hit)<210)||s.hazards.some(p=>R.dist(p,hit)<185);return blocked?null:['throw'];});assert(out.s.hits>5);assert.equal(out.replay.score,out.s.score);assert.equal(out.replay.ticks,out.s.tick);});
test('nova merge chains and replay matches',()=>{let c=0;const out=simulate('nova-merge',s=>s.tick%18?null:['drop',(c++%3)]);assert(out.s.drops>10);assert(out.s.merges>0);assert.equal(out.replay.score,out.s.score);assert.equal(out.replay.maxCombo,out.s.maxCombo);});
test('gyro smash is consumed after one assisted fall',()=>{const s=R.create('gyro-drop',1);s.smash=1;s.combo=0;s.nextBounce=s.tick;const before=s.ring;R.step(s,null);assert.equal(s.ring,before+1);assert.equal(s.smash,0);assert.equal(s.combo,0);});
test('gyro rejects impossible turn inputs',()=>{assert.throws(()=>R.replay('gyro-drop',1,[[1,'turn',181]],100));assert.throws(()=>R.replay('gyro-drop',1,[[1,'turn',0]],100));});
test('pins rejects duplicate ticks and unknown actions',()=>{assert.throws(()=>R.replay('core-pins',1,[[3,'throw'],[3,'throw']],100));assert.throws(()=>R.replay('core-pins',1,[[2,'drop']],100));});
test('merge rejects invalid columns and out-of-order inputs',()=>{assert.throws(()=>R.replay('nova-merge',1,[[1,'drop',7]],100));assert.throws(()=>R.replay('nova-merge',1,[[4,'drop',0],[2,'drop',1]],100));});
test('unfinished runs never verify',()=>{for(const g of Object.keys(R.CONFIG))assert.throws(()=>R.replay(g,1,[],10));});
test('actions at or beyond terminal tick never verify',()=>{const out=simulate('core-pins',null);assert.throws(()=>R.replay('core-pins',123456,[[out.s.tick,'throw']],out.s.tick));});
test('score returned by verifier is always server-computed and bounded',()=>{for(const g of Object.keys(R.CONFIG)){const out=simulate(g,null,9);assert.equal(out.replay.score,out.s.score);assert(out.replay.score>=0&&out.replay.score<=50000);}});
