'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),fs=require('node:fs'),path=require('node:path');
const FX=require('../feel/phaser-fx.js'),Audio=require('../feel/audio.js');
function scene(){
 const objects=[],ts=[],s={events:new EventEmitter(),add:{},tweens:{},cameras:{main:{shakeEffect:{isRunning:false},shake(d,i){this.shakes=(this.shakes||0)+1;this.last=[d,i];}}}};
 const obj=(x,y)=>{const p={scene:s,x,y,rotation:0,scaleX:1,scaleY:1,alpha:1,setTint(t){this.tint=t;return this},setScale(x,y=x){this.scaleX=x;this.scaleY=y;return this},setPosition(x,y){this.x=x;this.y=y;return this},setAlpha(a){this.alpha=a;return this},setText(t){this.text=t;return this},setColor(c){this.color=c;return this},destroy(){this.dead=true;this.scene=null;}};objects.push(p);return p;};
 s.add.image=(x,y,key)=>Object.assign(obj(x,y),{key});s.add.text=(x,y,t,style)=>Object.assign(obj(x,y),{text:t,style});
 s.tweens.add=c=>{const t={config:c,removed:false,remove(){this.removed=true;},finish(){for(const k of ['alpha','scaleX','scaleY'])if(k in c)c.targets[k]=c[k];c.onComplete?.();}};ts.push(t);return t;};
 return {s,objects,ts,obj};
}
function context(){
 const nodes=[],c={currentTime:3,state:'suspended',destination:{},created:0,resumes:0,suspends:0,closes:0};
 const param=()=>({value:0,events:[],setValueAtTime(...a){this.events.push(['set',...a]);this.value=a[0]},exponentialRampToValueAtTime(...a){this.events.push(['ramp',...a]);},cancelScheduledValues(){}});
 c.createGain=()=>{const n={gain:param(),connect(){},disconnect(){this.disconnected=true}};nodes.push(n);return n;};
 c.createOscillator=()=>{const n={frequency:param(),connect(){},start(t){this.started=t},stop(t){this.stopped=t??0},disconnect(){this.disconnected=true}};nodes.push(n);c.created++;return n;};
 c.resume=async()=>{c.resumes++;c.state='running'};c.suspend=async()=>{c.suspends++;c.state='suspended'};c.close=async()=>{c.closes++;c.state='closed'};
 return {c,nodes};
}
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('kit import does not load Phaser/audio context or mutate global game state',()=>{assert.equal(typeof FX.create,'function');assert.equal(typeof Audio.create,'function');});
test('scene is required, but generic scene does not need Descent',()=>{assert.throws(()=>FX.create(null));const {s}=scene();const fx=FX.create(s);assert.equal(fx.snapshot().particles,0);fx.destroy();});
test('particle hard cap is shared across bursts and cleanup destroys owned sprites',()=>{const {s,objects,obj}=scene(),unrelated=obj(2,3),fx=FX.create(s,{maxParticles:5});assert.equal(fx.burst({x:0,y:0,texture:'other-art',count:99}),5);assert.equal(fx.burst({x:0,y:0,texture:'other-art'}),0);fx.clear();assert(!unrelated.dead);assert(objects.slice(1).every(p=>p.dead));assert.equal(fx.snapshot().particles,0);});
test('fragment TTL frees budget, with exact legacy frame integration',()=>{const {s,objects}=scene(),fx=FX.create(s,{random:()=>.5});fx.burst({x:100,y:200,texture:'p',count:1});fx.update(16.667);assert.equal(objects[0].x,100);assert.equal(objects[0].y,195.6);for(let i=0;i<55;i++)fx.update(16.667);assert.equal(fx.snapshot().particles,0);assert(objects[0].dead);});
test('different art profiles change particle style without scoring code',()=>{const a=scene(),b=scene();FX.create(a.s,{random:()=>.5}).burst({x:3,y:4,texture:'star',tint:123,count:1});FX.create(b.s,{random:()=>.5}).burst({x:10,y:20,texture:'water',tint:456,count:1});assert.equal(a.objects[0].key,'star');assert.equal(b.objects[0].tint,456);});
test('invalid positions and giant counts cannot allocate unlimited effects',()=>{const {s}=scene(),fx=FX.create(s,{maxParticles:1e9});assert.equal(fx.burst({x:NaN,y:0,texture:'p',count:Infinity}),0);assert.equal(fx.burst({x:0,y:0,texture:'p',count:1e9}),200);fx.update(NaN);assert.equal(fx.snapshot().particles,200);});
test('float text has independent cap, expiration and no markup execution',()=>{const {s,objects}=scene(),fx=FX.create(s,{maxFloaters:1});assert(fx.floatText({x:1,y:2,text:'<img src=x>'}));assert.equal(objects[0].text,'<img src=x>');assert.equal(fx.floatText({x:1,y:2,text:'2'}),false);fx.update(700);assert(objects[0].dead);assert.equal(fx.snapshot().floaters,0);});
test('notice replacement cancels only kit-owned tween',()=>{const {s,obj,ts}=scene(),a=obj(1,2),b=obj(3,4),fx=FX.create(s);const outside=s.tweens.add({targets:b});fx.notice(a,'one');fx.notice(a,'two');assert(ts[1].removed);assert(!outside.removed);assert.equal(fx.snapshot().tweens,1);ts[2].finish();assert.equal(fx.snapshot().tweens,0);});
test('pulse reset restores borrowed object without destroying it',()=>{const {s,obj}=scene(),p=obj(0,0),fx=FX.create(s);fx.pulse(p,{toX:2,toY:3});fx.clear();assert.equal(p.scaleX,2);assert.equal(p.scaleY,3);assert(!p.dead);});
test('reduced motion lowers particle count and removes shake/pulse',()=>{const {s,obj}=scene(),p=obj(0,0),fx=FX.create(s,{reduced:()=>true});assert.equal(fx.burst({x:0,y:0,texture:'p',count:28}),3);assert.equal(fx.shake(),false);fx.pulse(p);assert.equal(fx.snapshot().tweens,0);assert.equal(p.scaleX,.47);});
test('switching reduced-motion on settles an in-progress pulse',()=>{let reduced=false;const {s,obj}=scene(),p=obj(0,0),fx=FX.create(s,{reduced:()=>reduced});fx.pulse(p);reduced=true;fx.update(1);assert.equal(p.scaleX,.47);assert.equal(fx.snapshot().tweens,0);});
test('shake is capped and does not replace an unrelated active effect',()=>{const {s}=scene(),fx=FX.create(s);fx.shake(999,.5);assert.deepEqual(s.cameras.main.last,[200,.008]);s.cameras.main.shakeEffect.isRunning=true;assert.equal(fx.shake(),false);});
test('shutdown removes owned sprites/tweens/listeners; remount is isolated',()=>{const {s,obj}=scene(),p=obj(0,0),fx=FX.create(s);fx.burst({x:1,y:2,texture:'p'});fx.notice(p,'x');s.events.emit('shutdown');assert(fx.snapshot().disposed);assert.equal(s.events.listenerCount('destroy'),0);fx.destroy();assert.equal(fx.burst({x:0,y:0,texture:'p'}),0);const next=FX.create(s);assert(!next.snapshot().disposed);next.destroy();});
test('100 resets do not accumulate effect objects or tween listeners',()=>{const {s,obj,objects}=scene(),p=obj(0,0),fx=FX.create(s);for(let i=0;i<100;i++){fx.burst({x:1,y:2,texture:'p',count:20});fx.floatText({x:0,y:0,text:'1'});fx.notice(p,'x');fx.clear();}assert.equal(objects.filter(n=>!n.dead).length,1);assert.equal(fx.snapshot().tweens,0);assert.equal(s.events.listenerCount('shutdown'),1);});
test('audio context is lazy and off produces no oscillator',async()=>{let made=0;const {c}=context(),a=Audio.create({contextFactory:()=>{made++;return c}});assert.equal(a.note(440),false);await a.enable(false);assert.equal(made,0);await a.enable(true);assert.equal(made,1);await a.enable(true);assert.equal(made,1);});
test('audio voice cap includes future scheduled voices',async()=>{const {c,nodes}=context(),a=Audio.create({contextFactory:()=>c,maxVoices:2});await a.enable(true);assert(a.note(440,.2,'sine',.2,2));assert(a.note(880));assert.equal(a.note(660),false);assert.equal(a.snapshot().voices,2);nodes.find(n=>n.frequency).onended();assert(a.note(660));});
test('note parameter envelope preserves the original timbre recipe',async()=>{const {c,nodes}=context(),a=Audio.create({contextFactory:()=>c});await a.enable(true);a.note(330,.16,'triangle',.28,0,620);const o=nodes.find(n=>n.frequency);assert.equal(o.type,'triangle');assert.deepEqual(o.frequency.events,[['set',330,3],['ramp',620,3.16]]);assert.equal(o.started,3);assert.equal(o.stopped,3.18);});
test('silencing stops/disconnects all scheduled voices before suspend',async()=>{const {c,nodes}=context(),a=Audio.create({contextFactory:()=>c});await a.enable(true);a.note(440,.3,'sine',.1,1);await a.enable(false);assert.equal(a.snapshot().voices,0);assert.equal(c.state,'suspended');assert(nodes.find(n=>n.frequency).disconnected);await a.enable(true);assert.equal(a.snapshot().voices,0);});
test('clear cancels old cue at replay without turning off sound preference',async()=>{const {c}=context(),a=Audio.create({contextFactory:()=>c});await a.enable(true);a.note(440);a.clear();assert(a.enabled);assert.equal(a.snapshot().voices,0);assert(a.note(440));});
for(const args of [[NaN],[0],[440,0],[440,.2,'custom'],[440,.2,'sine',0],[440,.2,'sine',.2,-1],[440,.2,'sine',.2,0,-1]])test('invalid note is ignored: '+JSON.stringify(args),async()=>{const {c}=context(),a=Audio.create({contextFactory:()=>c});await a.enable(true);assert.equal(a.note(...args),false);assert.equal(c.created,0);});
test('unsupported audio is silent without throwing',async()=>{const a=Audio.create({contextFactory:()=>null});assert.equal(await a.enable(true),false);assert.equal(a.note(440),false);await a.destroy();});
test('rejected browser resume does not leak unhandled errors or voices',async()=>{const {c}=context();c.resume=async()=>{throw Error('blocked')};const a=Audio.create({contextFactory:()=>c});assert.equal(await a.enable(true),false);assert.equal(a.enabled,false);});
test('rapid on then off cannot unmute via late resume',async()=>{const {c,nodes}=context(),d=deferred();c.resume=async()=>{await d.promise;c.state='running'};const a=Audio.create({contextFactory:()=>c}),on=a.enable(true);await a.enable(false);d.resolve();await on;assert.equal(a.enabled,false);assert.equal(c.state,'suspended');assert.equal(nodes[0].gain.value,0);});
test('rapid off then on ends running even when suspend resolves late',async()=>{const {c}=context(),a=Audio.create({contextFactory:()=>c});await a.enable(true);const d=deferred();c.suspend=async()=>{await d.promise;c.state='suspended'};const off=a.enable(false);await a.enable(true);d.resolve();await off;assert.equal(c.state,'running');assert(a.enabled);});
test('destroy during pending resume never reopens audio',async()=>{const {c}=context(),d=deferred();c.resume=async()=>{await d.promise;/* close is terminal */};const a=Audio.create({contextFactory:()=>c}),on=a.enable(true);await a.destroy();d.resolve();await on;assert(a.snapshot().disposed);assert.equal(a.snapshot().state,'uninitialized');assert.equal(await a.enable(true),false);});
test('audio destroy is idempotent and closes the owned context once',async()=>{const {c}=context(),a=Audio.create({contextFactory:()=>c});await a.enable(true);a.note(440);await a.destroy();await a.destroy();assert.equal(c.closes,1);assert.equal(a.snapshot().voices,0);});
test('sequence is bounded by voice budget',async()=>{const {c}=context(),a=Audio.create({contextFactory:()=>c,maxVoices:3});await a.enable(true);assert.equal(a.sequence(Array.from({length:100},()=>[440])),3);});
test('presentational modules have no network, storage or canonical-rules references',()=>{for(const f of ['phaser-fx.js','audio.js']){const src=fs.readFileSync(path.join(__dirname,'../feel',f),'utf8');assert(!/\b(?:fetch|localStorage|sessionStorage|DescentRules|LoopCommunity|requestAnimationFrame|setTimeout)\b/.test(src));}});
