// Synthetic fixtures only. No production sign-ins, scores or profile writes.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),path=require('node:path'),fs=require('node:fs');
const base='http://127.0.0.1:8789';const games=[['orbit-sprint','Orbit Sprint','orbit-v1'],['reaction-rush','Reaction Rush · Neon Siege','rr-neon-v1'],['perfect-timing','Perfect Timing · Skyforge','pt-sky-v1'],['dont-press',"Don't Press · Reactor Shift",'dp-core-v1']].map(([game,title,version])=>({game,title,version}));
const player={rank:1,handle:'FixturePilot',country_code:'KR',score:592,points:2000,games_played:2};const nation={rank:1,country_code:'KR',points:2000,players:1,contributors:1};
async function ready(page){await page.waitForFunction(()=>document.querySelector('#boardStatus').textContent.startsWith('Updated'));}
async function image(page,selector){await page.waitForFunction(selector=>{const img=document.querySelector(selector);return img&&img.complete&&img.naturalWidth>0;},selector);}
(async()=>{let browser;const server=spawn('python3',['-m','http.server','8789','--directory',path.resolve(__dirname,'..')],{stdio:'ignore'});try{await new Promise(r=>setTimeout(r,900));browser=await chromium.launch({headless:true});fs.mkdirSync('league-qa',{recursive:true});
for(const width of [360,390,768,1440]){const context=await browser.newContext({viewport:{width,height:width>1000?1100:900},isMobile:width<500,hasTouch:width<500,locale:'en-US'});const errors=[],writes=[];let failed=false,empty=false,slowAll=false;await context.route('**/api/event',r=>r.fulfill({status:204,body:''}));
await context.route('**/functions/v1/loopjolt-community*',async route=>{const u=new URL(route.request().url()),action=u.searchParams.get('action');if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type'}});if(route.request().method()==='POST'&&action!=='profile')writes.push(action);
let data;if(action==='config')data={loginReady:true,seed:125904,rankedGames:games};else if(action==='profile')data={profile:{handle:'FixturePilot',country:'KR'}};else{if(failed)return route.fulfill({status:503,contentType:'application/json',body:'{}',headers:{'Access-Control-Allow-Origin':'*'}});const overall=u.searchParams.get('game')==='all',nations=u.searchParams.get('scope')==='nations';data={game:u.searchParams.get('game'),mode:overall?'overall':'game',rankedGameCount:4,countryRule:'Country standings sum the top 10 distinct players best scores.',rows:empty?[]:[nations?nation:player]};if(slowAll&&overall)await new Promise(r=>setTimeout(r,450));}
try{await route.fulfill({contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type'},body:JSON.stringify(data)});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/');await image(page,'#homeNations img.lj-flag');assert.equal(await page.locator('.game-card').count(),4);assert((await page.locator('#homeNations').innerText()).includes('2,000'));assert.equal(await page.locator('#homeNations .country-row').count(),1);assert.equal(await page.locator('.nation-invite').count(),1);await page.locator('#gameSearch').fill('precision');assert.equal(await page.locator('.game-card:visible').count(),1);await page.locator('#gameSearch').fill('no such game');assert(await page.locator('#noGames').isVisible());await page.locator('#gameSearch').fill('');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'league-qa/home-'+width+'.png',fullPage:true});
await page.goto(base+'/community/?game=perfect-timing&scope=world');await ready(page);await image(page,'#rows img.lj-flag');assert.equal(await page.locator('#gameFilter').inputValue(),'perfect-timing');assert((await page.locator('#rows').innerText()).includes('592'));assert(await page.locator('#profileDetails').isHidden());await page.getByRole('button',{name:'Country standings',exact:true}).click();await ready(page);assert.equal(await page.locator('#nameHeader').innerText(),'COUNTRY');await page.locator('#boardSearch').fill('impossible');assert(await page.locator('#searchEmpty').isVisible());assert.equal(await page.locator('#rows tr').count(),0);await page.locator('#boardSearch').fill('');assert.equal(await page.locator('#rows tr').count(),1);
await page.selectOption('#gameFilter','all');await ready(page);assert.equal(new URL(page.url()).searchParams.get('game'),'all');assert.equal(await page.locator('#scoreHeader').innerText(),'CHAMPIONSHIP');assert((await page.locator('#rows tr a').getAttribute('href')).includes('country=KR'));
failed=true;await page.locator('#refreshBoard').click();await page.waitForFunction(()=>document.querySelector('#boardStatus').textContent.includes('unavailable'));assert.equal(await page.locator('#rows tr').count(),0);assert(!(await page.locator('#refreshBoard').isDisabled()));failed=false;empty=true;await page.locator('#refreshBoard').click();await ready(page);assert(await page.locator('#empty').isVisible());empty=false;await page.locator('#refreshBoard').click();await ready(page);
// The last selection must win even if an earlier response is slower.
slowAll=true;await page.getByRole('button',{name:'Players',exact:true}).click();await page.selectOption('#gameFilter','perfect-timing');await ready(page);await page.waitForTimeout(550);assert.equal(await page.locator('#scoreHeader').innerText(),'SCORE');assert.equal(await page.locator('#gameFilter').inputValue(),'perfect-timing');slowAll=false;
await page.evaluate(()=>sessionStorage.setItem('loopjolt_google_session_v1',JSON.stringify({token:'QA-only',expires:Date.now()+3600000})));await page.goto(base+'/community/?game=all&scope=country');await page.waitForFunction(()=>document.querySelector('#accountTitle').textContent.includes('FixturePilot'));await page.waitForFunction(()=>document.querySelector('#countryFilter').value==='KR');await ready(page);assert.equal(new URL(page.url()).searchParams.get('country'),'KR');await image(page,'#leagueIdentity img.lj-flag');assert.equal(await page.locator('#rows .is-me').count(),1);assert(!(await page.locator('#profileDetails').evaluate(n=>n.open)));await page.locator('#profileDetails summary').click();await image(page,'#countryFlagPreview img.lj-flag');
const safe=await page.evaluate(()=>({bad:WorldLeague.safeReturn('https://example.org/arcade3/play?game=perfect-timing'),good:WorldLeague.safeReturn('/arcade3/play?game=perfect-timing&capture=1'),xss:(()=>{const n=WorldLeague.node('span','<img src=x>');return n.querySelectorAll('img').length;})()}));assert.equal(safe.bad,null);assert.equal(safe.good,'/arcade3/play?game=perfect-timing');assert.equal(safe.xss,0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'league-qa/rankings-'+width+'.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);console.log('LEAGUE UI PASS',width,'home,flags,filters,URL,error,retry,empty,stale response,identity');await context.close();}
}finally{if(browser)await browser.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
