/* Offline real-browser fixtures + canonical input parity. No live identity or DB writes. */
'use strict';
const {chromium}=require(process.env.PW_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),repo=path.resolve(root,'..'),out=process.env.PROOF24_OUT||'/tmp/proof24-qa';fs.mkdirSync(out,{recursive:true});
const baseline=f=>process.env.BASELINE_DIR?fs.readFileSync(path.join(process.env.BASELINE_DIR,'vibe-arcade',f),'utf8'):cp.execFileSync('git',['show',process.env.PROOF24_BASE_REF+':vibe-arcade/'+f],{cwd:repo,encoding:'utf8'});
const fixture=`(()=>{
 let time=1000,queue=new Map(),id=0,player={handle:'QA_Proof',country:'KR'},stored=0,storage=new Map();
 window.__opt={failConfig:false,delayConfig:false,guest:false,failStart:false,delayStart:false,failFinish:false,delayFinish:false,expire:false,badVersion:false,badBoard:false};
 window.__calls={start:[],finish:[],boards:[],events:[],storage:[]};
 Object.defineProperty(window,'localStorage',{value:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{storage.set(k,String(v));__calls.storage.push([k,String(v)]);},removeItem:k=>storage.delete(k)}});
 Object.defineProperty(performance,'now',{value:()=>time});Date.now=()=>1789894892000+time;
 window.requestAnimationFrame=f=>{queue.set(++id,f);return id;};window.cancelAnimationFrame=i=>queue.delete(i);
 window.__qa={frame:(ms=16.667)=>{time+=ms;const q=[...queue.values()];queue.clear();q.forEach(f=>f(time));},frames:n=>{for(let i=0;i<n;i++)__qa.frame();}};
 window.LoopCommunity={get profile(){return __opt.guest?null:player;},get authenticated(){return !__opt.guest;},endpoint:'https://qa.invalid/board',
 config:async()=>{if(__opt.failConfig)throw Error('request_failed');const c={seed:7,loginReady:true,rankedGames:[{game:'core-pins',version:'cp-phaser-v1'}]};if(__opt.delayConfig)return await new Promise(r=>window.__releaseConfig=()=>r(c));return c;},me:async()=>__opt.guest?null:player,
 renderFlagLabel:(el,c,h)=>{el.textContent=c+' '+h;},countryName:()=> 'South Korea',
 api:async(action,body)=>{if(action==='start'){__calls.start.push(body);if(__opt.failStart)throw Error('request_failed');const r={game:'core-pins',version:__opt.badVersion?'bad':'cp-phaser-v1',seed:7,runId:'00000000-0000-4000-8000-'+String(__calls.start.length).padStart(12,'0')};if(__opt.delayStart)return await new Promise(x=>window.__releaseStart=()=>x(r));return r;}
 if(action==='finish'){__calls.finish.push(JSON.parse(JSON.stringify(body)));if(__opt.expire){player=null;throw Error('invalid_or_expired_login');}if(__opt.failFinish){__opt.failFinish=false;throw Error('request_failed');}const v=ChallengerRules.replay('core-pins',7,body.actions,body.ticks);stored=v.score;const r={saved:true,score:stored};if(__opt.delayFinish){__opt.delayFinish=false;return await new Promise(x=>window.__releaseFinish=()=>x(r));}return r;}}
 };
 window.fetch=async(input)=>{const u=new URL(input);__calls.boards.push(u.searchParams.toString());if(__opt.badBoard)throw Error('offline');return {ok:true,json:async()=>({version:'cp-phaser-v1',rows:u.searchParams.get('scope')==='nations'?[{country_code:'KR',rank:1,score:stored}]:[{handle:'QA_Proof',country_code:'KR',rank:1,score:stored}]})};};
 window.LJTelemetry={track:(...a)=>__calls.events.push(a)};
})();`;
const afterFiles=['runtime/core.js','runtime/community-adapter.js','shell/core.js','feel/phaser-fx.js','feel/audio.js','core-pins/shell.js','core-pins/feel.js','core-pins/view.js','core-pins/app.js'];
async function load(browser,{width=390,before=false,game='core-pins',capture=false,opt={}}={}){
 const ctx=await browser.newContext({viewport:{width,height:1000},isMobile:width<600,hasTouch:width<600,reducedMotion:'reduce'}),p=await ctx.newPage();p.errors=[];p.requests=[];p.on('pageerror',e=>p.errors.push(e.message));p.on('request',r=>p.requests.push(r.url()));
 let html=fs.readFileSync(path.join(root,'challengers/play.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,'').replace(/<link rel="stylesheet"[^>]+>/g,'');await p.setContent(html);
 await p.addStyleTag({content:fs.readFileSync(path.join(root,'league/simple.css'),'utf8')+fs.readFileSync(path.join(root,'community/flags.css'),'utf8')+fs.readFileSync(path.join(root,'challengers/style.css'),'utf8')+(!before&&game==='core-pins'?fs.readFileSync(path.join(root,'core-pins/style.css'),'utf8'):'')});
 await p.addScriptTag({content:fixture});await p.evaluate(x=>Object.assign(__opt,x),opt);
 for(const file of ['vendor/phaser-3.90.0.min.js','arcade3/clock.js','challengers/core.js'])await p.addScriptTag({content:fs.readFileSync(path.join(root,file),'utf8')});
 await p.evaluate(()=>{let s=null,actions=[];const create=ChallengerRules.create,step=ChallengerRules.step;ChallengerRules.create=(...args)=>{s=create(...args);actions=[];return s;};ChallengerRules.step=(state,a)=>{if(a)actions.push([state.tick,...a]);return step(state,a);};window.__audit={state:()=>JSON.parse(JSON.stringify(s)),trace:()=>actions.map(x=>x.slice())};});
 const scripts=before||game!=='core-pins'?['challengers/game.js']:['core-pins/bundle.js'];
 for(const file of scripts){let text=before?baseline(file):fs.readFileSync(path.join(root,file),'utf8');text=text.replace(/new URLSearchParams\(location.search\)/g,"new URLSearchParams('game="+game+(capture?'&capture=1':'')+"')");await p.addScriptTag({content:text});}
 await p.waitForTimeout(60);await p.evaluate(()=>__qa.frames(3));await p.waitForSelector('#phaser-game canvas');await p.waitForTimeout(40);return p;
}
async function start(p,ranked=false){await p.click(ranked?'#ranked':'#primary');await p.waitForTimeout(20);}
async function end(p){await p.evaluate(()=>{
 let landed=false;
 for(let i=0;i<3605;i++){
  const s=__audit.state();if(!s.alive)break;
  let speed=s.speed;if(s.tick%420===0&&s.tick>0)speed=-speed+(speed>0?2:-2);
  const rotation=ChallengerRules.mod(s.rotation+speed+(Math.floor(s.tick/420)%4===3?Math.round(Math.sin(s.tick/18)*2):0),3600),hit=ChallengerRules.mod(900-rotation,3600);
  const minPin=s.pins.length?Math.min(...s.pins.map(x=>ChallengerRules.dist(x,hit))):9999,minHaz=s.hazards.length?Math.min(...s.hazards.map(x=>ChallengerRules.dist(x,hit))):9999;
  if(!landed&&minPin>220&&minHaz>200||landed&&(minPin<130||minHaz<120))window.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',key:' ',keyCode:32,which:32,bubbles:true}));
  __qa.frame();if(__audit.state().hits>0)landed=true;
 }
});await p.waitForTimeout(50);assert(await p.locator('#resultDialog').isVisible());}
async function cleanPlay(p,n=160){await p.evaluate(n=>{for(let i=0;i<n;i++){const s=__audit.state();if(!s.alive)break;if(s.tick%23===0)window.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',key:' ',keyCode:32,which:32,bubbles:true}));__qa.frame();}},n);await p.waitForTimeout(30);}
async function shot(p,file){await p.screenshot({path:path.join(out,file),fullPage:true});}
let checks=0;async function test(name,fn){await fn();console.log('PASS',++checks,name);}
(async()=>{let b;const report=[];try{
 b=await chromium.launch({headless:true,...(process.env.PW_EXECUTABLE?{executablePath:process.env.PW_EXECUTABLE}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});
 for(const width of [360,390,768,1280])await test('practice result/replay '+width,async()=>{const p=await load(b,{width});await start(p);await end(p);assert.equal(await p.evaluate(()=>__calls.finish.length),0);assert((await p.locator('#saveState').innerText()).includes('Practice'));await shot(p,'practice-'+width+'.png');await p.click('#again');await p.waitForTimeout(20);await p.evaluate(()=>__qa.frames(2));assert(await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));assert(!(await p.locator('#resultDialog').isVisible()));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(p.errors,[]);assert.deepEqual(p.requests,[]);await p.context().close();});
 if(process.env.BASELINE_DIR||process.env.PROOF24_BASE_REF)await test('canonical before/after state + input-only finish + scene parity',async()=>{
  for(const width of [390,1280]){const samples=[];
   for(const before of [true,false]){const p=await load(b,{width,before});const prefix=(before?'before':'after')+'-'+width;await p.locator('#phaser-game canvas').screenshot({path:path.join(out,prefix+'-canvas.png')});await start(p,true);await end(p);
    const sample=await p.evaluate(()=>({state:__audit.state(),trace:__audit.trace(),finish:__calls.finish,score:document.querySelector('#resultScore').textContent,meta:document.querySelector('#resultMeta').textContent,save:document.querySelector('#saveState').textContent}));samples.push(sample);await shot(p,prefix+'-result.png');assert.deepEqual(p.errors,[]);await p.context().close();}
   fs.writeFileSync(path.join(out,'canonical-'+width+'.json'),JSON.stringify(samples,null,2));assert.deepEqual(samples[0],samples[1]);report.push({width,canonical:true,payload:true,score:samples[1].state.score,ticks:samples[1].state.tick,actions:samples[1].trace.length});}
 });
 await test('ranked failure -> exact same run retry; no claimed score',async()=>{const p=await load(b,{opt:{failFinish:true}});await start(p,true);await end(p);assert(await p.locator('#pinsRetry').isVisible());await p.click('#pinsRetry');await p.waitForTimeout(50);assert((await p.locator('#saveState').innerText()).includes('Verified'));const calls=await p.evaluate(()=>__calls.finish);assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1]);assert.deepEqual(Object.keys(calls[0]).sort(),['actions','runId','ticks']);await p.context().close();});
 await test('start failure and mismatched version leave practice available',async()=>{for(const opt of [{failStart:true},{badVersion:true}]){const p=await load(b,{opt});await start(p,true);assert(await p.locator('#primary').isVisible());assert(!await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));assert((await p.locator('#status').innerText()).includes('failed'));await p.click('#primary');assert(await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));await p.context().close();}});
 await test('expired auth is not verified and cannot retry',async()=>{const p=await load(b,{opt:{expire:true}});await start(p,true);await end(p);assert((await p.locator('#saveState').innerText()).includes('expired'));assert(await p.locator('#pinsRetry').isHidden());await p.context().close();});
 await test('pause/resume downgrades and no hidden or paused inputs',async()=>{const p=await load(b);await start(p,true);await p.evaluate(()=>__qa.frames(15));await p.click('#pinsPause');const s=await p.evaluate(()=>CorePinsDiagnostics.snapshot());assert(s.paused&&!s.ranked);await p.evaluate(()=>{window.dispatchEvent(new KeyboardEvent('keydown',{code:'Space',bubbles:true}));__qa.frames(150);});assert.deepEqual(await p.evaluate(()=>CorePinsDiagnostics.snapshot().state),s.state);await p.click('#pinsResume');await end(p);assert.equal(await p.evaluate(()=>__calls.finish.length),0);await p.context().close();});
 await test('stalled frame downgrades',async()=>{const p=await load(b);await start(p,true);await p.evaluate(()=>__qa.frame(300));assert(!await p.evaluate(()=>CorePinsDiagnostics.snapshot().ranked));await end(p);assert.equal(await p.evaluate(()=>__calls.finish.length),0);await p.context().close();});
 await test('hidden tab downgrades and pauses',async()=>{const p=await load(b);await start(p,true);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{get:()=>true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});assert(await p.evaluate(()=>CorePinsDiagnostics.snapshot().paused&&!CorePinsDiagnostics.snapshot().ranked));await p.context().close();});
 await test('capture forbids backend, analytics and storage writes',async()=>{const p=await load(b,{capture:true});assert(await p.locator('#ranked').isDisabled());await start(p);await end(p);const x=await p.evaluate(()=>__calls);assert.equal(x.start.length+x.finish.length+x.events.length+x.storage.length,0);await p.context().close();});
 await test('offline config never blocks practice; guest label correct',async()=>{for(const opt of [{failConfig:true},{guest:true}]){const p=await load(b,{opt});if(opt.guest)assert.equal(await p.locator('#ranked').innerText(),'SIGN IN TO RANK');await start(p);assert(await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));await p.context().close();}});
 await test('late config cannot rewind a running game',async()=>{const p=await load(b,{opt:{delayConfig:true}});await start(p);await p.evaluate(()=>__qa.frames(45));const s=await p.evaluate(()=>__audit.state());await p.evaluate(()=>__releaseConfig());await p.waitForTimeout(30);assert.deepEqual(await p.evaluate(()=>__audit.state()),s);assert((await p.locator('#status').innerText()).includes('Practice run'));await p.context().close();});
 await test('late save never overwrites a new attempt',async()=>{const p=await load(b,{opt:{delayFinish:true}});await start(p,true);await end(p);assert((await p.locator('#saveState').innerText()).includes('Verifying'));await p.click('#again');await p.waitForTimeout(20);await p.evaluate(()=>__releaseFinish());await p.waitForTimeout(30);assert(await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));assert(await p.locator('#resultDialog').isHidden());await p.context().close();});
 await test('ranked replay failure returns choice; native Escape and close allow replay',async()=>{const p=await load(b);await start(p,true);await end(p);await p.evaluate(()=>__opt.failStart=true);await p.click('#again');await p.waitForTimeout(30);assert(await p.locator('#primary').isVisible());assert(!await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));await p.click('#primary');await end(p);await p.keyboard.press('Escape');await p.waitForTimeout(30);assert(await p.locator('#primary').isVisible());await p.context().close();});
 await test('board failure cannot downgrade confirmed save',async()=>{const p=await load(b,{opt:{badBoard:true}});await start(p,true);await end(p);assert((await p.locator('#saveState').innerText()).includes('Verified'));assert((await p.locator('#rankState').innerText()).includes('temporarily unavailable'));await p.context().close();});
 await test('real keyboard Space from focused canvas records a throw',async()=>{const p=await load(b);await start(p);await p.keyboard.press('Space');await p.evaluate(()=>__qa.frames(1));assert.equal(await p.evaluate(()=>__audit.state().thrown),1);assert.deepEqual(p.errors,[]);await p.context().close();});
 await test('duplicate clicks and hidden start never start a second run',async()=>{const p=await load(b,{opt:{delayStart:true}});await start(p,true);await p.locator('#ranked').evaluate(el=>el.click());assert.equal(await p.evaluate(()=>__calls.start.length),1);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{get:()=>true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});await p.evaluate(()=>__releaseStart());await p.waitForTimeout(20);assert(!await p.evaluate(()=>CorePinsDiagnostics.snapshot().playing));assert(await p.locator('#primary').isVisible());await p.context().close();});
 await test('emulated touch records a throw; effects obey resource budget',async()=>{const p=await load(b);await start(p);await p.locator('#phaser-game canvas').tap({position:{x:100,y:100}});await p.evaluate(()=>__qa.frames(1));assert.equal(await p.evaluate(()=>__audit.state().thrown),1);await cleanPlay(p,180);const r=await p.evaluate(()=>CorePinsDiagnostics.resources());assert(r.fx.particles<=64&&r.fx.floaters<=5&&r.audio.voices<=12);assert.deepEqual(p.errors,[]);await p.context().close();});
 await test('sound prefs/reduced motion and page disposal',async()=>{const p=await load(b);await start(p);await p.waitForTimeout(30);await p.click('#pinsPause');await p.click('#pinsSound');await p.click('#pinsSound');await p.waitForTimeout(50);assert(['suspended','uninitialized'].includes(await p.evaluate(()=>CorePinsDiagnostics.resources().audio.state)));await p.click('#pinsResume');await p.waitForTimeout(30);await p.click('#pinsMotion');assert.equal(await p.locator('#pinsMotion').getAttribute('aria-pressed'),'false');await p.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false})));await p.waitForTimeout(30);assert(await p.evaluate(()=>CorePinsDiagnostics.resources().audio.disposed));assert.deepEqual(p.errors,[]);await p.context().close();});
 // Legacy controllers are byte-identical and continue to run from the dispatcher.
 for(const game of ['gyro-drop','nova-merge'])await test('unchanged legacy '+game,async()=>{const p=await load(b,{game});await start(p);await p.evaluate(()=>__qa.frames(50));assert.equal(await p.evaluate(()=>typeof CorePinsDiagnostics),'undefined');assert.deepEqual(p.errors,[]);await p.context().close();});
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,report},null,2));console.log('TOTAL',checks);
}finally{if(b)await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
