'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const R=require('../experience/replay-kit.js'),root=path.resolve(__dirname,'..');
function storage(){const rows=new Map();return {getItem:k=>rows.has(k)?rows.get(k):null,setItem:(k,v)=>rows.set(k,String(v)),rows};}
test('four existing games only, deterministic next cycle',()=>{assert.equal(R.CATALOG.length,4);let game='gyro-drop';const seen=[];for(let i=0;i<4;i++){seen.push(game);game=R.next(game).id;}assert.equal(game,'gyro-drop');assert.equal(new Set(seen).size,4);assert.equal(R.next('invented'),null);});
for(const [score,best,label,detail] of [[10,20,'BEAT YOUR DEVICE BEST','11 more points'],[20,20,'DEVICE BEST MATCHED','1 more point'],[21,20,'NEW DEVICE BEST','+1 above'],[1,0,'FIRST DEVICE BEST','score to beat'],[0,0,'READY FOR ANOTHER TRY?','first points']])test('accurate comparison '+score+'/'+best,()=>{const c=R.comparison({score,previousBest:best});assert.equal(c.title,label);assert(c.detail.includes(detail));});
for(const n of [-1,NaN,Infinity,'300',1.5,Number.MAX_SAFE_INTEGER+1])test('invalid score rejected '+String(n),()=>assert.throws(()=>R.record({score:n,key:'test',store:storage()})));
test('current score, previous best and maximum remain distinct',()=>{const s=storage();s.setItem('test','50');const r=R.record({score:30,previousBest:20,key:'test',store:s});assert.equal(r.score,30);assert.equal(r.previousBest,50);assert.equal(r.best,50);assert(r.stored);assert.equal(s.getItem('test'),'50');});
test('capture never writes local records',()=>{const r=R.record({score:500,previousBest:2,key:'test',capture:true,store:{getItem:()=>assert.fail(),setItem:()=>assert.fail()}});assert(!r.stored&&r.capture);assert(R.practiceNote(r).includes('no record written'));});
test('blocked storage is never claimed saved',()=>{const r=R.record({score:10,key:'test',store:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}}});assert(!r.stored);assert(R.practiceNote(r).includes('unavailable'));});
for(const raw of ['-30','NaN','Infinity','bad','1.5',String(Number.MAX_SAFE_INTEGER+1)])test('corrupt stored best rejected '+raw,()=>assert.equal(R.loadBest('key',{getItem:()=>raw}),0));
test('device record explicitly not a ranked record',()=>assert(R.practiceNote({stored:true}).includes('Not a ranked score')));
function intent(options={}){const handlers={},added=[],a={href:'https://unit.test/games/core-pins?utm_source=threads',target:'',hasAttribute:()=>false,getAttribute:()=>null};const s={URL,location:{href:'https://unit.test/',origin:'https://unit.test'},navigator:{connection:options.connection},document:{addEventListener:(e,f)=>handlers[e]=f,createElement:()=>({}),head:{append:x=>added.push(x)}}};vm.runInNewContext(fs.readFileSync(path.join(root,'experience/entry-hints.js'),'utf8'),s);return {a,added,handlers,event:(extra={})=>({target:{closest:()=>a},button:0,...extra})};}
test('normal card click starts free intent and preserves tags',()=>{const t=intent();t.handlers.click(t.event());const u=new URL(t.a.href,'https://unit.test');assert.equal(u.searchParams.get('play'),'1');assert.equal(u.searchParams.get('utm_source'),'threads');});
for(const patch of [{ctrlKey:true},{metaKey:true},{shiftKey:true},{button:1},{defaultPrevented:true}])test('native modified clicks unchanged '+JSON.stringify(patch),()=>{const t=intent(),before=t.a.href;t.handlers.click(t.event(patch));assert.equal(t.a.href,before);});
test('disabled save-state next link never gets launch intent',()=>{const t=intent(),before=t.a.href;t.a.getAttribute=()=> 'true';t.handlers.click(t.event());assert.equal(t.a.href,before);});
test('preload only one common script, not game page or analytics',()=>{const t=intent();t.handlers.pointerover(t.event());t.handlers.focusin(t.event());assert.equal(t.added.length,1);assert.equal(t.added[0].href,'/vendor/phaser-3.90.0.min.js');assert.equal(t.added[0].as,'script');});
for(const connection of [{saveData:true},{effectiveType:'2g'},{effectiveType:'slow-2g'}])test('bandwidth preference respected '+JSON.stringify(connection),()=>{const t=intent({connection});t.handlers.pointerover(t.event());assert.equal(t.added.length,0);});
test('same-origin only',()=>{const t=intent();t.a.href='https://other.test/games/core-pins';t.handlers.click(t.event());assert(!t.a.href.includes('play='));t.handlers.pointerover(t.event());assert.equal(t.added.length,0);});
test('build wiring repeatable without duplicating kit and preserving canonical',()=>{const build=require('../scripts/build-retention.cjs').build;build();const files=['descent/index.html','challengers/play.html','games/core-pins/index.html','games/nova-merge/index.html','games/orbit-sprint/index.html'];const first=files.map(p=>fs.readFileSync(path.join(root,p),'utf8'));build();assert.deepEqual(files.map(p=>fs.readFileSync(path.join(root,p),'utf8')),first);for(const html of first){assert.equal((html.match(/src="\/experience\/replay-kit.js"/g)||[]).length,1);assert.equal((html.match(/src="\/experience\/entry-hints.js"/g)||[]).length,1);}});
function auto(search,hidden=false){const listeners={},replaced=[],micro=[];let started=0,ready=false;const context={URL,Set,Number,Object,queueMicrotask:f=>micro.push(f),location:{href:'https://unit.test/descent'+search},history:{state:null,replaceState:(state,title,url)=>{replaced.push(url);context.location.href='https://unit.test'+url;}},document:{hidden,addEventListener:(k,f)=>listeners[k]=f,removeEventListener:k=>delete listeners[k]}};vm.runInNewContext(fs.readFileSync(path.join(root,'experience/replay-kit.js'),'utf8'),context);const run=context.LoopJoltReplayKit.autoPractice({ready:()=>ready,start:()=>started++});return {run,micro,replaced,listeners,context,ready:()=>ready=true,count:()=>started};}
test('intent waits for readiness, consumes only once, preserves campaign',()=>{const a=auto('?play=1&utm_source=threads');a.micro[0]();assert.equal(a.count(),0);a.ready();a.run();a.run();assert.equal(a.count(),1);assert.equal(a.replaced[0],'/descent?utm_source=threads');});
test('hidden page cannot auto-start until visible',()=>{const a=auto('?play=1',true);a.ready();a.run();assert.equal(a.count(),0);a.context.document.hidden=false;a.listeners.visibilitychange();assert.equal(a.count(),1);});
for(const query of ['', '?utm_source=threads', '?capture=1&play=1','?qa=1&play=1'])test('no automatic launch '+query,()=>{const a=auto(query);a.ready();a.run();assert.equal(a.count(),0);});
