'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const S=require('../scripts/build-search-metadata.cjs');const root=path.resolve(__dirname,'..');
for(const file of Object.keys(S.PAGES)){
 const before=fs.readFileSync(path.join(root,file),'utf8');
 test(file+' unique descriptive metadata and clean canonical',()=>{const after=S.transform(before,file),p=S.PAGES[file];assert(after.includes('<title>'+p.title+'</title>'));assert.equal((after.match(/rel="canonical"/g)||[]).length,1);assert(after.includes('href="'+p.url+'"'));for(const k of ['description','og:title','og:description','og:url','og:type'])assert.equal((after.match(new RegExp('(?:name|property)="'+k+'"','g'))||[]).length,1);assert(!p.url.includes('utm_'));});
 test(file+' idempotent',()=>{const once=S.transform(before,file);assert.equal(S.transform(once,file),once);});
 test(file+' controls, scripts and route hrefs unchanged',()=>{const after=S.transform(before,file);for(const re of [/<script src="[^"]+"><\/script>/g,/<button\b[\s\S]*?<\/button>/g,/<a\b[^>]*href="([^"]*)"/g])assert.deepEqual(after.match(re),before.match(re));assert.deepEqual(after.match(/data-preview="[^"]+"/g),before.match(/data-preview="[^"]+"/g));});
}
test('home visible game name matches the Reel without changing game ID',()=>{const after=S.transform(fs.readFileSync(path.join(root,'index.html'),'utf8'),'index.html');assert(after.includes('<h2>Deep Descent</h2>'));assert(after.includes('data-preview="gyro-drop"'));assert(after.includes('Gyro Drop series'));assert(after.includes('No download. Try without an account.'));const schema=JSON.parse(after.match(/id="loopjolt-site-schema">(.*?)<\/script>/)[1]);assert.equal(schema['@type'],'WebSite');assert.equal(schema.name,'LoopJolt');assert(!JSON.stringify(schema).includes('aggregateRating'));});
test('sitemap includes Astra, all 4 ranked games and preserves all 3 legacy games',()=>{assert.equal(S.URLS.length,9);assert.equal(new Set(S.URLS).size,9);assert(S.URLS.includes('/games/astra-sentinel'));assert(S.URLS.includes('/descent'));assert(S.URLS.includes('/challengers/play?game=core-pins'));assert(S.URLS.includes('/challengers/play?game=nova-merge'));for(const slug of ['orbit-sprint','dont-press','perfect-timing','reaction-rush'])assert(S.URLS.includes('/games/'+slug));});
test('sitemap has no tracking, private/account pages or invented lastmod',()=>{const xml=S.sitemap();assert(!/utm_|fbclid|capture=|<lastmod>|community\/|api\//.test(xml));for(const u of S.URLS){assert.equal(new URL(u,S.ORIGIN).origin,S.ORIGIN);if(u!=='/')assert(!u.endsWith('/'));}assert.equal((xml.match(/<loc>/g)||[]).length,9);});
test('unknown or malformed HTML fails closed',()=>{assert.throws(()=>S.transform('<head></head>','unknown'));assert.throws(()=>S.transform('<head></head>','index.html'));});
