'use strict';
// Trusted visual-observation intake. No candidate source writes or oracle changes.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const {FileStore}=require('../../orchestrator/store.cjs'),{transition}=require('../../orchestrator/manifest.cjs');
const {readJSON,atomicJSON,hash,hashTree}=require('../../orchestrator/files.cjs'),{evaluate}=require('../../orchestrator/quality.cjs');
const id='GAME-20260923-141',root=path.resolve(process.env.FACTORY_WORKER_ROOT),tmp=path.resolve(process.env.RUNNER_TEMP),repo='andysong111/auto-lab';
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
if(process.env.GITHUB_RUN_ATTEMPT!=='1'||!root.startsWith(tmp+path.sep)||fs.existsSync(root))throw Error('isolated_once_only');
const api=p=>JSON.parse(execFileSync('gh',['api','--method','GET',`repos/${repo}/`+p],{encoding:'utf8',maxBuffer:4*1024*1024}));
const runs=api('actions/workflows/playjolt-keywake-final-repair.yml/runs?per_page=100').workflow_runs;
if(runs.some(r=>String(r.id)!==process.env.GITHUB_RUN_ID))throw Error('prior_final_execution_do_not_retry');
const zip=execFileSync('gh',['api','--method','GET',`repos/${repo}/actions/artifacts/10731172803/zip`],{maxBuffer:64*1024*1024});
if(digest(zip)!=='91bce4fb95cb3ccc49e2bd971ff70930708b2c259b53f70398f9cc5939ed7254')throw Error('checkpoint_mismatch');
const archive=path.join(tmp,'depth-v5.zip');fs.writeFileSync(archive,zip);
execFileSync('python',['-c','import zipfile,pathlib,sys; r=pathlib.Path(sys.argv[2]); z=zipfile.ZipFile(sys.argv[1]); assert all((r/n).resolve().is_relative_to(r.resolve()) for n in z.namelist()); z.extractall(r)',archive,root]);
const store=new FileStore(root),original=store.get(id),ledgerFile=path.join(root,'autonomy/.provider/ledger.json'),ledgerBytes=fs.readFileSync(ledgerFile),ledger=JSON.parse(ledgerBytes);
if(digest(ledgerBytes)!=='b444986da60c8dd2c3a27c7e38931297933761331b6c51d733bdf1d9ef30c9ed'||Object.keys(ledger.operations).length!==5||Object.values(ledger.operations).some(o=>o.state!=='COMPLETE')||original.repair_attempt!==4||original.version!=='v5'||original.state!=='RC_READY'||original.max_repair_attempts!==5)throw Error('lifetime_identity');
const sourceHash=hashTree(path.join(root,original.source_path));if(sourceHash!==original.source_hash)throw Error('source_mismatch');
const proof='v5/product/product-390-midgame.png',proofHash=digest(fs.readFileSync(store.artifact(id,proof)));
if(proofHash!=='f92d1d0f383b712b1af587d0c823603aff83472a5b3d4a4185cf3d8bf93babe3')throw Error('visual_proof_mismatch');
const failure={code:'product_key_counter_invalid_number',check:'visible_key_progress',selector:'[data-room-keys]',state_path:'state.stage / state.key_mask',expected:'A readable ROOM 2 · KEYS 0 / 2 label in the captured state; finite accurate collected/required counts in every room.',actual:'NaN / 2 rendered in v5. Work visually reviewed product-390-midgame.png. app.js update expression concatenates strings before subtracting 1.',message:'Fix the visible key counter arithmetic/formatting error, preserving the passing topology, scoring, core, seed mapping and art readability. This is the last lifetime repair (5/5). No rebuild or budget reset. Preserve v3 Preview base handling and all existing product contract requirements.',evidence:[proof]};
const qaFile=store.artifact(id,'v5/qa.json'),qa=readJSON(qaFile);if(!qa.passed)throw Error('v5_checkpoint_qa');
fs.copyFileSync(qaFile,store.artifact(id,'v5/qa-before-visual-review.json'));fs.copyFileSync(store.artifact(id,'v5/quality.json'),store.artifact(id,'v5/quality-before-visual-review.json'));
atomicJSON(path.join(root,'owner-depth','v5-visual-review.json'),{game_id:id,version:'v5',decision:'HOLD',failure,proof_sha256:proofHash,source_hash:sourceHash,ledger_sha256:digest(ledgerBytes),repair_before:4,remaining:1,original_started_at:ledger.jobs[id].started_at,additional_wall_pause:false});
atomicJSON(qaFile,{...qa,passed:false,hard_failures:[...qa.hard_failures,failure]});
let m=store.put(transition({...original,qa_status:'FAIL',quality_status:'PENDING',release_status:'NONE',failure_reasons:[failure]},'QA_RUNNING',{reason:'Visible NaN key counter found in QA screenshot; original automated reports preserved.'}));
m=store.put(transition(m,'QUALITY_GATE',{reason:'Trusted observed product failure intake.'}));
const result=evaluate(m,readJSON(qaFile));if(result.decision!=='REPAIR'||result.hard_failures.some(f=>f.code!==failure.code))throw Error('unexpected_quality_result');
atomicJSON(store.artifact(id,'v5/quality.json'),result);store.put(transition({...m,quality_status:'REPAIR',failure_reasons:result.hard_failures},'QUALITY_FAILED',{reason:'Last authorized same-ID repair; no further operations after repair/5.'}));
if(!fs.readFileSync(ledgerFile).equals(ledgerBytes)||hashTree(path.join(root,original.source_path))!==sourceHash)throw Error('source_or_ledger_changed');
console.log(JSON.stringify({state:'QUALITY_FAILED',version:'v5',repair_attempt:4,calls:5,next_operation:id+'/repair/5',source_unchanged:true,ledger_unchanged:true}));
