'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{validateProposal:validateRealProposal}=require('../spec-gate.cjs'),{buildPacket}=require('../release-packet.cjs');
const fixturePolicy={...require('../policy.json'),product_quality:{allow_fixture_oracles:true}};
const validateProposal=p=>validateRealProposal(p,{policy:fixturePolicy});
const proposal={product_contract:require('../../qa/fixtures/product/contract.json'),game_id:'GAME-20260922-120',generation:1,title:'Signal Loom',slug:'signal-loom',genre:'arcade puzzle',mechanic_family:'spatial-routing-chain',controls:['Arrows move cursor','Space commits link'],mobile_controls:['Drag to route','Tap to commit'],max_repair_attempts:5,qa:{seed:7,keyboard:{key:'ArrowRight',observation:'state.cursor.x'},pointer:{observation:'state.pointerMoves'},terminal_ms:45000},implementation_contract:{
goal:'Show the concrete objective prominently before play begins and keep it visible during the run.',
progression:'Expose visible goal progress and make later decisions require more meaningful actions across multiple seeds.',
presentation:'Use a readable mobile-first visual hierarchy with clear active state, feedback, and no overlapping labels.',
originality:'Use an original spatial-routing mechanic and original code-created presentation without copying existing games.',
difficulty:'Verify several deterministic seeds and ensure later stages require more meaningful decisions than early stages.',
mobile_readability:'Keep critical objective, score and controls legible at 390px without text collisions inside the canvas or DOM.',
result:'Show a clear complete or incomplete result, current score, device-local best and an obvious replay action.',
reduced_motion:'Respond to prefers-reduced-motion both at initial load and when the media preference changes during a session.',
scoring:'Reward objective progress and efficiency while preventing reversible no-progress action loops from increasing score.',
completion_timing:'End promptly when the objective is complete; achieve target session length through meaningful play, never forced waiting.',
action_feedback:'Make each meaningful state change visually legible with an appropriate transition or static reduced-motion alternative.'
}};
test('a distinct 45-second proposal keeps its public-quality brief in the factory spec',()=>{const r=validateProposal(proposal);assert.equal(r.passed,true);assert.equal(r.factory_spec.game_id,proposal.game_id);assert.deepEqual(r.factory_spec.implementation_contract,proposal.implementation_contract);assert.equal(r.commissioning.auto_production_ship,false);});
for(const family of ['arena-survival-autofire','tower-descent-rotation','radial-pin-timing','column-merge','auto-runner','single-button-reaction'])test('known mechanic family is blocked: '+family,()=>{const r=validateProposal({...proposal,mechanic_family:family,title:'Different '+family,slug:'different-'+family});assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='mechanic_family_blocked'));});
test('too many controls and long sessions fail before paid generation',()=>{const r=validateProposal({...proposal,controls:['1','2','3','4'],qa:{...proposal.qa,terminal_ms:90000}});assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='desktop_control_complexity'));assert(r.errors.some(e=>e.code==='terminal_window'));});
test('public title and slug collisions are blocked',()=>{const r=validateProposal({...proposal,title:'Astra Sentinel',slug:'astra-sentinel'});assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='title_collision'));assert(r.errors.some(e=>e.code==='slug_collision'));});
test('release packet fails closed before READY_TO_SHIP',()=>{const r=buildPacket({game_id:'GAME-20260922-110',version:'v1',title:'Signal Loom',slug:'signal-loom',state:'RC_READY',qa_status:'PASS',quality_status:'PASS',release_status:'RC',preview_url:null,metrics_eligibility:false,repair_attempt:0,failure_reasons:[]});assert.equal(r.passed,false);assert.equal(r.production.authorized,false);});
test('READY_TO_SHIP packet still does not authorize production without owner review adapter',()=>{const r=buildPacket({game_id:'GAME-20260922-110',version:'v3',title:'Signal Loom',slug:'signal-loom',state:'READY_TO_SHIP',product_contract:proposal.product_contract,commercial_contract:require('../../qa/commercial/fixtures/contract.json'),commercial_qa_status:'PASS',technical_qa_status:'PASS',product_qa_status:'PASS',qa_status:'PASS',quality_status:'PASS',release_status:'READY',preview_url:'https://preview.vercel.app',source_hash:'a'.repeat(64),rc_commit:'b'.repeat(40),branch:'factory/GAME-20260922-110',pr_number:99,pr_url:'https://github.com/andysong111/auto-lab/pull/99',metrics_eligibility:false,repair_attempt:2,failure_reasons:[]});assert.equal(r.passed,true);assert.equal(r.production.authorized,false);assert.equal(r.owner_review.decision,'PENDING');});

test('paid commissioning rejects a missing or vague public-quality implementation contract',()=>{const {implementation_contract,...missing}=proposal;let r=validateProposal(missing);assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='missing_field'));r=validateProposal({...proposal,implementation_contract:{goal:'too short'}});assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='invalid_implementation_contract'));});

test('previously rejected Prism mechanic family cannot consume the second commissioning slot',()=>{const r=validateProposal({...proposal,game_id:'GAME-20260922-121',title:'Not Prism',slug:'not-prism',mechanic_family:'spatial-optical-routing'});assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='rejected_mechanic_family'));});

test('production commissioning rejects test-only oracle approval',()=>{const r=validateRealProposal(proposal);assert.equal(r.passed,false);assert(r.errors.some(e=>e.code==='invalid_product_contract'));});
