'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {oracle,shift,solve}=require('../../qa/ribbon-shift.cjs');
const {repeatedPair,checkFeedback}=require('../third-real-game/feedback.cjs');
const {validateProposal}=require('../spec-gate.cjs');
const {settle}=require('../../qa/media-settlement.cjs');
test('media settlement waits for delayed native delivery and rejects a permanently stale presentation',async()=>{
 let wall=0,value=false;const r=await settle({read:async()=>value,advance:async()=>{},delay:async ms=>{wall+=ms;if(wall>=60)value=true;},now:()=>wall,matches:x=>x===true});assert.equal(r.initial,false);assert.equal(r.settled,true);assert.equal(r.polls,3);
 wall=0;await assert.rejects(()=>settle({read:async()=>false,advance:async()=>{},delay:async ms=>{wall+=ms;},now:()=>wall,matches:x=>x===true}),/did not settle/);assert.equal(wall,800);
});
test('third proposal is original family, concrete contract and passes before paid call',()=>{const p=require('../third-real-game/proposal.json'),g=validateProposal(p);assert(g.passed);assert.equal(p.game_id,'GAME-20260922-131');assert.equal(p.max_repair_attempts,5);assert(g.factory_spec.implementation_contract.reduced_motion.includes('change event'));});
test('independent bounded reverse oracle returns shortest normal forward shift solutions',()=>{const m=oracle(),counts={};for(const [key,solution]of m){let b=key.split(',').map(Number);const depth=solution.length;counts[depth]=(counts[depth]||0)+1;for(const op of solution)b=shift(b,op);assert.deepEqual(b,[0,1,2,3,4,5,6,7,8]);if(depth){assert(!oracle(depth-1).has(key));}}assert(counts[2]>0&&counts[3]>0&&counts[4]>0);assert.throws(()=>solve({board:[0,0,0]}));});
test('same validation twice pauses before third reservation and requires exact reviewed fingerprint',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'feedback-test-'));try{const operations={};for(let i=0;i<2;i++)operations[i]={game_id:'GAME-20260922-131',operation_id:'op'+i,request_hash:'hash'+i,started_at:i,state:'MODEL_FAILED',error_code:'core_dom_dependency',error_context:{file:'core.js',identifier:'window'},rejected_output:{files:[]}};const ledger={operations},pair=repeatedPair(ledger);assert(pair);fs.mkdirSync(path.join(root,'autonomy/.provider'),{recursive:true});const file=path.join(root,'autonomy/.provider/ledger.json');fs.writeFileSync(file,JSON.stringify(ledger));assert.throws(()=>checkFeedback(root),e=>e.code==='repeated_validation_requires_system_review');assert.equal(Object.keys(JSON.parse(fs.readFileSync(file)).operations).length,2);fs.writeFileSync(path.join(root,'feedback-review.json'),JSON.stringify({...pair,system_reviewed:true,findings:'Verified exact failing file and identifier, bounded quarantined sources, unchanged candidate workspace and compiled allowed repair context. No engine defect found.'}));checkFeedback(root);operations[1].request_hash='different';fs.writeFileSync(file,JSON.stringify(ledger));assert.throws(()=>checkFeedback(root));operations[1].error_code='model_missing_file';assert.equal(repeatedPair(ledger),null);}finally{fs.rmSync(root,{recursive:true,force:true});}});
