'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {create,transition}=require('../../orchestrator/manifest.cjs');
const {loadPolicy,decision,snapshot}=require('../control.cjs'),{readiness}=require('../metrics.cjs'),{html}=require('../render.cjs');
const policy=loadPolicy(),tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'pj-control-'));
function spec(id,title='<unsafe>'){return{game_id:id,title,slug:'fixture',genre:'test',mechanic_family:'fixture',controls:['move'],mobile_controls:['drag'],qa:{seed:7,keyboard:{key:'ArrowRight',observation:'state.x'},pointer:{observation:'state.taps'},terminal_ms:1000}};}
function to(m,state){return transition(m,state);}
function save(root,m){const d=path.join(root,'autonomy/jobs',m.game_id);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'manifest.json'),JSON.stringify(m));}
test('control policy fails closed for production shipping and intake',()=>{assert.equal(policy.auto_production_ship,false);assert.equal(policy.kill_switches.production_shipping,true);const s=snapshot({root:tmp(),policy,provider_ready:true});assert.equal(s.automation.can_create,false);assert.equal(s.automation.reason,'intake_disabled');});
test('READY_TO_SHIP never becomes a production-ship action',()=>{let m=create(spec('GAME-20260922-001'));for(const s of ['SPEC_READY','BUILDING','QA_RUNNING','QUALITY_GATE','RC_READY','PREVIEW_DEPLOYING','PREVIEW_SMOKE','READY_TO_SHIP'])m=to(m,s);assert.deepEqual(decision(m,policy),{action:'HOLD_RC',reason:'production_shipping_disabled'});});
test('critical failure becomes the only kind that requires owner action',()=>{const root=tmp();let m=create(spec('GAME-20260922-002'));m={...m,state:'REJECTED',revision:1,failure_reasons:[{code:'production_side_effect',message:'blocked'}]};save(root,m);const s=snapshot({root,policy});assert.equal(s.owner_action_required,true);assert.equal(s.incidents[0].severity,'critical');});
test('ordinary rejected candidate is informational and does not wake owner',()=>{const root=tmp();let m=create(spec('GAME-20260922-003'));m={...m,state:'REJECTED',revision:1};save(root,m);const s=snapshot({root,policy});assert.equal(s.owner_action_required,false);assert.equal(s.incidents[0].code,'candidate_rejected');});
test('phase 2 metrics remain disabled and cannot classify a winner',()=>{const r=readiness({observed_sessions:999,starting_sessions:900,replaying_sessions:800,game_finish_sessions:700,error_rate:0,age_hours:500},policy);assert.equal(r.state,'DISABLED');assert(!JSON.stringify(r).includes('WINNER'));});
test('dashboard escapes game text and is explicitly noindex',()=>{const root=tmp();save(root,create(spec('GAME-20260922-004')));const h=html(snapshot({root,policy}));assert(h.includes('noindex,nofollow'));assert(h.includes('&lt;unsafe&gt;'));assert(!h.includes('<unsafe>'));});
test('active limit and provider readiness can stop intake independently',()=>{const root=tmp(),p={...policy,intake_enabled:true};let m=create(spec('GAME-20260922-005'));m=to(m,'SPEC_READY');save(root,m);assert.equal(snapshot({root,policy:p,provider_ready:false}).automation.reason,'builder_provider_not_ready');const limited={...p,max_active_jobs:1};assert.equal(snapshot({root,policy:limited,provider_ready:true}).automation.reason,'active_job_limit');});
