/* LoopJolt Challengers: canonical deterministic rules for three Phaser-rendered games.
 * Browser and server replay the same 60 Hz state machine. Visuals never decide score. */
(function(root){'use strict';
const CONFIG=Object.freeze({
 'gyro-drop':{version:'gd-phaser-v1',ticks:4500,title:'Gyro Drop'},
 'core-pins':{version:'cp-phaser-v1',ticks:3600,title:'Core Pins'},
 'nova-merge':{version:'nm-phaser-v1',ticks:5400,title:'Nova Merge'}
});
const mod=(n,m)=>(n%m+m)%m,dist=(a,b,m=3600)=>Math.min(mod(a-b,m),mod(b-a,m)),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function rand(s){s.rng=(s.rng+0x6D2B79F5)>>>0;let t=s.rng;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}
function event(s,kind,data={}){s.events.push({kind,...data});}
function base(game,seed){if(!CONFIG[game])throw Error('invalid_game');if(!Number.isInteger(seed)||seed<0||seed>0xffffffff)throw Error('invalid_seed');return{game,version:CONFIG[game].version,seed,rng:seed>>>0,tick:0,score:0,combo:0,maxCombo:0,hits:0,misses:0,health:3,alive:true,won:false,events:[]};}
function makeGyro(seed){const s=base('gyro-drop',seed);Object.assign(s,{rotation:0,ring:0,nextBounce:72,smash:0,falls:0,rings:[]});for(let i=0;i<80;i++){const gap=Math.floor(rand(s)*3600),hazard=mod(gap+900+Math.floor(rand(s)*1800),3600),gapW=Math.max(260,520-i*4),hazW=Math.min(500,280+i*3);s.rings.push({gap,hazard,gapW,hazW});}return s;}
function gyroStep(s,a){if(a&&a[0]==='turn')s.rotation=mod(s.rotation+a[1],3600);if(s.tick<s.nextBounce)return;const r=s.rings[s.ring];if(!r){s.alive=false;s.won=true;s.score+=2000;event(s,'finish');return;}const at=mod(-s.rotation,3600),through=dist(at,r.gap)<=r.gapW/2,danger=dist(at,r.hazard)<=r.hazW/2,usingSmash=s.smash>0;if(through||usingSmash){s.ring++;s.falls++;s.hits++;let value;if(usingSmash){s.smash=0;s.combo=0;value=260;event(s,'smash',{ring:s.ring});}else{s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);value=120+Math.min(12,s.combo)*25;if(s.combo>=3){s.smash=1;s.combo=0;}}s.score+=value;event(s,'fall',{ring:s.ring,value,smash:usingSmash});s.nextBounce=s.tick+Math.max(26,46-Math.floor(s.ring/5));}
else{if(danger){s.health--;s.misses++;s.combo=0;s.smash=0;event(s,'hazard',{ring:s.ring});if(s.health<=0){s.alive=false;s.health=0;return;}}else{s.combo=0;event(s,'bounce',{ring:s.ring});}s.nextBounce=s.tick+Math.max(30,54-Math.floor(s.ring/6));}}
function makePins(seed){const s=base('core-pins',seed);Object.assign(s,{stage:1,rotation:0,speed:13,target:7,pins:[],hazards:[],thrown:0,stageHits:0,boss:false});pinsStage(s);return s;}
function pinsStage(s){s.target=Math.min(15,6+s.stage*2);s.stageHits=0;s.pins=[];s.hazards=[];s.boss=s.stage%4===0;const count=s.boss?4:Math.min(3,1+Math.floor(s.stage/2));for(let i=0;i<count;i++)s.hazards.push(Math.floor(rand(s)*3600));const mag=Math.min(34,12+s.stage*2);s.speed=(rand(s)<.5?-1:1)*mag;event(s,'stage',{stage:s.stage,boss:s.boss,target:s.target});}
function pinsStep(s,a){const wave=Math.floor(s.tick/420)%4;if(s.tick%420===0&&s.tick>0)s.speed=-s.speed+(s.speed>0?2:-2);s.rotation=mod(s.rotation+s.speed+(wave===3?Math.round(Math.sin(s.tick/18)*2):0),3600);if(!a||a[0]!=='throw')return;s.thrown++;const hit=mod(900-s.rotation,3600),blocked=s.pins.some(p=>dist(p,hit)<185)||s.hazards.some(p=>dist(p,hit)<160);if(blocked){s.health--;s.misses++;s.combo=0;event(s,'collision',{angle:hit});if(s.health<=0){s.health=0;s.alive=false;}return;}s.pins.push(hit);s.stageHits++;s.hits++;s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);const value=90+Math.min(15,s.combo)*18+(s.boss?40:0);s.score+=value;event(s,'pin',{angle:hit,value});if(s.stageHits>=s.target){s.score+=300+s.stage*80;s.stage++;if(s.stage>8){s.alive=false;s.won=true;s.score+=1500;event(s,'finish');}else pinsStage(s);}}
function makeMerge(seed){const s=base('nova-merge',seed);Object.assign(s,{cols:Array.from({length:7},()=>[]),next:0,drops:0,merges:0,cooldown:0,maxRows:8,largest:0});s.health=1;s.next=nextOrb(s);return s;}
function nextOrb(s){const r=rand(s);return r<.58?0:r<.88?1:2;}
function mergeColumn(s,col){let chain=0;while(true){const a=s.cols[col];if(a.length<2||a[a.length-1]!==a[a.length-2])break;const level=a.pop()+1;a[a.length-1]=level;chain++;s.merges++;s.hits++;s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);s.largest=Math.max(s.largest,level);const value=Math.min(1800,(level+1)*(level+1)*45+chain*40);s.score+=value;event(s,'merge',{col,level,value,chain});let n=-1;if(col>0&&s.cols[col-1].at(-1)===level)n=col-1;else if(col<6&&s.cols[col+1].at(-1)===level)n=col+1;if(n>=0){s.cols[n].pop();a[a.length-1]=level+1;chain++;s.merges++;s.combo++;s.maxCombo=Math.max(s.maxCombo,s.combo);s.largest=Math.max(s.largest,level+1);const bonus=Math.min(2200,(level+2)*(level+2)*55+chain*60);s.score+=bonus;event(s,'resonance',{from:n,col,level:level+1,value:bonus,chain});continue;}}
if(chain===0)s.combo=0;}
function mergeStep(s,a){if(s.cooldown>0)s.cooldown--;if(!a||a[0]!=='drop'||s.cooldown>0)return;const col=a[1];if(s.cols[col].length>=s.maxRows){s.alive=false;s.misses++;event(s,'overflow',{col});return;}const level=s.next;s.cols[col].push(level);s.drops++;s.cooldown=10;s.largest=Math.max(s.largest,level);event(s,'drop',{col,level,row:s.cols[col].length-1});mergeColumn(s,col);s.next=nextOrb(s);if(s.cols.every(c=>c.length>=s.maxRows)){s.alive=false;event(s,'overflow');}}
function create(game,seed){return game==='gyro-drop'?makeGyro(seed):game==='core-pins'?makePins(seed):makeMerge(seed);}
function step(s,a){if(!s.alive)return s;s.events=[];if(s.game==='gyro-drop')gyroStep(s,a);else if(s.game==='core-pins')pinsStep(s,a);else mergeStep(s,a);s.tick++;if(s.tick>=CONFIG[s.game].ticks&&s.alive){s.alive=false;s.won=true;s.score+=500+s.health*100;event(s,'finish');}s.score=clamp(Math.round(s.score),0,50000);return s;}
function valid(game,e,ticks,last){if(!Array.isArray(e)||!Number.isInteger(e[0])||e[0]<=last||e[0]<0||e[0]>=ticks)return false;if(game==='gyro-drop')return e.length===3&&e[1]==='turn'&&Number.isInteger(e[2])&&e[2]>=-180&&e[2]<=180&&e[2]!==0;if(game==='core-pins')return e.length===2&&e[1]==='throw';return e.length===3&&e[1]==='drop'&&Number.isInteger(e[2])&&e[2]>=0&&e[2]<=6;}
function replay(game,seed,actions,ticks){const cfg=CONFIG[game];if(!cfg)throw Error('invalid_game');if(!Number.isInteger(ticks)||ticks<1||ticks>cfg.ticks)throw Error('invalid_duration');if(!Array.isArray(actions)||actions.length>2000)throw Error('invalid_inputs');let last=-1;for(const e of actions){if(!valid(game,e,ticks,last))throw Error('invalid_input_order');last=e[0];}const s=create(game,seed);let i=0;while(s.tick<ticks&&s.alive){const e=actions[i];step(s,e&&e[0]===s.tick?e.slice(1):null);if(e&&e[0]===s.tick-1)i++;}if(s.alive||s.tick!==ticks||i!==actions.length)throw Error('incomplete_or_extra_inputs');return{score:s.score,ticks:s.tick,orbs:Math.min(150,s.hits||s.merges||0),maxCombo:Math.min(150,s.maxCombo),won:s.won,version:cfg.version};}
const api={CONFIG,create,step,replay,mod,dist};root.ChallengerRules=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
