(function(){'use strict';
const R=ChallengerRules,C=window.LoopCommunity,$=q=>document.querySelector(q),params=new URLSearchParams(location.search);
const game=R.CONFIG[params.get('game')]?params.get('game'):'gyro-drop',cfg=R.CONFIG[game],capture=params.get('capture')==='1';
const COPY={
 'gyro-drop':{title:'Gyro Drop',tag:'Turn the tower. Chain the fall.',health:'SHIELDS',how:'Drag left or right to rotate the tower. Drop through the glowing gaps. Red sectors cost a shield. Chain three clean drops to enter smash mode.'},
 'core-pins':{title:'Core Pins',tag:'One tap. One clean angle.',health:'SHIELDS',how:'Tap or press Space to fire a pin into the rotating core. Never hit a pin or red seal already on the core. Clear each ring and survive the boss stages.'},
 'nova-merge':{title:'Nova Merge',tag:'Drop small. Build a galaxy.',health:'BOARD',how:'Tap a column or use 1–7 to drop the next orb. Two matching orbs in a column merge. Matching neighbour tops can trigger a resonance chain. Keep the board below the limit.'}
}[game];
document.title=COPY.title+' — LoopJolt';$('#title').textContent=COPY.title;$('#tagline').textContent=COPY.tag;$('#healthLabel').textContent=COPY.health;$('#instructions').textContent=COPY.how;
$('#rankings').href=$('#resultRankings').href='/community/?game='+encodeURIComponent(game)+'&scope=world';
let seed=125904,state=R.create(game,seed),active=false,ranked=false,run=null,inputs=[],pending=null,acc=0,last=performance.now(),busy=false,attempt=0,best=0,profile=null,ready=false,savePayload=null,saveAttempt=0;
try{best=Number(localStorage.getItem('lj_ch_'+cfg.version)||0)||0;}catch{}$('#best').textContent=best.toLocaleString();
function status(t){$('#status').textContent=t;}function hud(){$('#score').textContent=state.score.toLocaleString();$('#time').textContent=Math.max(0,(cfg.ticks-state.tick)/60).toFixed(1);$('#combo').textContent=state.combo;$('#health').textContent=game==='nova-merge'?Math.max(...state.cols.map(c=>c.length))+'/'+state.maxRows:state.health;}
function record(a){if(!active||busy||!state.alive)return;if(pending){if(game==='gyro-drop'&&a[0]==='turn'&&pending[0]==='turn'){pending[1]=Math.max(-180,Math.min(180,pending[1]+a[1]));return;}return;}pending=a;}
function track(e,p={}){window.LJTelemetry?.track(e,game,cfg.version,p);}
function tone(kind){try{const ac=tone.ac||(tone.ac=new (AudioContext||webkitAudioContext)()),o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime;o.type=kind==='bad'?'sawtooth':'triangle';o.frequency.setValueAtTime(kind==='bad'?120:kind==='merge'?520:760,t);o.frequency.exponentialRampToValueAtTime(kind==='bad'?55:1200,t+.12);g.gain.setValueAtTime(.022,t);g.gain.exponentialRampToValueAtTime(.0001,t+.14);o.connect(g);g.connect(ac.destination);o.start();o.stop(t+.15);}catch{}}
class GameScene extends Phaser.Scene{
 constructor(){super('play');this.g=null;this.dragX=null;this.selected=3;}
 create(){this.cameras.main.setBackgroundColor('#08100f');this.g=this.add.graphics();this.fx=this.add.graphics();this.label=this.add.text(360,70,COPY.title.toUpperCase(),{fontFamily:'system-ui',fontSize:'18px',fontStyle:'bold',color:'#d5ff68'}).setOrigin(.5);this.sub=this.add.text(360,97,'LOOPJOLT CHALLENGER',{fontFamily:'system-ui',fontSize:'10px',color:'#8c9a95',letterSpacing:2}).setOrigin(.5);
 this.input.on('pointerdown',p=>{if(!active)return;if(game==='gyro-drop')this.dragX=p.x;else if(game==='core-pins')record(['throw']);else{const col=Math.max(0,Math.min(6,Math.floor(p.x/720*7)));this.selected=col;record(['drop',col]);}});
 this.input.on('pointermove',p=>{if(game!=='gyro-drop'||this.dragX==null||!active)return;const dx=p.x-this.dragX;if(Math.abs(dx)>2){record(['turn',Math.max(-180,Math.min(180,Math.round(dx*5)))]);this.dragX=p.x;}});
 this.input.on('pointerup',()=>this.dragX=null);this.input.on('pointerout',()=>this.dragX=null);
 this.input.keyboard.on('keydown-SPACE',()=>{if(game==='core-pins')record(['throw']);else if(game==='nova-merge')record(['drop',this.selected]);});
 this.input.keyboard.on('keydown-LEFT',()=>{if(game==='gyro-drop')record(['turn',-100]);else if(game==='nova-merge')this.selected=Math.max(0,this.selected-1);});
 this.input.keyboard.on('keydown-RIGHT',()=>{if(game==='gyro-drop')record(['turn',100]);else if(game==='nova-merge')this.selected=Math.min(6,this.selected+1);});
 for(let i=1;i<=7;i++)this.input.keyboard.on('keydown-'+i,()=>{if(game==='nova-merge'){this.selected=i-1;record(['drop',i-1]);}});
 }
 burst(x,y,color=0xd5ff68,n=10){for(let i=0;i<n;i++){const p=this.add.circle(x,y,2+Math.random()*3,color,.9),a=Math.random()*Math.PI*2,d=25+Math.random()*65;this.tweens.add({targets:p,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,alpha:0,scale:.2,duration:350+Math.random()*250,onComplete:()=>p.destroy()});}}
 float(text,x,y,color='#d5ff68'){const t=this.add.text(x,y,text,{fontFamily:'system-ui',fontSize:'18px',fontStyle:'bold',color}).setOrigin(.5);this.tweens.add({targets:t,y:y-50,alpha:0,duration:650,onComplete:()=>t.destroy()});}
 process(events){for(const e of events){if(['fall','pin','merge','resonance','finish'].includes(e.kind)){tone(e.kind==='merge'||e.kind==='resonance'?'merge':'ok');this.burst(game==='nova-merge'?105+(e.col||3)*85:360,game==='core-pins'?380:360,e.kind==='resonance'?0xffd166:0xd5ff68,e.kind==='finish'?24:10);if(e.value)this.float('+'+e.value,360,220);}if(['hazard','collision','overflow'].includes(e.kind)){tone('bad');this.cameras.main.shake(140,.008);this.burst(360,380,0xff657e,16);}}}
 arcEllipse(cx,cy,rx,ry,a0,a1,color,w){const g=this.g;g.lineStyle(w,color,1);g.beginPath();const n=28;for(let i=0;i<=n;i++){const a=a0+(a1-a0)*i/n,x=cx+Math.cos(a)*rx,y=cy+Math.sin(a)*ry;i?g.lineTo(x,y):g.moveTo(x,y);}g.strokePath();}
 gyro(){const g=this.g;g.clear();g.fillStyle(0x08100f,1);g.fillRect(0,0,720,900);for(let i=0;i<45;i++){g.fillStyle(0x92fff0,(i%7)/30+.05);g.fillCircle((i*149)%720,130+(i*71)%540,1+(i%3===0));}g.lineStyle(2,0x263b38,.8);g.lineBetween(360,140,360,790);
 for(let j=0;j<7;j++){const idx=state.ring+j;if(!state.rings[idx])continue;const r=state.rings[idx],cy=370+j*72,rx=250-j*10,ry=52-j*2,rot=state.rotation/1800*Math.PI,gap=r.gap/1800*Math.PI+rot,haz=r.hazard/1800*Math.PI+rot,gapW=r.gapW/1800*Math.PI,hazW=r.hazW/1800*Math.PI;for(let s=0;s<40;s++){const a=s/40*Math.PI*2,b=(s+1)/40*Math.PI*2,mid=(a+b)/2,isGap=Math.abs(Math.atan2(Math.sin(mid-gap),Math.cos(mid-gap)))<gapW/2,isHaz=Math.abs(Math.atan2(Math.sin(mid-haz),Math.cos(mid-haz)))<hazW/2;if(isGap)continue;this.arcEllipse(360,cy,rx,ry,a,b,isHaz?0xff536d:0x4d6f68,12);}}
 const phase=Math.max(0,Math.min(1,(state.nextBounce-state.tick)/55)),ballY=322-Math.sin((1-phase)*Math.PI)*75;g.fillStyle(state.smash?0xffd166:0xd5ff68,.18);g.fillCircle(360,ballY,38);g.fillStyle(state.smash?0xffd166:0xe9fff8,1);g.fillCircle(360,ballY,15);g.lineStyle(3,state.smash?0xffd166:0x66edd5,1);g.strokeCircle(360,ballY,21);this.sub.setText('RING '+(state.ring+1)+' · '+(state.smash?'SMASH READY':'CHAIN '+state.combo));}
 pins(){const g=this.g;g.clear();g.fillStyle(state.boss?0x160b17:0x07100f,1);g.fillRect(0,0,720,900);for(let i=0;i<30;i++){g.fillStyle(state.boss?0xff477e:0x66edd5,.05+(i%5)*.02);g.fillCircle((i*211)%720,160+(i*97)%600,1+(i%3));}const cx=360,cy=390,rot=state.rotation/1800*Math.PI;g.fillStyle(0x66edd5,.08);g.fillCircle(cx,cy,150);g.lineStyle(4,state.boss?0xff657e:0x66edd5,.8);g.strokeCircle(cx,cy,120);g.lineStyle(1,0xd5ff68,.25);g.strokeCircle(cx,cy,92);for(const h of state.hazards){const a=h/1800*Math.PI+rot,x=cx+Math.cos(a)*118,y=cy+Math.sin(a)*118;g.fillStyle(0xff657e,1);g.fillCircle(x,y,10);}for(const p of state.pins){const a=p/1800*Math.PI+rot,x1=cx+Math.cos(a)*115,y1=cy+Math.sin(a)*115,x2=cx+Math.cos(a)*185,y2=cy+Math.sin(a)*185;g.lineStyle(5,0xf5f1e8,1);g.lineBetween(x1,y1,x2,y2);g.fillStyle(0xd5ff68,1);g.fillCircle(x2,y2,5);}g.fillStyle(state.boss?0xff657e:0xd5ff68,1);g.fillCircle(cx,cy,48);g.fillStyle(0x0b1111,1);g.fillCircle(cx,cy,20);g.fillStyle(0xf4f1e8,1);g.fillTriangle(347,760,373,760,360,710);g.lineStyle(2,0xd5ff68,.5);g.lineBetween(360,700,360,520);this.sub.setText((state.boss?'BOSS ':'STAGE ')+state.stage+' · '+state.stageHits+'/'+state.target+' PINS');}
 merge(){const g=this.g;g.clear();g.fillStyle(0x070c12,1);g.fillRect(0,0,720,900);for(let i=0;i<40;i++){g.fillStyle([0x5fe1d3,0x7aa2ff,0xbd7aff][i%3],.08);g.fillCircle((i*173)%720,110+(i*59)%650,1+(i%2));}const x0=60,w=600,colW=w/7,bottom=790,rowH=72;for(let c=0;c<7;c++){g.fillStyle(c===this.selected?0xd5ff68:0x273330,c===this.selected?.08:.16);g.fillRoundedRect(x0+c*colW+4,170,colW-8,640,12);g.lineStyle(1,c===this.selected?0xd5ff68:0x31413d,c===this.selected?.7:.45);g.strokeRoundedRect(x0+c*colW+4,170,colW-8,640,12);const arr=state.cols[c];for(let r=0;r<arr.length;r++){const level=arr[r],x=x0+c*colW+colW/2,y=bottom-r*rowH-35,rad=Math.min(31,19+level*2),colors=[0x6cf1d7,0x7aa2ff,0xc47cff,0xff6f91,0xffc75f,0xf6ff7a,0xffffff];g.fillStyle(colors[level%colors.length],.13);g.fillCircle(x,y,rad+10);g.fillStyle(colors[level%colors.length],1);g.fillCircle(x,y,rad);g.fillStyle(0x08100f,.8);g.fillCircle(x-rad*.25,y-rad*.22,rad*.18);}}}const colors=[0x6cf1d7,0x7aa2ff,0xc47cff,0xff6f91,0xffc75f];g.fillStyle(colors[state.next%colors.length],1);g.fillCircle(360,120,24);this.sub.setText('NEXT ORB · LEVEL '+(state.next+1)+' · LARGEST '+(state.largest+1));}
 update(){if(game==='gyro-drop')this.gyro();else if(game==='core-pins')this.pins();else this.merge();}
}
const phaser=new Phaser.Game({type:Phaser.AUTO,parent:'phaser-game',width:720,height:900,transparent:false,backgroundColor:'#08100f',scene:GameScene,render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
function scene(){return phaser.scene.getScene('play');}
async function account(){try{const c=await C.config();seed=c.seed||seed;ready=!!c.rankedGames?.some(g=>g.game===game&&g.version===cfg.version);if(C.authenticated){profile=await C.me();if(profile)C.renderFlagLabel($('#identity'),profile.country,profile.handle);}status(capture?'Capture mode · practice only':ready?'Practice is instant. Ranked runs require sign-in.':'Practice ready. Ranked board activates after verification.');}catch{status('Practice ready. Ranking service is unavailable.');}state=R.create(game,seed);hud();updateButtons();}
function updateButtons(){$('#ranked').disabled=capture||!ready;$('#ranked').textContent=profile?'PLAY RANKED':'SIGN IN TO RANK';}
async function launch(wantRanked){if(busy)return;if(wantRanked&&!profile){const ret='/challengers/play?game='+encodeURIComponent(game);location.href='/community/?panel=profile&returnTo='+encodeURIComponent(ret);return;}busy=true;const id=++attempt;run=null;ranked=false;status('Preparing…');try{if(wantRanked&&!capture&&ready){run=await C.api('start',{game});if(run.version!==cfg.version)throw Error('version_mismatch');ranked=true;}}catch{run=null;ranked=false;status('Ranked start failed. Nothing was submitted.');busy=false;return;}if(id!==attempt)return;state=R.create(game,run?Number(run.seed):seed);inputs=[];pending=null;active=true;busy=false;savePayload=null;saveAttempt=0;acc=0;last=performance.now();status(ranked?'Ranked run · server will replay your inputs.':'Practice run · score stays on this device.');track('game_start',{ranked});hud();}
$('#primary').onclick=()=>launch(false);$('#ranked').onclick=()=>launch(true);
async function rankSummary(){if(!profile)return'';try{const u=new URL(C.endpoint);u.search=new URLSearchParams({action:'board',game,scope:'world',period:'week'});const d=await fetch(u,{cache:'no-store'}).then(r=>r.json()),row=d.rows?.find(r=>r.handle?.toLowerCase()===profile.handle.toLowerCase());const u2=new URL(C.endpoint);u2.search=new URLSearchParams({action:'board',game,scope:'nations',period:'week'});const n=await fetch(u2,{cache:'no-store'}).then(r=>r.json()),country=n.rows?.find(r=>r.country_code===profile.country);return[row?'World #'+row.rank:null,country?C.countryName(profile.country)+' #'+country.rank:null].filter(Boolean).join(' · ');}catch{return'';}}
async function saveRanked(payload,id){$('#saveState').className='save-state';$('#saveState').textContent='Verifying this run…';try{const response=await C.api('finish',payload);if(id!==saveAttempt)return;if(response.saved){$('#saveState').className='save-state ok';$('#saveState').textContent='Verified · '+Number(response.score).toLocaleString()+' saved.';const summary=await rankSummary();if(id===saveAttempt)$('#rankState').textContent=summary||'Official leaderboard updated.';}else throw Error('not_saved');}catch{if(id!==saveAttempt)return;$('#saveState').className='save-state bad';$('#saveState').textContent='Save not confirmed. Your local best is safe.';}}
async function finish(){if(!active)return;active=false;best=Math.max(best,state.score);try{localStorage.setItem('lj_ch_'+cfg.version,String(best));}catch{}$('#best').textContent=best.toLocaleString();track('game_finish',{ranked,score:state.score,ticks:state.tick});$('#resultScore').textContent=state.score.toLocaleString()+' pts';$('#resultMeta').textContent=game==='gyro-drop'?state.falls+' rings · '+state.maxCombo+' best chain':game==='core-pins'?'Stage '+state.stage+' · '+state.hits+' clean pins':state.merges+' merges · level '+(state.largest+1)+' largest';$('#rankState').textContent='';$('#saveState').className='save-state';if(ranked&&run){savePayload={runId:run.runId,actions:inputs,ticks:state.tick};const id=++saveAttempt;saveRanked(savePayload,id);}else $('#saveState').textContent='Practice best saved on this device.';run=null;ranked=false;$('#resultDialog').showModal();}
$('#again').onclick=()=>{$('#resultDialog').close();launch(false);};$('#closeResult').onclick=()=>$('#resultDialog').close();
let loopLast=performance.now();function loop(now){const dt=Math.min(100,now-loopLast);loopLast=now;if(active&&state.alive){acc+=dt/1000;let n=0;while(acc>=1/60&&state.alive&&n++<6){const a=pending;pending=null;if(a)inputs.push([state.tick,...a]);R.step(state,a);if(state.events.length)scene()?.process(state.events);acc-=1/60;}hud();if(!state.alive)finish();}requestAnimationFrame(loop);}requestAnimationFrame(loop);
track('page_view');track('game_open');account();
})();