/* Local, guest-first expedition controller. No account, network or ranked-score writes. */
(function(){'use strict';
const R=AstraRules,$=id=>document.getElementById(id),canvas=$('game'),view=AstraArt.make(canvas),capture=new URLSearchParams(location.search).get('capture')==='1',KEY='loopjolt_astra_v1';
let state=R.create(74021),paused=false,last=0,acc=0,phase='ready',run=0,soundOn=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,disposed=false,saved=true,record={best:0,cleared:0,wins:0},seenVictory=false;
let keys=new Set(),joy=null,pointer=null,dashRequested=false,frameId=0,lastHud=-1,lastPortrait=-1,tipUntil=0;
const movement=()=>{let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),y=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);if(joy){x=joy.dx;y=joy.dy;}return{x,y,dash:dashRequested};};
function read(){try{const raw=localStorage.getItem(KEY);if(!raw||raw.length>2048)return;const r=JSON.parse(raw);for(const [k,max] of [['best',10000000],['cleared',9],['wins',100000]])if(Number.isSafeInteger(r[k])&&r[k]>=0&&r[k]<=max)record[k]=Math.max(record[k],r[k]);soundOn=r.sound===true;reduced=reduced||r.reduced===true;}catch{saved=false;}}
function write(victory=false){if(capture){saved=false;return;}try{const old=JSON.parse(localStorage.getItem(KEY)||'{}');if(Number.isSafeInteger(old.best)&&old.best>=0&&old.best<10000000)record.best=Math.max(record.best,old.best);if(Number.isSafeInteger(old.cleared)&&old.cleared>=0&&old.cleared<=9)record.cleared=Math.max(record.cleared,old.cleared);record.best=Math.max(record.best,state.score);record.cleared=Math.max(record.cleared,state.cleared);if(victory&&!seenVictory){record.wins++;seenVictory=true;}localStorage.setItem(KEY,JSON.stringify({...record,sound:soundOn,reduced}));saved=true;}catch{saved=false;}}
read();
// Original synthesized effects. No soundtrack downloads, autoplay music or accumulating voices.
const audio={ctx:null,voices:new Set(),lastShot:0,init(){try{this.ctx??=new (window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}catch{}},tone(freq,dur,volume=.025,type='sine',end=freq){if(!soundOn||paused||disposed)return;this.init();if(!this.ctx||this.voices.size>=10)return;try{const ctx=this.ctx,o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(25,end),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(ctx.destination);this.voices.add(o);o.onended=()=>{this.voices.delete(o);o.disconnect();g.disconnect();};o.start(t);o.stop(t+dur+.01);}catch{}},event(e){if(e.kind==='shot'){if(state.tick-this.lastShot<10)return;this.lastShot=state.tick;this.tone(520,.065,.013,'triangle',210);}else if(e.kind==='kill')this.tone(e.boss?110:330,e.boss?.35:.1,.023,'triangle',70);else if(e.kind==='dash')this.tone(140,.19,.025,'sawtooth',850);else if(e.kind==='hurt')this.tone(100,.21,.03,'triangle',35);else if(e.kind==='heal')this.tone(900,.13,.023,'sine',1300);else if(e.kind==='arc')this.tone(400,.1,.018,'triangle',1500);else if(['clear','evolve','victory'].includes(e.kind)){this.tone(440,.3,.025,'triangle',880);this.tone(660,.4,.016,'sine',1320);}else if(e.kind==='telegraph')this.tone(120,.27,.025,'sine',240);},stop(){for(const o of this.voices)try{o.stop();}catch{}this.voices.clear();},close(){this.stop();this.ctx?.close().catch(()=>{});this.ctx=null;}};
function resetInput(){keys.clear();joy=null;pointer=null;dashRequested=false;}
function setSound(){ $('sound').textContent=soundOn?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(soundOn));$('motion').textContent=reduced?'Motion off':'Motion on';$('motion').setAttribute('aria-pressed',String(reduced));}
$('sound').onclick=()=>{soundOn=!soundOn;if(soundOn){audio.init();audio.tone(660,.15);}else audio.stop();setSound();write();};
$('motion').onclick=()=>{reduced=!reduced;setSound();write();};
function track(event,props={}){try{if(!capture&&window.LoopAcquisition?.GAMES.has('astra-sentinel'))window.LJTelemetry?.track(event,'astra-sentinel',R.VERSION,{ranked:false,...props});}catch{}}
function start(){if(state.phase==='playing'||state.phase==='upgrade')return;resetInput();paused=false;acc=0;last=performance.now();phase='ready';seenVictory=false;run++;state=R.create(capture?74021:crypto.getRandomValues(new Uint32Array(1))[0]);view.reset();R.begin(state);audio.lastShot=0;$('intro').hidden=true;for(const id of ['resultDialog','pauseDialog'])if($(id).open)$(id).close();$('pause').disabled=false;canvas.focus({preventScroll:true});tipUntil=state.tick+480;track('game_start');if(run>1)track('replay');if(soundOn)audio.init();sync(true);}
$('play').onclick=start;$('again').onclick=start;
function togglePause(){if(state.phase!=='playing')return;paused=!paused;resetInput();acc=0;last=performance.now();audio.stop();if(paused){$('pauseDialog').showModal();$('resume').focus({preventScroll:true});}else{$('pauseDialog').close();canvas.focus({preventScroll:true});}sync(true);}
$('pause').onclick=togglePause;$('resume').onclick=()=>{if(paused)togglePause();};$('pauseDialog').addEventListener('cancel',e=>{e.preventDefault();if(paused)togglePause();});
$('dash').onclick=()=>{if(!paused&&state.phase==='playing'){dashRequested=true;canvas.focus({preventScroll:true});}};
const moveCodes=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight']);
window.addEventListener('keydown',e=>{if(state.phase==='upgrade'){const n=['Digit1','Digit2','Digit3'].indexOf(e.code);if(n>=0&&!e.repeat){e.preventDefault();select(state.offers[n]);}return;}if(['KeyP','Escape'].includes(e.code)&&state.phase==='playing'&&!e.repeat){e.preventDefault();togglePause();return;}if(state.phase!=='playing'||paused||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(moveCodes.has(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='Space'&&!e.repeat&&!/BUTTON|A/.test(e.target.tagName)){e.preventDefault();dashRequested=true;}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',resetInput);
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state.phase==='playing'&&!paused)togglePause();audio.stop();resetInput();}last=performance.now();acc=0;});
function coords(e){const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)/b.width*R.W,y:(e.clientY-b.top)/b.height*R.H};}
canvas.addEventListener('pointerdown',e=>{if(state.phase!=='playing'||paused||pointer!==null||e.button!==0)return;e.preventDefault();canvas.focus({preventScroll:true});pointer=e.pointerId;const p=coords(e);joy={x:p.x,y:p.y,dx:0,dy:0};canvas.setPointerCapture?.(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer||!joy)return;const p=coords(e),x=p.x-joy.x,y=p.y-joy.y,n=Math.max(48,Math.hypot(x,y));joy.dx=x/n;joy.dy=y/n;});
const release=e=>{if(e.pointerId!==pointer)return;pointer=null;joy=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);
const symbols={power:'✦',twin:'Ⅱ',rapid:'»',orbit:'◉',arc:'ϟ',armor:'◇',flux:'➤',pierce:'⌁',repair:'✚'};
function showUpgrade(){resetInput();write();audio.stop();audio.event({kind:'clear'});$('clearLabel').textContent='GATE '+String(state.cleared).padStart(2,'0')+' RECLAIMED';$('nextTier').textContent='MK.'+String(state.tier).padStart(2,'0');$('newForm').textContent=R.FORMS[state.tier];$('growthText').textContent='+6 max hull · up to 24 hull restored · stronger bolts'+(state.tier%3===0?' · companion drone unlocked.':'.');$('nextRegion').textContent='Choose one module. Gate '+(state.stage+1)+' awaits.';const list=$('choices');list.replaceChildren();for(const id of state.offers){const u=R.UPGRADES.find(x=>x.id===id),b=document.createElement('button');b.type='button';b.className='choice';b.dataset.upgrade=id;for(const [tag,cls,text] of [['span','symbol',symbols[id]],['small','',u.tag+' / LV.'+(state.upgrades[id]+1)],['strong','',u.name],['p','',u.text],['span','choose','INSTALL →']]){const n=document.createElement(tag);if(cls)n.className=cls;n.textContent=text;b.append(n);}b.onclick=()=>select(id);list.append(b);}view.portrait($('upgradePortrait'),state.tier,0);$('upgradeDialog').showModal();list.firstElementChild?.focus({preventScroll:true});}
$('upgradeDialog').addEventListener('cancel',e=>e.preventDefault());
function select(id){if(!R.choose(state,id))return;$('upgradeDialog').close();resetInput();acc=0;last=performance.now();view.effects(state.events);state.events.forEach(e=>audio.event(e));phase='playing';canvas.focus({preventScroll:true});sync(true);}
function result(){resetInput();write(state.phase==='victory');track('game_finish');$('resultTag').textContent=state.phase==='victory'?'ALL NINE GATES RECLAIMED':'EXPEDITION ENDED';$('resultTitle').textContent=state.phase==='victory'?'You are the Sentinel.':'Rise again.';$('resultScore').textContent=state.score.toLocaleString('en-US');$('resultCleared').textContent=state.cleared+' / 9';$('resultKills').textContent=String(state.kills);view.portrait($('resultPortrait'),state.tier,0);$('resultNote').textContent=capture?'Capture practice. No device record written.':saved?'Device best '+record.best.toLocaleString('en-US')+'. '+(state.score<record.best?(record.best-state.score+1).toLocaleString('en-US')+' more points to beat it. ':'')+'Local record only; upgrades reset next expedition.':'Browser storage unavailable. This result was not saved.';$('pause').disabled=true;$('dash').disabled=true;$('resultDialog').showModal();$('again').focus({preventScroll:true});}
$('resultDialog').addEventListener('cancel',e=>e.preventDefault());
$('share').onclick=async()=>{const url='https://vibe-arcade-dun.vercel.app/games/astra-sentinel';try{await navigator.clipboard.writeText('I reclaimed '+state.cleared+'/9 gates in Astra Sentinel. Can you reach the final form? '+url);$('share').textContent='Copied ✓';}catch{$('share').textContent='Copy this page address to share';}};
function sync(force=false){if(!force&&state.tick-lastHud<6)return;lastHud=state.tick;const p=state.player,st=R.stats(state),theme=AstraArt.THEMES[Math.min(2,Math.floor((state.stage-1)/3))];document.documentElement.style.setProperty('--accent',theme.light);$('gate').replaceChildren(document.createTextNode(String(state.stage).padStart(2,'0')+' '));const em=document.createElement('em');em.textContent='/ 09';$('gate').append(em);$('hullValue').textContent=Math.ceil(p.hp)+' / '+p.maxHp;$('hullBar').style.width=p.hp/p.maxHp*100+'%';$('hullBar').parentElement.setAttribute('aria-valuenow',String(p.hp));$('hullBar').parentElement.setAttribute('aria-valuemax',String(p.maxHp));$('score').textContent=state.score.toLocaleString('en-US');$('region').textContent=theme.name;$('tier').textContent='MK.'+String(state.tier).padStart(2,'0');$('form').textContent=R.FORMS[state.tier];$('formCaption').textContent=state.tier===0?'An untested frame. A limitless ascent.':state.tier<3?'Reforged in battle. Every gate makes you stronger.':state.tier<6?'Your wings awaken. The foundry calls.':'A living constellation. Reclaim the citadel.';$('damage').textContent=st.damage.toFixed(0);$('volley').textContent=st.bolts+(st.bolts===1?' bolt':' bolts');$('drones').textContent=String(st.drones);$('best').textContent=record.best.toLocaleString('en-US');$('bestGate').textContent=record.cleared+' / 9';$('dash').disabled=state.phase!=='playing'||paused||p.dashCd>0;$('dashNote').textContent=p.dashCd>0?(p.dashCd/60).toFixed(1)+'s RECHARGING':'SPACE · READY';$('dashBar').style.width=(1-p.dashCd/st.dashCd)*100+'%';
const boss=state.enemies.find(e=>e.type==='boss');$('bossHud').hidden=!boss;if(boss){$('bossName').textContent=['THE THORN REGENT','THE PRISM ORACLE','THE SOLAR SOVEREIGN'][boss.boss-1]+(boss.phase===2?' · ENRAGED':'');$('bossBar').style.width=Math.max(0,boss.hp/boss.maxHp)*100+'%';}
$('remaining').textContent=state.phase==='playing'?(R.tuning(state.stage).quota-state.spawned+state.enemies.filter(e=>e.type!=='boss').length)+' DEFENDERS LEFT'+(state.stage%3===0?' + GUARDIAN':''):'9 GATES · 3 GUARDIANS';$('objective').textContent=paused?'Paused. Resume when ready.':state.phase==='upgrade'?'Gate reclaimed. Choose your next module.':state.phase==='victory'?'The citadel is yours.':state.phase==='dead'?'A new expedition awaits.':state.stage===1?'Defeat all defenders. Watch the red warnings.':'Clear the gate. Evolve. Push deeper.';$('hint').hidden=state.phase!=='playing'||paused||state.tick>tipUntil;
if(force||lastPortrait!==state.tier){lastPortrait=state.tier;view.portrait($('portrait'),state.tier,0);$('gates').replaceChildren();for(let i=1;i<=9;i++){const n=document.createElement('i');n.className=(i%3===0?'boss ':'')+(i<=state.cleared?'done':i===state.stage?'active':'');n.title='Gate '+i;$('gates').append(n);}$('loadout').replaceChildren();let count=0;for(const u of R.UPGRADES){const level=state.upgrades[u.id];if(!level)continue;count++;const row=document.createElement('div');row.className='module';const name=document.createElement('b'),value=document.createElement('em');name.textContent=symbols[u.id]+' '+u.name;value.textContent='Ⅰ'.repeat(level);row.append(name,value);$('loadout').append(row);}if(!count){const n=document.createElement('span');n.textContent='No modules installed yet.';$('loadout').append(n);}}}
function frame(now){if(disposed)return;const dt=Math.max(0,Math.min(.05,(now-last)/1000||0));last=now;if(state.phase==='playing'&&!paused&&!document.hidden){acc+=dt;let n=0;while(acc>=1/60&&n++<4&&state.phase==='playing'){const input=movement();R.step(state,input);dashRequested=false;view.effects(state.events);state.events.forEach(e=>audio.event(e));acc-=1/60;}if(state.phase!==phase){phase=state.phase;if(phase==='upgrade')showUpgrade();if(phase==='dead'||phase==='victory')result();sync(true);}else sync();}else acc=0;const move=movement();view.draw(state,now/1000,{reduced,moving:!paused&&(Math.abs(move.x)+Math.abs(move.y)>.1),joy:paused?null:joy});frameId=requestAnimationFrame(frame);}
window.addEventListener('pagehide',e=>{audio.stop();resetInput();if(!e.persisted){disposed=true;cancelAnimationFrame(frameId);audio.close();}else if(state.phase==='playing'&&!paused)togglePause();});
window.addEventListener('pageshow',()=>{last=performance.now();acc=0;});
window.AstraDiagnostics=Object.freeze({snapshot:()=>JSON.parse(JSON.stringify({state,paused,capture,record,version:R.VERSION})),resources:()=>({...view.resources(),voices:audio.voices.size})});
setSound();sync(true);$('play').disabled=false;$('play').textContent='BEGIN EXPEDITION →';frameId=requestAnimationFrame(frame);
})();
