/* One choice per game. One compact board. No synthetic opponents or rank deltas. */
(function(){'use strict';
const L=WorldLeague,C=L.C,$=q=>document.querySelector(q);let scope='nations',request=0,controller=null,data=null;
function myPosition(){const box=$('#homePlayerSummary'),p=C?.profile;$('#joinNote').hidden=!!p;box.hidden=!p;if(!p)return;if(!data){box.textContent='Your player card is ready. Standings are not loaded yet.';return;}const r=data.rows.find(r=>scope==='nations'?p.country&&r.country_code===p.country:r.handle?.toLowerCase()===p.handle.toLowerCase());box.textContent=r?(scope==='nations'?'Your country':'Your record')+' · #'+r.rank+' · '+L.number(r.points)+' points':'Your '+(scope==='nations'?'country':'player ID')+' has no entry in the displayed top 100 this week.';}
async function loadBoard(){const id=++request;controller?.abort();const own=new AbortController();controller=own;const timer=setTimeout(()=>own.abort(),10000);data=null;$('#homeRows').replaceChildren();$('#homeEmpty').hidden=true;$('#retryHome').hidden=true;$('#homeStatus').classList.remove('error');$('#homeStatus').textContent='Loading standings…';$('.home-table-wrap').setAttribute('aria-busy','true');myPosition();
try{const result=await L.readBoard({scope},own.signal);if(id!==request)return;data=result;for(const r of data.rows.slice(0,5)){const tr=L.node('tr'),rank=L.node('td',String(r.rank).padStart(2,'0')),name=L.node('td'),value=L.node('td',L.number(r.points)),link=L.node('a');if(scope==='nations'){link.href='/community/?game=all&scope=country&country='+encodeURIComponent(r.country_code);L.label(link,r.country_code,C.countryName(r.country_code));}else{link.href='/community/?game=all&scope=world';L.label(link,r.country_code,r.handle);}name.append(link);name.append(L.node('small',scope==='nations'?r.contributors+' of '+r.players+' player'+(r.players===1?'':'s')+' contributing':r.games_played+' ranked game'+(r.games_played===1?'':'s'),'row-detail'));tr.append(rank,name,value);$('#homeRows').append(tr);}$('#homeEmpty').hidden=data.rows.length>0;$('#homeStatus').textContent='Championship points · Updated '+new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});myPosition();}
catch{if(id===request){$('#homeStatus').textContent='Rankings unavailable. You can still play.';$('#homeStatus').classList.add('error');$('#retryHome').hidden=false;}}
finally{clearTimeout(timer);if(id===request)$('.home-table-wrap').setAttribute('aria-busy','false');}}
$('#homeScopes').addEventListener('click',e=>{const b=e.target.closest('[data-home-scope]');if(!b)return;scope=b.dataset.homeScope;document.querySelectorAll('[data-home-scope]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));$('#homeNameHeader').textContent=scope==='nations'?'Country':'Player';$('#fullStandings').href='/community/?game=all&scope='+scope;loadBoard();});$('#retryHome').onclick=loadBoard;
for(const a of document.querySelectorAll('.game-card'))a.addEventListener('click',()=>{const u=new URL(a.href);const game=u.pathname.replace(/\/+$/,'')==='/descent'?'gyro-drop':u.searchParams.get('game')||'orbit-sprint';L.track('next_game',{from:'simple-home',to:game});});
function stars(x){for(let i=0;i<38;i++){x.fillStyle='#9cefe2';x.globalAlpha=.08+(i%5)*.025;x.fillRect((i*137)%640,24+(i*67)%300,1+(i%7===0),1+(i%5===0));}x.globalAlpha=1;}
function gyro(c){const x=c.getContext('2d');x.fillStyle='#08100f';x.fillRect(0,0,640,400);stars(x);for(let j=0;j<4;j++){const cy=165+j*55,rx=190-j*11,ry=32-j*2;x.strokeStyle=j===1?'#ff657e':'#52776f';x.lineWidth=12;x.beginPath();x.ellipse(320,cy,rx,ry,0,.18+j*.45,5.45+j*.22);x.stroke();}x.fillStyle='#d5ff68';x.beginPath();x.arc(320,95,16,0,Math.PI*2);x.fill();x.strokeStyle='#66edd5';x.lineWidth=3;x.beginPath();x.arc(320,95,23,0,Math.PI*2);x.stroke();}
function pins(c){const x=c.getContext('2d');x.fillStyle='#07100f';x.fillRect(0,0,640,400);stars(x);x.strokeStyle='#66edd5';x.lineWidth=5;x.beginPath();x.arc(320,180,76,0,Math.PI*2);x.stroke();x.fillStyle='#d5ff68';x.beginPath();x.arc(320,180,34,0,Math.PI*2);x.fill();for(const a of [.2,1.4,2.7,4.2]){const x1=320+Math.cos(a)*75,y1=180+Math.sin(a)*75,x2=320+Math.cos(a)*125,y2=180+Math.sin(a)*125;x.strokeStyle=a>4?'#ff657e':'#f4f1e8';x.lineWidth=5;x.beginPath();x.moveTo(x1,y1);x.lineTo(x2,y2);x.stroke();}x.fillStyle='#f4f1e8';x.beginPath();x.moveTo(308,360);x.lineTo(332,360);x.lineTo(320,310);x.closePath();x.fill();}
function merge(c){const x=c.getContext('2d');x.fillStyle='#070c12';x.fillRect(0,0,640,400);stars(x);const colors=['#66edd5','#7aa2ff','#c47cff','#ff6f91','#ffd166'];for(let col=0;col<7;col++){x.fillStyle=col===3?'#d5ff6814':'#26332f33';x.fillRect(42+col*80,86,70,276);}const orbs=[[2,0,0],[2,1,0],[3,0,1],[3,1,1],[3,2,0],[4,0,2],[4,1,2],[1,0,1],[5,0,0]];for(const [col,row,lv] of orbs){const cx=77+col*80,cy=335-row*62,r=18+lv*3;x.fillStyle=colors[lv];x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.fill();}x.fillStyle='#c47cff';x.beginPath();x.arc(320,48,18,0,Math.PI*2);x.fill();}
function orbit(c){const x=c.getContext('2d');x.fillStyle='#0a1530';x.fillRect(0,0,640,400);for(let i=0;i<42;i++){x.fillStyle='#7ea4c1';x.fillRect((i*131)%640,(i*47)%190,1,1);}x.strokeStyle='#6dbccb';x.lineWidth=2;for(let i=0;i<4;i++){x.beginPath();x.moveTo(280+i*26,120);x.lineTo(-20+i*230,430);x.stroke();}for(let i=0;i<7;i++){x.beginPath();x.moveTo(155-i*23,170+i*34);x.lineTo(485+i*23,170+i*34);x.strokeStyle='#344d66';x.stroke();}x.fillStyle='#234361';x.fillRect(390,205,44,82);x.strokeStyle='#fa75b0';x.strokeRect(390,205,44,82);x.fillStyle='#bddeee';x.beginPath();x.moveTo(320,253);x.lineTo(352,323);x.lineTo(320,305);x.lineTo(288,323);x.closePath();x.fill();x.fillStyle='#79dec6';x.beginPath();x.moveTo(320,270);x.lineTo(330,300);x.lineTo(310,300);x.closePath();x.fill();}
for(const c of document.querySelectorAll('canvas[data-preview]'))try{({'gyro-drop':gyro,'core-pins':pins,'nova-merge':merge,'orbit-sprint':orbit}[c.dataset.preview]||orbit)(c);}catch{c.setAttribute('aria-label',c.dataset.preview+' illustration unavailable');}
loadBoard();L.ready.then(myPosition);document.addEventListener('league:identity',myPosition);
})();