(function(){'use strict';const L=WorldLeague,C=L.C,$=q=>document.querySelector(q);let players=null,nations=null,playerError=false;const seenAt=()=>new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});
// Keep a word break when the decorative <br> is hidden in the mobile layout.
$('.how-card h2 br')?.before(document.createTextNode(' '));
function failure(status,target,retry){status.textContent='Standings unavailable — games are still playable.';status.classList.add('error');const b=L.node('button','Retry rankings','text-link');b.onclick=()=>{b.remove();retry();};target.replaceChildren(b);}
function invite(){const a=L.node('a',undefined,'nation-invite');a.href='/community/?panel=profile';a.append(L.node('span','+'));const d=L.node('div');d.append(L.node('strong','Bring the next flag to the league.'),L.node('p','Open beta. New countries join with their first verified score.'));a.append(d);return a;}
async function loadNations(){const status=$('#homeNationStatus'),target=$('#homeNations');status.classList.remove('error');status.textContent='Loading verified standings…';nations=null;try{nations=await L.readBoard({scope:'nations'});target.replaceChildren();for(const [i,r]of nations.rows.slice(0,4).entries()){const a=L.node('a',undefined,'country-row'+(i===0?' leader':''));a.href='/community/?game=all&scope=country&country='+encodeURIComponent(r.country_code);a.append(L.node('span',String(r.rank).padStart(2,'0'),'country-rank'));const name=L.node('div',undefined,'country-details'),flagName=L.node('div');L.label(flagName,r.country_code,C.countryName(r.country_code));name.append(flagName,L.node('small',r.contributors+' of '+r.players+' player'+(r.players===1?'':'s')+' contributing'));a.append(name);const score=L.node('div',undefined,'country-points');score.append(L.node('b',L.number(r.points)),L.node('small','CHAMPIONSHIP PTS'));a.append(score);target.append(a);}if(nations.rows.length<3)target.append(invite());status.textContent='Verified standings · Updated '+seenAt();playerStatus();}catch{failure(status,target,loadNations);}}
async function loadPlayers(){const status=$('#homePlayersStatus'),target=$('#homePlayers');status.classList.remove('error');status.textContent='Loading verified players…';players=null;playerError=false;playerStatus();try{players=await L.readBoard({scope:'world'});target.replaceChildren();for(const r of players.rows.slice(0,5)){const a=L.node('a',undefined,'mini-player');a.href='/community/?game=all&scope=world';a.append(L.node('b','#'+r.rank));const name=L.node('span');L.label(name,r.country_code,r.handle);a.append(name);const s=L.node('span',undefined,'mini-score');s.append(L.node('b',L.number(r.points)),L.node('small',r.games_played+' ranked game'+(r.games_played===1?'':'s')));a.append(s);target.append(a);}if(!players.rows.length)target.append(L.node('p','No verified records this week. Start the first challenge.','empty'));status.textContent='Weekly championship · Updated '+seenAt();playerStatus();}catch{playerError=true;failure(status,target,loadPlayers);playerStatus();}}
function playerStatus(){const p=C?.profile;if(!p)return;L.label($('#homePlayerTitle'),p.country,p.handle);const r=players?.rows.find(r=>r.handle.toLowerCase()===p.handle.toLowerCase());const n=nations?.rows.find(r=>r.country_code===p.country);$('#homePlayerSummary').textContent=!players?(playerError?'Your player card is ready. Standings are unavailable; retry the table below.':'Your player card is ready. Loading your weekly standings…'):r?'Your weekly total: '+L.number(r.points)+' pts · #'+r.rank+' among listed players'+(n?' · '+C.countryName(p.country)+' #'+n.rank:''):'No record in the displayed weekly top 100 yet. Your next ranked run is a new chance.';$('#homePlayerAction').textContent='View my standings →';$('#homePlayerAction').href='/community/?game=all&scope=world';}
$('#gameSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();let visible=0;document.querySelectorAll('[data-title]').forEach(n=>{n.hidden=!n.dataset.title.includes(q);if(!n.hidden)visible++;});$('#noGames').hidden=visible>0;});
document.querySelectorAll('.game-visual,.play-link').forEach(a=>a.addEventListener('click',()=>L.track('next_game',{from:'league',to:new URL(a.href).searchParams.get('game')||'orbit-sprint'})));
// Orbit preview reuses the original game's lane/ship geometry; it is an illustration, not a score claim.
function orbit(c){const x=c.getContext('2d');x.fillStyle='#0a1530';x.fillRect(0,0,640,400);for(let i=0;i<42;i++){x.fillStyle='#7ea4c1';x.fillRect((i*131)%640,(i*47)%190,1,1);}x.strokeStyle='#6dbccb';x.lineWidth=2;for(let i=0;i<4;i++){x.beginPath();x.moveTo(280+i*26,120);x.lineTo(-20+i*230,430);x.stroke();}for(let i=0;i<7;i++){x.beginPath();x.moveTo(155-i*23,170+i*34);x.lineTo(485+i*23,170+i*34);x.strokeStyle='#344d66';x.stroke();}x.fillStyle='#234361';x.fillRect(390,205,44,82);x.strokeStyle='#fa75b0';x.strokeRect(390,205,44,82);x.fillStyle='#bddeee';x.beginPath();x.moveTo(320,253);x.lineTo(352,323);x.lineTo(320,305);x.lineTo(288,323);x.closePath();x.fill();x.fillStyle='#79dec6';x.beginPath();x.moveTo(320,270);x.lineTo(330,300);x.lineTo(310,300);x.closePath();x.fill();x.beginPath();x.moveTo(312,320);x.lineTo(328,320);x.lineTo(320,352);x.closePath();x.fill();}
for(const c of document.querySelectorAll('canvas[data-preview]'))try{if(c.dataset.preview==='orbit-sprint')orbit(c);else{const r=new ArcadeRenderer(c,c.dataset.preview);r.reduced=true;r.draw(ArcadeRules.create(c.dataset.preview,125904),0);}}catch{c.setAttribute('aria-label',c.dataset.preview+' game illustration unavailable');}
loadNations();loadPlayers();L.ready.then(config=>{for(const card of document.querySelectorAll('.game-card')){const game=card.querySelector('canvas')?.dataset.preview;const badge=card.querySelector('.game-kind span');if(badge)badge.textContent=config?.rankedGames?.some(g=>g.game===game)?'RANKED':config?'PRACTICE':'CHECK STATUS';}playerStatus();});document.addEventListener('league:identity',playerStatus);
})();
