/* One choice per game. One compact board. No synthetic opponents or rank deltas. */
(function(){'use strict';
const L=WorldLeague,C=L.C,$=q=>document.querySelector(q);let scope='nations',request=0,controller=null,data=null;
function myPosition(){const box=$('#homePlayerSummary'),p=C?.profile;$('#joinNote').hidden=!!p;box.hidden=!p;if(!p)return;if(!data){box.textContent='Your player card is ready. Standings are not loaded yet.';return;}const r=data.rows.find(r=>scope==='nations'?p.country&&r.country_code===p.country:r.handle?.toLowerCase()===p.handle.toLowerCase());box.textContent=r?(scope==='nations'?'Your country':'Your record')+' · #'+r.rank+' · '+L.number(r.points)+' points':'Your '+(scope==='nations'?'country':'player ID')+' has no entry in the displayed top 100 this week.';}
async function loadBoard(){const id=++request;controller?.abort();const own=new AbortController();controller=own;const timer=setTimeout(()=>own.abort(),10000);data=null;$('#homeRows').replaceChildren();$('#homeEmpty').hidden=true;$('#retryHome').hidden=true;$('#homeStatus').classList.remove('error');$('#homeStatus').textContent='Loading standings…';$('.home-table-wrap').setAttribute('aria-busy','true');myPosition();
try{const result=await L.readBoard({scope},own.signal);if(id!==request)return;data=result;for(const r of data.rows.slice(0,5)){const tr=L.node('tr'),rank=L.node('td',String(r.rank).padStart(2,'0')),name=L.node('td'),value=L.node('td',L.number(r.points)),link=L.node('a');if(scope==='nations'){link.href='/community/?game=all&scope=country&country='+encodeURIComponent(r.country_code);L.label(link,r.country_code,C.countryName(r.country_code));}else{link.href='/community/?game=all&scope=world';L.label(link,r.country_code,r.handle);}name.append(link);name.append(L.node('small',scope==='nations'?r.contributors+' of '+r.players+' player'+(r.players===1?'':'s')+' contributing':r.games_played+' ranked game'+(r.games_played===1?'':'s'),'row-detail'));tr.append(rank,name,value);$('#homeRows').append(tr);}$('#homeEmpty').hidden=data.rows.length>0;$('#homeStatus').textContent='Championship points · Updated '+new Date().toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'});myPosition();}
catch{if(id===request){$('#homeStatus').textContent='Rankings unavailable. You can still play.';$('#homeStatus').classList.add('error');$('#retryHome').hidden=false;}}
finally{clearTimeout(timer);if(id===request)$('.home-table-wrap').setAttribute('aria-busy','false');}}
$('#homeScopes').addEventListener('click',e=>{const b=e.target.closest('[data-home-scope]');if(!b)return;scope=b.dataset.homeScope;document.querySelectorAll('[data-home-scope]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));$('#homeNameHeader').textContent=scope==='nations'?'Country':'Player';$('#fullStandings').href='/community/?game=all&scope='+scope;loadBoard();});$('#retryHome').onclick=loadBoard;
for(const a of document.querySelectorAll('.game-card'))a.addEventListener('click',()=>L.track('next_game',{from:'simple-home',to:new URL(a.href).searchParams.get('game')||'orbit-sprint'}));
// Orbit uses the released ship/lane geometry for an illustration, never a score claim.
function orbit(c){const x=c.getContext('2d');x.fillStyle='#0a1530';x.fillRect(0,0,640,400);for(let i=0;i<42;i++){x.fillStyle='#7ea4c1';x.fillRect((i*131)%640,(i*47)%190,1,1);}x.strokeStyle='#6dbccb';x.lineWidth=2;for(let i=0;i<4;i++){x.beginPath();x.moveTo(280+i*26,120);x.lineTo(-20+i*230,430);x.stroke();}for(let i=0;i<7;i++){x.beginPath();x.moveTo(155-i*23,170+i*34);x.lineTo(485+i*23,170+i*34);x.strokeStyle='#344d66';x.stroke();}x.fillStyle='#234361';x.fillRect(390,205,44,82);x.strokeStyle='#fa75b0';x.strokeRect(390,205,44,82);x.fillStyle='#bddeee';x.beginPath();x.moveTo(320,253);x.lineTo(352,323);x.lineTo(320,305);x.lineTo(288,323);x.closePath();x.fill();x.fillStyle='#79dec6';x.beginPath();x.moveTo(320,270);x.lineTo(330,300);x.lineTo(310,300);x.closePath();x.fill();x.beginPath();x.moveTo(312,320);x.lineTo(328,320);x.lineTo(320,352);x.closePath();x.fill();}
for(const c of document.querySelectorAll('canvas[data-preview]'))try{if(c.dataset.preview==='orbit-sprint')orbit(c);else{const r=new ArcadeRenderer(c,c.dataset.preview);r.reduced=true;r.draw(ArcadeRules.create(c.dataset.preview,125904),0);}}catch{c.setAttribute('aria-label',c.dataset.preview+' illustration unavailable');}
loadBoard();L.ready.then(myPosition);document.addEventListener('league:identity',myPosition);
})();
