'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../auth/play-id.js');
const {makeHandler,cookieToken}=require('../../vibe-arcade/api/play-id.js');
const GOOD='quiet moons cross winter hills';
test('ID is case-insensitive, bounded and excludes reserved names',()=>{assert.equal(A.id(' Orbit_4 '),'orbit_4');for(const x of ['abc','a'.repeat(17),'with space','admin','../evil',null])assert.throws(()=>A.id(x));});
test('password accepts phrases/Unicode and normalizes NFC without trimming',()=>{assert.equal(A.password('  '+GOOD+'  ','pilot'), '  '+GOOD+'  ');assert.equal(A.password('가나다라마바사아자차카타파하가나다','pilot').length,17);assert.equal(A.password('e\u0301'.repeat(15),'pilot',false),'é'.repeat(15));});
test('rejects short, huge, common and repeating passwords',()=>{for(const p of ['short','x'.repeat(129),'passwordpassword','1'.repeat(16),GOOD+'\n'])assert.throws(()=>A.password(p,'pilot'));});
test('PBKDF2 hash uses the full password and independent salts',async()=>{const s1=A.random(16),s2=A.random(16);const h=await A.derive(GOOD,s1);assert.match(h,/^[a-f0-9]{64}$/);assert.equal(h,await A.derive(GOOD,s1));assert.notEqual(h,await A.derive(GOOD,s2));assert.notEqual(h,await A.derive(GOOD+'!',s1));assert(A.equal(h,h));assert(!A.equal(h,h.slice(1)));assert(!A.equal(h,'0'.repeat(64)));});
function mock(){const calls=[],salt=A.random(16);let row={collision:false},rate=true,enabled=true;const rpc=async(action,p={})=>{calls.push([action,p]);if(action==='config')return {enabled};if(action==='rate')return {allowed:rate};if(action==='lookup')return row;if(action==='enter'||action==='recover')return {profile:{handle:p.login,country:'KR'},expiresAt:new Date(Date.now()+604800000).toISOString()};if(action==='session')return {subject:'a'.repeat(64)};return {};};return {calls,rpc,setRow:r=>row=r,setRate:x=>rate=x,setEnabled:x=>enabled=x,make:()=>A.create({rpc,secret:'private-test-key',countries:new Set(['KR','US'])}),salt};}
test('create hashes every secret before SQL and issues a recovery code',async()=>{const m=mock(),r=await m.make().enter({id:'Pilot_4',password:GOOD,country:'KR',consent:true,age16:true},'test-ip');assert(r.created);assert.match(r.token,/^ljp_[a-f0-9]{64}$/);assert.match(r.recoveryCode,/^ljr_[a-f0-9]{48}$/);const wire=JSON.stringify(m.calls);for(const secret of [GOOD,r.token,r.recoveryCode,'test-ip'])assert(!wire.includes(secret));assert(m.calls.some(([k])=>k==='rate'));});
test('existing login cannot change its country',async()=>{const m=mock();m.setRow({hash:await A.derive(GOOD,m.salt),salt:m.salt,subject:'a'.repeat(64)});const r=await m.make().enter({id:'pilot_4',password:GOOD,country:'US'},'ip');assert.equal(r.created,false);assert.equal(r.profile.country,'KR');assert.equal(r.recoveryCode,undefined);});
test('incorrect password never invokes commit',async()=>{const m=mock();m.setRow({hash:await A.derive(GOOD,m.salt),salt:m.salt,subject:'a'.repeat(64)});await assert.rejects(m.make().enter({id:'pilot_4',password:GOOD+'!'},'ip'),/invalid_credentials/);assert(!m.calls.some(([a])=>a==='enter'));});
test('existing Google handle cannot be claimed by a Play ID',async()=>{const m=mock();m.setRow({collision:true});await assert.rejects(m.make().enter({id:'pilot_4',password:GOOD,country:'KR',consent:true,age16:true},'ip'),/invalid_credentials/);});
test('new account requires a country and consent',async()=>{for(const body of [{country:''},{country:'ZZ'},{country:'KR',consent:false}]){const m=mock();await assert.rejects(m.make().enter({id:'pilot_4',password:GOOD,...body},'ip'),/invalid_country|consent_required/);}});
test('rate limit happens before the credential lookup',async()=>{const m=mock();m.setRate(false);await assert.rejects(m.make().enter({id:'pilot_4',password:GOOD},'ip'),/rate_limited/);assert(!m.calls.some(([a])=>a==='lookup'));});
test('disabled auth fails closed',async()=>{const m=mock();m.setEnabled(false);await assert.rejects(m.make().enter({id:'pilot_4',password:GOOD},'ip'),/play_id_unavailable/);assert.equal(m.calls.length,1);});
test('reset rotates secrets and only hashes reach SQL',async()=>{const m=mock(),old='ljr_'+A.random(24),r=await m.make().recover({id:'pilot_4',password:GOOD,recoveryCode:old},'ip');assert(r.recovered);assert.notEqual(r.recoveryCode,old);const wire=JSON.stringify(m.calls);for(const secret of [old,r.recoveryCode,GOOD,r.token])assert(!wire.includes(secret));});
test('malformed session rejected before DB lookup',async()=>{const m=mock();await assert.rejects(m.make().resolve('not-a-token'));assert.equal(m.calls.length,0);});
test('opaque session lookup hashes token',async()=>{const m=mock(),token='ljp_'+A.random();assert.equal(await m.make().resolve(token),'a'.repeat(64));assert(!JSON.stringify(m.calls).includes(token));});
const TOKEN='ljp_'+'a'.repeat(64),ORIGIN='https://vibe-arcade-dun.vercel.app';
function req(action='auth_enter'){return {method:'POST',query:{action},headers:{origin:ORIGIN,'content-type':'application/json','sec-fetch-site':'same-origin'},body:{id:'pilot_4',password:GOOD,country:'KR',consent:true,age16:true}};}
function response(){return {statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(data){this.data=data;return this;}};}
test('proxy issues HttpOnly Secure cookie but never returns the token',async()=>{let posted;const h=makeHandler(async(url,opts)=>{posted=opts;return {ok:true,status:200,json:async()=>({token:TOKEN,expiresAt:new Date(Date.now()+604800000).toISOString(),profile:{handle:'pilot_4',country:'KR'},created:true,recoveryCode:'recovery-once'})};});const res=response();await h(req(),res);assert.equal(res.statusCode,200);assert.match(res.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Lax/);assert(!JSON.stringify(res.data).includes(TOKEN));assert.equal(posted.headers.Origin,ORIGIN);});
test('proxy rejects cross-origin, missing origin and unsupported actions',async()=>{let count=0;const h=makeHandler(async()=>{count++;});for(const patch of [{headers:{origin:'https://evil.invalid'}},{headers:{}},{query:{action:'arbitrary_rpc'}},{method:'GET'}]){const r=req();Object.assign(r,patch);const res=response();await h(r,res);assert(res.statusCode>=400);}assert.equal(count,0);});
test('proxy rejects arrays, non-JSON and huge input',async()=>{const h=makeHandler(async()=>assert.fail());for(const modify of [r=>r.body=[],r=>r.headers['content-type']='text/plain',r=>r.body={a:'a'.repeat(65537)}]){const r=req();modify(r);const res=response();await h(r,res);assert(res.statusCode>=400);}});
test('proxy takes auth only from cookie, never body subject/bearer',async()=>{let posted;const h=makeHandler(async(url,opts)=>{posted=opts;return {ok:true,status:200,json:async()=>({profile:{handle:'pilot_4'}})};});const r=req('profile');r.headers.cookie='__Host-loopjolt_play='+TOKEN;r.headers.authorization='Bearer attacker';r.body={subject:'attacker'};const res=response();await h(r,res);assert.equal(posted.headers.Authorization,'Bearer '+TOKEN);});
test('logout clears cookie even when backend is unavailable',async()=>{const h=makeHandler(async()=>{throw Error('offline')});const r=req('auth_logout');r.headers.cookie='__Host-loopjolt_play='+TOKEN;const res=response();await h(r,res);assert.match(res.headers['Set-Cookie'],/Max-Age=0/);assert.equal(res.statusCode,503);});
test('unknown cookie never authenticates and no raw malformed token accepted',()=>{assert.equal(cookieToken('__Host-loopjolt_play='+TOKEN),TOKEN);assert.equal(cookieToken('__Host-loopjolt_play=evil'),'');assert.equal(cookieToken('other='+TOKEN),'');});
