(function(){'use strict';
const C=LoopCommunity,$=s=>document.querySelector(s),query=new URLSearchParams(location.search);let scope=['world','country','nations'].includes(query.get('scope'))?query.get('scope'):'world',request=0,cfg=null;const names=new Intl.DisplayNames(['en'],{type:'region'});
// Native select options remain text for keyboard/mobile accessibility. A real SVG preview
// next to the selected value replaces unsupported emoji inside native dropdowns.
function countryOptions(el,blank){if(blank)el.add(new Option(blank,''));C.countries.map(code=>({code,name:names.of(code)||code})).sort((a,b)=>a.name.localeCompare(b.name)).forEach(c=>el.add(new Option(c.name+' ('+c.code+')',c.code)));}
countryOptions($('#country'),'No flag / prefer not to say');countryOptions($('#countryFilter'));const localeRegion=(navigator.language.split('-')[1]||'').toUpperCase();$('#countryFilter').value=C.countries.includes(query.get('country'))?query.get('country'):C.countries.includes(localeRegion)?localeRegion:'US';$('#period').value=query.get('period')==='all'?'all':'week';
function previews(){C.selectionPreview($('#country'));C.selectionPreview($('#countryFilter'));}
function message(el,text,error=false){el.textContent=text;el.classList.toggle('error',error);}
const human=e=>({login_not_configured:'Google login is awaiting owner setup. Guest play is ready.',invalid_or_expired_login:'Sign-in expired. Please sign in again.',country_locked_30_days:'Country changes are limited to once every 30 days.',handle_taken:'That player ID is taken. Choose another.',invalid_handle:'Use 3–20 letters, numbers or underscores. Reserved names are not allowed.',google_unavailable:'Google could not load. Guest play is still available.',consent_required:'Please confirm both checkboxes.',account_blocked:'This account is not eligible to post ranked scores.',game_validator_unavailable:'Ranked validation is not available for that game yet.'}[e.message]||'Could not complete this request. Try again.');
function selectedGame(){return $('#gameFilter').value||'orbit-sprint';}
function titleForGame(){return $('#gameFilter').selectedOptions[0]?.textContent||'Rankings';}
function boardRule(data){if(data.mode==='overall')return scope==='nations'?'All-game country standings: top 10 distinct players’ overall championship points per country. One current profile flag per player. '+(data.rankedGameCount||0)+' ranked game(s) currently count.':'All-game player standings: '+data.overallRule+' Positive scores only; one current profile flag per player.';if(scope==='nations')return data.countryRule||'Country standings sum the top 10 distinct players’ best scores for this game.';return 'Best positive server-validated '+titleForGame()+' run per player'+(scope==='country'?' in the selected country.':'. Weekly boards reset Monday at 00:00 UTC.');}
function setHeaders(data){const nations=scope==='nations',overall=data.mode==='overall';$('#nameHeader').textContent=nations?'COUNTRY':'PLAYER';$('#countryHeader').textContent=nations?'TOP / TOTAL':overall?'COUNTRY · GAMES':'COUNTRY';$('#scoreHeader').textContent=overall?'CHAMPIONSHIP':'SCORE';$('#boardTitle').textContent=(overall?'All ranked games':titleForGame())+' · '+(nations?'countries':scope==='country'?'players in country':'players');}
async function board(){const id=++request;message($('#boardStatus'),'Loading rankings…');try{const u=new URL(C.endpoint);u.search=new URLSearchParams({action:'board',game:selectedGame(),scope,period:$('#period').value,country:$('#countryFilter').value});const res=await fetch(u,{cache:'no-store',signal:AbortSignal.timeout(10000)});const data=await res.json();if(!res.ok)throw Error(data.error||'board_failed');if(id!==request)return;setHeaders(data);$('#rule').textContent=boardRule(data);$('#rows').replaceChildren();data.rows.forEach(row=>{
 const tr=document.createElement('tr'),nations=scope==='nations';
 const values=nations?[row.rank,C.countryName(row.country_code),row.contributors+'/'+row.players+' players',Number(row.points).toLocaleString()]:[row.rank,row.handle,(row.country_code||'—')+(data.mode==='overall'?' · '+row.games_played+' game'+(row.games_played===1?'':'s'):''),Number(data.mode==='overall'?row.points:row.score).toLocaleString()];
 values.forEach((v,i)=>{const td=document.createElement('td');if(i===1){C.renderFlagLabel(td,row.country_code,v);if(!nations)td.className='player-id';}else td.textContent=v;if(i===2)td.className='country';tr.append(td);});$('#rows').append(tr);
 });$('#empty').hidden=data.rows.length>0;message($('#boardStatus'),'Live board · '+data.rows.length+' '+(data.rows.length===1?'entry':'entries')+' shown');}catch(e){if(id===request)message($('#boardStatus'),'Rankings are temporarily unavailable. Guest play still works.',true);}}
function ui(){const p=C.profile;$('#login').hidden=C.authenticated;$('#profileForm').hidden=!C.authenticated;$('#signedIn').hidden=!C.authenticated;if(p)C.renderFlagLabel($('#accountTitle'),p.country,p.handle);else $('#accountTitle').textContent='Play now. Join when ready.';if(p){$('#handle').value=p.handle;$('#country').value=p.country||'';$('#consent').checked=true;$('#age16').checked=true;if(p.country&&!query.has('country'))$('#countryFilter').value=p.country;}if(!C.authenticated)$('#google').replaceChildren();previews();}
function scopeUI(){document.querySelectorAll('[data-scope]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.scope===scope)));$('#countryFilter').hidden=scope!=='country';previews();}
function loadGames(){const select=$('#gameFilter');[...(cfg?.rankedGames||[{game:'orbit-sprint',version:'orbit-v1',title:'Orbit Sprint'}])].forEach(g=>{if(![...select.options].some(o=>o.value===g.game))select.add(new Option(g.title,g.game));});const wanted=query.get('game')||'orbit-sprint';if([...select.options].some(o=>o.value===wanted))select.value=wanted;scopeUI();}
$('#scopes').addEventListener('click',e=>{const b=e.target.closest('[data-scope]');if(!b)return;scope=b.dataset.scope;scopeUI();board();});$('#period').onchange=board;$('#gameFilter').onchange=board;$('#countryFilter').onchange=()=>{previews();board();};$('#country').onchange=previews;
$('#login').onclick=async()=>{try{await C.googleButton($('#google'),async()=>{ui();message($('#accountStatus'),C.profile?'Signed in.':'Choose your public player ID to join rankings.');},e=>message($('#accountStatus'),human(e),true));$('#login').hidden=true;}catch(e){message($('#accountStatus'),human(e),true);}};
$('#profileForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await C.api('save_profile',{handle:$('#handle').value.trim(),country:$('#country').value,consent:$('#consent').checked,age16:$('#age16').checked});await C.me();ui();message($('#accountStatus'),'Saved. Your flag image appears beside your player ID on rankings.');board();}catch(err){message($('#accountStatus'),human(err),true);}finally{b.disabled=false;}};
$('#logout').onclick=()=>{C.logout();ui();message($('#accountStatus'),'Signed out.');};$('#delete').onclick=async()=>{const typed=prompt('This deletes your LoopJolt profile and scores only, not your Google account. Type DELETE MY LOOPJOLT ACCOUNT to confirm.');if(typed!=='DELETE MY LOOPJOLT ACCOUNT')return;try{await C.api('delete_profile',{confirmation:typed});C.logout();ui();board();message($('#accountStatus'),'LoopJolt account and scores deleted.');}catch(e){message($('#accountStatus'),human(e),true);}};
(async()=>{try{cfg=await C.config();loadGames();if(C.authenticated){await C.me();ui();}if(!cfg.loginReady){$('#login').disabled=true;message($('#accountStatus'),'Google login is awaiting owner setup. Guest play is ready.');}await board();}catch{message($('#accountStatus'),'Account service unavailable; play as a guest.',true);await board();}})();
})();
