'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..');
function collect(event){const logs=[],sandbox={module:{exports:{}},console:{log(...args){logs.push(args);}}};vm.runInNewContext(fs.readFileSync(path.join(root,'api/event.js'),'utf8'),sandbox);const res={code:0,status(c){this.code=c;return this;},json(d){this.data=d;return this;},end(){return this;}};sandbox.module.exports({method:'POST',body:{event,source:'instagram',campaign:'qa_fixture',content:'dd_fc01',props:{game:'gyro-drop',ranked:true}}},res);return{res,logs};}
for(const event of ['page_view','game_open','game_start','game_finish','replay','share','next_game','score_verified','ranked_downgrade'])test('collector accepts existing event '+event,()=>{const {res,logs}=collect(event);assert.equal(res.code,204);assert.equal(logs.length,1);const body=JSON.parse(logs[0][1]);assert.equal(body.source,'instagram');assert.equal(body.props.game,'gyro-drop');});
test('unknown events still rejected',()=>{const {res,logs}=collect('arbitrary_auth_password');assert.equal(res.code,400);assert.equal(logs.length,0);});
test('actual home click handlers correctly identify all four game cards',()=>{
 const cards=['/descent/','/descent','/challengers/play?game=core-pins','/challengers/play?game=nova-merge','/games/orbit-sprint/'].map(url=>({href:'https://vibe-arcade-dun.vercel.app'+url,addEventListener(n,f){this.click=f;}}));
 const events=[],node=()=>({hidden:false,textContent:'',replaceChildren(){},append(){},setAttribute(){},addEventListener(){},classList:{add(){},remove(){}}});
 const sandbox={URL,AbortController,setTimeout:()=>0,clearTimeout(){},document:{querySelector:node,querySelectorAll:q=>q==='.game-card'?cards:[],addEventListener(){}},WorldLeague:{C:{profile:null},readBoard:()=>new Promise(()=>{}),track:(...a)=>events.push(a),ready:new Promise(()=>{})}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'league/home.js'),'utf8'),sandbox);cards.forEach(a=>a.click());
 assert.deepEqual(events.map(e=>e[1].to),['gyro-drop','gyro-drop','core-pins','nova-merge','orbit-sprint']);
});
function tab(search,store){const outputs=[];const sandbox={window:{},location:{search,hostname:'vibe-arcade-dun.vercel.app',pathname:'/example'},URLSearchParams,sessionStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>store[k]=v},crypto:{randomUUID:()=> 'qa-fixture-session'},document:{referrer:''},navigator:{sendBeacon:(u,b)=>{outputs.push(b);return true;}},Blob,fetch:()=>{throw Error('no network allowed in fixture');}};vm.runInNewContext(fs.readFileSync(path.join(root,'arcade3/telemetry.js'),'utf8'),sandbox);return sandbox;}
test('channel/content persist through home, game and sign-in page navigation',()=>{const store={};tab('?utm_source=instagram&utm_medium=profile&utm_campaign=alwayson',store);assert.equal(JSON.parse(store.lj3_attribution).source,'instagram');tab('?game=core-pins',store);assert.equal(JSON.parse(store.lj3_attribution).source,'instagram');tab('?panel=profile',store);assert.equal(JSON.parse(store.lj3_attribution).campaign,'alwayson');assert.equal(store.lj3_session,'qa-fixture-session');});
test('explicit new campaign replaces old attribution without invented content ID',()=>{const store={};tab('?utm_source=threads&utm_campaign=pilot&utm_content=cp_fc01',store);tab('?utm_source=youtube&utm_medium=profile&utm_campaign=alwayson',store);assert.equal(JSON.parse(store.lj3_attribution).content,'');});
test('capture mode does not write attribution storage',()=>{const store={};tab('?capture=1&utm_source=qa',store);assert.deepEqual(store,{});});
