'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib');
const {contract,product}=require('../commercial/fixtures/generate.cjs');
const {validate,review,LIMITS}=require('../commercial/contract.cjs');
const {hash}=require('../../orchestrator/files.cjs');
const {requestFor}=require('../../orchestrator/repair.cjs');
const {failures}=require('../commercial/evidence.cjs');
const raster=require('../commercial/raster.cjs'),visual=require('../commercial/visual-review.cjs');
const clone=x=>JSON.parse(JSON.stringify(x));
test('strict data contract binds meaningful pairs and increasing stages to reviewed oracle',()=>{const r=review(contract(),product,{allowFixture:true});assert.equal(r.approval.scope,'fixture');assert.throws(()=>review(contract(),product),/scope|not a candidate approval/);for(const field of ['visual_legibility','action_feedback','motion','progression_spectacle','state_distinction','result_presentation','audio','mobile_hierarchy','replay_motivation','performance']){const c=contract();delete c[field];assert.throws(()=>validate(c),/commercial_contract/);}});
test('contracts cannot hide invalid regions, timing or unreviewed silence',()=>{for(const change of [c=>c.visual_legibility.pairs[0].a.region.x=.99,c=>c.motion.intermediate_ms=[130,60],c=>c.audio={mode:'reviewed_silence'},c=>c.execute='arbitrary code']){const c=contract();change(c);assert.throws(()=>validate(c));}const c=contract();c.progression_spectacle.marker+=' changed';assert.throws(()=>review(c,product,{allowFixture:true}),/changed/);});
test('oracle semantics reject equal states, fabricated availability and fake progression',()=>{const {model}=review(contract(),product,{allowFixture:true}),{semantics}=require('../commercial/contract.cjs');for(const change of [c=>c.state_distinction.pairs[0].b.node='1:0',c=>c.visual_legibility.pairs[0].action_b='a0',c=>c.action_feedback.probes[0].action='a4',c=>c.progression_spectacle.checkpoints[1].node='1:0']){const c=contract();change(c);assert.throws(()=>semantics(c,product,model));}});
function png(rgb){const part=(tag,data)=>{const h=Buffer.alloc(8);h.writeUInt32BE(data.length);h.write(tag,4);return Buffer.concat([h,data,Buffer.alloc(4)]);};const header=Buffer.alloc(13);header.writeUInt32BE(4);header.writeUInt32BE(4,4);header[8]=8;header[9]=2;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),part('IHDR',header),part('IDAT',zlib.deflateSync(Buffer.from(Array.from({length:4},()=>[0,...rgb,...rgb,...rgb,...rgb]).flat()))),part('IEND',Buffer.alloc(0))]);}
test('raster pixels, not state or numeric text, distinguish important states',()=>{const region={x:0,y:0,width:4,height:4},a=raster.sample(raster.decode(png([20,20,20])),region,[]),b=raster.sample(raster.decode(png([210,210,210])),region,[]);assert(!raster.distinct(raster.compare(a,a),LIMITS));assert(raster.distinct(raster.compare(a,b),LIMITS));const masked=raster.sample(raster.decode(png([210,210,210])),region,[region]);assert(!raster.distinct(raster.compare(a,masked),LIMITS));assert.throws(()=>raster.decode(Buffer.from('not png')));});
test('review opinion is bound to evidence and cannot manufacture proof',async()=>{const p=visual.packet({source_hash:'a',artifacts:[{path:'frame.png'}],checks:[]},contract()),r=await new visual.MachineCorroboration().review(p);assert.equal(visual.validateResponse(r,p).aesthetics,'UNVERIFIED');assert.throws(()=>visual.validateResponse({...r,evidence_hash:'bad'},p));assert.throws(()=>visual.validateResponse({...r,issues:[{category:'hierarchy',severity:'critical',message:'Important objects invisible',evidence:['missing.png']}]},p));assert.equal(visual.evidenceComplete({artifacts:[]},os.tmpdir()),false);});
test('missing commercial evidence blocks production policy but not explicit old infrastructure fixtures',()=>{const p=require('../../policies/quality-gate.json');assert(failures({},null,p).some(f=>f.code==='commercial_contract_missing'));assert.equal(failures({},null,{...p,product:{allow_fixture_oracles:true}}).length,0);const fs=failures({commercial_contract:contract(),product_contract:product},null,{...p,product:{allow_fixture_oracles:true}});assert(fs.some(f=>f.code==='commercial_stale_evidence'));assert(fs.some(f=>f.code==='commercial_visual_evidence_incomplete'));});
test('every actionable independent defect reaches repair unchanged; terminal budget never resets',()=>{const issues=['visual_legibility','action_feedback','audio'].map(check=>({code:'commercial_'+check,check,message:'Specific measured defect',state_pair:{a:'open',b:'blocked'},selector:'canvas',visual_region:{x:0,y:0,width:.2,height:.2},expected:'visible difference',actual:{delta:0},evidence:['commercial/before.png','commercial/settled.png'],viewport:{width:390,height:844},stage:2}));const m={game_id:'GAME-00000000-901',version:'v6',repair_attempt:4,max_repair_attempts:5,commercial_contract:contract(),failure_reasons:[]};const r=requestFor(m,{hard_failures:issues});assert.deepEqual(r.qa_failures,issues);assert.equal(r.operation_id,m.game_id+'/repair/5');assert.equal(r.commercial_contract.review_id,contract().review_id);assert.throws(()=>requestFor({...m,repair_attempt:5},{hard_failures:issues}),/budget_exhausted/);});
test('Control Plane holds historical green RC and preserves terminal rejection',()=>{const {decision,loadPolicy}=require('../../control-plane/control.cjs'),{create}=require('../../orchestrator/manifest.cjs');const m=create({game_id:'GAME-00000000-901',title:'Fixture',slug:'fixture',genre:'fixture',mechanic_family:'fixture',controls:['Arrows'],mobile_controls:['Tap'],qa:{seed:7,keyboard:{key:'ArrowRight',observation:'state.x'},pointer:{observation:'state.x'},terminal_ms:16000}});assert.equal(decision({...m,state:'RC_READY'},loadPolicy()).reason,'commercial_polish_unverified');assert.equal(decision({...m,state:'REJECTED',repair_attempt:5},loadPolicy()).action,'NONE');});
test('Docker suite never supplies host fallback or secrets',()=>{const {dockerArgs}=require('../../isolation/docker-qa.cjs');const args=dockerArgs({name:'fixture',image:'sha256:'+'a'.repeat(64),candidate:'/tmp/c',input:'/tmp/i',artifacts:'/tmp/a',limits:{cpus:1,memory_mb:1024,pids:128}});assert(args.includes('none'));assert(args.includes('--read-only'));assert(!args.some(a=>a.includes('docker.sock')||a==='-e'));});
