'use strict';
// TRUSTED INFRASTRUCTURE: generates reviewed DATA only, before the AI build.
// Never imports, executes, patches or supplies candidate implementation source.
const fs=require('node:fs'),path=require('node:path');
const {hash,atomicJSON}=require('../../orchestrator/files.cjs');
const seeds=[1,7,23,89,2026,4294967295];
const projection=['state.stage','state.cell','state.key_mask','state.outcome'];
const layouts=[{walls:[1,3],keys:[],exit:8},{walls:[7],keys:[0],exit:2},{walls:[],keys:[0,6],exit:2}];
const moves={left:[-1,0],up:[0,-1],right:[1,0],down:[0,1]};
function transform(cell,variant){let x=cell%3,y=Math.floor(cell/3);if(variant&4)x=2-x;for(let r=0;r<(variant&3);r++)[x,y]=[2-y,x];return y*3+x;}
function graph(seed){
 const rooms=layouts.map((l,i)=>{const t=c=>transform(c,(seed>>>(3*i))&7);return {walls:l.walls.map(t),keys:l.keys.map(t),exit:t(l.exit)};});
 const nodes={},queue=[[1,4,0,'playing']],id=s=>s.join(':');
 for(let i=0;i<queue.length;i++){
  const s=queue[i],name=id(s);if(nodes[name])continue;const [stage,cell,mask,outcome]=s;
  const n={stage,values:s,edges:[]};nodes[name]=n;if(outcome==='success'){n.success=true;continue;}
  const room=rooms[stage-1];
  for(const [action,[dx,dy]] of Object.entries(moves)){
   const x=cell%3+dx,y=Math.floor(cell/3)+dy,to=y*3+x;
   if(x<0||x>2||y<0||y>2||room.walls.includes(to)||to===room.exit&&mask!==(1<<room.keys.length)-1)continue;
   const k=room.keys.indexOf(to),nextMask=k<0?mask:mask|(1<<k);
   const next=to===room.exit?[stage+1,4,0,stage===3?'success':'playing']:[stage,to,nextMask,'playing'];
   n.edges.push({action,to:id(next)});if(!nodes[id(next)])queue.push(next);
  }
 }
 return {initial:'1:4:0:playing',nodes};
}
const model={schema_version:1,projection,seeds:Object.fromEntries(seeds.map(s=>[s,graph(s)]))};
const contract=JSON.parse(fs.readFileSync(path.join(__dirname,'../../schema/product-quality-contract.example.json'),'utf8'));
Object.assign(contract.objective,{expected_text:'Collect every key. Reach the exit in all 3 rooms.'});
Object.assign(contract.progress,{format:'ROOMS {value} / 3'});
Object.assign(contract.score,{reversible_probes:[['left','right'],['down','up']],no_progress_probes:[['up'],['right']]});
Object.assign(contract.completion,{success_text:'ALL ROOMS CLEARED',failure_text:'TIME UP',max_terminal_latency_ms:100,failure_wait_ms:41000});
Object.assign(contract.difficulty,{deterministic_seeds:seeds,oracle_id:'keywake-rooms-v1',oracle_sha256:hash(model),projection,max_actions:64});
Object.assign(contract.mobile,{min_font_px:14,canvas_control_regions:[0,.25,.5,.75].map(x=>({x,y:.8,width:.25,height:.2}))});
Object.assign(contract.feedback,{action:'left',settle_ms:400});
contract.actions=Object.fromEntries(Object.keys(moves).map((a,i)=>[a,{key:'Arrow'+a[0].toUpperCase()+a.slice(1),touch:{x:.125+i*.25,y:.9},hold_ms:35,settle_ms:35}]));
const implementation_contract={
 goal:'Show the exact objective "Collect every key. Reach the exit in all 3 rooms." before Start within the first mobile viewport. Explain one move per arrow press/tap. The explorer walks between stationary tiles; keys unlock the gold hatch. Room 1 teaches reaching an open hatch. Human target 15–40 seconds; skilled normal inputs can finish earlier without waiting.',
 progression:'Use exactly three bounded 3×3 walking rooms, never row/column shifting. Cells are row-major 0..8. Enter each room at cell 4 with key_mask 0. Base room 1: walls [1,3], keys [], exit 8. Base room 2: walls [7], keys [0], exit 2. Base room 3: walls [], keys [0,6], exit 2. An orthogonal move outside the board, into a wall, or into an exit before every key is held does nothing. Each key sets bit 1<<its index in the listed key array. A collected key stays collected for that room. A legal exit step immediately increments objective_progress and stage, resets cell=4,key_mask=0. Stage 4 is the canonical success state: stage=4,cell=4,key_mask=0,outcome="success",objective_progress=3. Initial outcome="playing"; timeout outcome="failure". Show permanent exact DOM progress "ROOMS {value} / 3" at [data-product-progress], driven by state.objective_progress, plus a separate current-room key count. GameKit writes [data-game-progress] from observe.progress; use this mandatory node as a visibly labeled elapsed time counter, not the rooms goal.',
 presentation:'Create original procedural Canvas art: a compact graphite room, softly beveled tiles, coral explorer, brass key silhouettes and a teal/gold hatch. Use a large central 3×3 board, clear blocked tiles, high contrast player/key/exit silhouettes, visible room number and key goal. Draw four generous arrow pads in the bottom 20% of the canvas in this left-to-right order: LEFT, UP, RIGHT, DOWN. The entire canvas accepts tap columns using floor(pointer.x*4) clamped 0..3, regardless of pointer.y; pads visibly communicate those same four actions. Keyboard arrows give exactly one move per press; use directional edge latching and clear it on neutral input or a touch action. Never lock input during animation. Every pointer action increments state.pointer_actions; only legal movement increments state.meaningful_actions and state.moves. Space alone is a no-op. GameKit provides x/y held directions, one-tick action, normalized pointer only while pressed. Export core as globalThis.KeywakeCore; no browser identifiers anywhere in core.js. Pass the fetched manifest as metadata to PlayJoltGameKit.create, with core, draw, canvas and presentation callback. No custom diagnostic API or loop.',
 originality:'Original three-room key-order micro puzzle, family discrete-key-collection-navigation. It is stationary turn-based walking with persistent key collection and exit constraints; no optical routing, cargo assignment, cycling rows/columns, timing gates, falling/merging stacks or automatic movement. Visual identity and every implementation file must be newly generated by the provider. No reused rejected candidate source.',
 difficulty:'Determinism for EVERY unsigned 32-bit seed: for room index i=0,1,2, variant=(seed >>> (3*i)) & 7. Apply the same transform to that room\'s walls, ordered keys and exit. Transform a cell (x=cell%3,y=floor(cell/3)): first if variant&4 mirror horizontally x=2-x; then repeat variant&3 clockwise rotations, each replacing (x,y) with (2-y,x); transformed cell=y*3+x. Center remains 4. Six reviewed samples are 1,7,23,89,2026,4294967295, with no seed-specific branch. Room-entry legal movement choices are 2,3,4; independent shortest required moves are 2,4,6. Room 3 key order matters: the other order takes 8 moves. Keys are irreversible and routes are reversible between pickups. observe().quality must provide stage=state.stage, complexity equal to the ACTUAL count of legal orthogonal destinations from the current cell under walls/exit/key constraints (0 at success), objective_progress, meaningful_actions (cumulative actual legal moves, never reset between rooms), reversible_state_key built only from stage,cell,key_mask,outcome. Keep state.stage,cell,key_mask,outcome matching the finite projection. One legal move including exit transitions increments meaningful_actions exactly once. Never count score, elapsed time or HP as complexity.',
 mobile_readability:'At 390×844 keep heading, objective, separate score/best cards, room/key progress, readable board, result and the primary Replay button inside the first viewport. Use compact responsive spacing, a roughly 340–370 CSS-pixel high canvas, ≥14 CSS-pixel DOM/canvas text and ≥44×44 CSS-pixel buttons. Scale canvas font sizes for device pixels correctly. Avoid stacked fillText/strokeText on the same glyph, overlapped text, tiny footnotes and canvas labels under arrows. Critical label and value elements must have separate non-overlapping boxes. Include all mandatory GameKit controls. At 768×1024 and 1280×800 keep the full interface within the viewport with a max-width compact board. [data-result] can be a visible hint before a terminal result; never nest critical selectors inside one another.',
 result:'On success show exact ALL ROOMS CLEARED, current score, number of moves and an efficiency message; on time expiry show exact TIME UP and rooms cleared. Use one [data-result] element and a strong [data-game-restart] Replay button visible inside the first 390px result viewport. Restart must use GameKit and reset the real core with the same seed. Render CURRENT SCORE in [data-score-label], its numeric value in [data-game-score]; DEVICE BEST in [data-best-label] and snapshot.best in [data-best]. Read best only from GameKit snapshot, no custom storage. Capture/QA writes zero; normal practice persists GameKit best and survives reload.',
 reduced_motion:'Read matchMedia("(prefers-reduced-motion: reduce)") initially and subscribe to native change events in presentation code. Honor both directions at runtime; expose a presentation callback returning reduced_motion, feedback_active, static_feedback as booleans. Reduced mode disables explorer travel, pulses and wiggle, replacing a meaningful move with a clearly visible static contrasting destination ring/path mark. Changing back restores animation for subsequent moves. Respect GameKit pause/hidden/restart lifecycle and clean native event listeners on final non-persisted pagehide. No sound, network, external assets or extra timers are needed.',
 scoring:'Initial score 0. Award score ONLY on clearing a room: max(100,200-20*max(0,room_moves-room_optimal_moves)), with optimal moves [2,4,6]. Count all legal moves, including detours, in room_moves; reset room_moves on each new room. Best possible score 600. Never award points for mere moving, bumping, keys, elapsed time or reversible walks. Going out and back cannot increase score and decreases later efficiency. Same objective projection with extra actions cannot produce a positive score delta. Do not reset total meaningful_actions on room change. observe returns finite tick,score,progress,interactions,entities and quality. Tick advances each 1/60 core step, progress=tick/60 seconds, interactions=meaningful_actions; entities remains small.',
 completion_timing:'Use a 40-second shared real simulation limit (2400 ticks at 60Hz), no minimum success duration. Immediately terminal when outcome becomes success at room 3 exit, and return terminal true for failure at tick>=2400. Success wins on the successful step. A player completing rapidly sees results in that same frame, ≤100ms. Never impose a post-success timer, animation completion barrier or arbitrary wait. Only human decision time determines normal 15–40 second sessions.',
 action_feedback:'For every legal move create a visible 220–280ms explorer step interpolation or movement trail between old and new cells plus a key/door event highlight. Use GameKit draw snapshots and presentation-only state; canonical state moves immediately and later inputs remain accepted. Derive transition time from the draw/performance clock, not mutable QA state. At 70ms and 130ms after an input there must be different visible intermediate frames; by 530ms the move settles and feedback_active=false. Expose feedback_active=true only during real visible interpolation, not a fabricated probe. In reduced mode use no travel: a static high-contrast outline visibly marks the new cell and static_feedback=true while that alternative is shown. Reset presentation tracking on Start/Replay; ignore idle redraws as actions. Show blocked-move feedback without adding points or meaningful_actions.'
};
const proposal={game_id:'GAME-20260923-141',generation:1,title:'Keywake',slug:'keywake',genre:'discrete navigation puzzle',mechanic_family:'discrete-key-collection-navigation',controls:['Press arrow keys to move one tile.'],mobile_controls:['Tap the arrow pads to move one tile.'],max_repair_attempts:5,qa:{seed:1,keyboard:{key:'ArrowLeft',observation:'state.cell'},pointer:{observation:'state.pointer_actions'},terminal_ms:42000},implementation_contract,product_contract:contract};
atomicJSON(path.join(__dirname,'proposal.json'),proposal);
atomicJSON(path.join(__dirname,'product-contract.json'),contract);
atomicJSON(path.join(__dirname,'../../qa/reviewed/keywake-rooms-v1.json'),model);
const registryPath=path.join(__dirname,'../../qa/reviewed/registry.json'),registry=JSON.parse(fs.readFileSync(registryPath,'utf8'));
registry.entries=registry.entries.filter(e=>e.id!=='keywake-rooms-v1');registry.entries.push({id:'keywake-rooms-v1',file:'keywake-rooms-v1.json',sha256:hash(model),contract_sha256:hash(contract),scope:'candidate',game_id:proposal.game_id,reviewed_by:'Work trusted infrastructure design review, 2026-09-23',rationale:'Small walking graph; persistent key masks; D4 seed transforms; room-entry legal choices 2/3/4 and independent shortest normal inputs 2/4/6. Every entry alternative returns without collecting keys. No candidate code, DOM, eval or mutation adapter.'});
atomicJSON(registryPath,registry);
const {review,shortest,stageMetrics}=require('../../qa/product-contract.cjs');review(contract);
const evidence=seeds.map(seed=>{const g=model.seeds[seed],plan=shortest(g,g.initial,n=>n.success),stages=[];for(const p of plan)if(!stages.some(s=>s.stage===g.nodes[p.from].stage))stages.push(stageMetrics(g,p.from));return {seed,nodes:Object.keys(g.nodes).length,normal_inputs:plan.length,stages};});
if(evidence.some(e=>JSON.stringify(e.stages.map(s=>[s.complexity,s.required_actions]))!==JSON.stringify([[2,2],[3,4],[4,6]])))throw Error('Unexpected reviewed depth');
atomicJSON(path.join(__dirname,'oracle-review.json'),{trusted_infrastructure:true,candidate_code_authored:false,scope:'Offline reviewed model only. Actual browser conformance is still required.',oracle_sha256:hash(model),contract_sha256:hash(contract),bounds:{max_nodes_per_seed:128,max_actions:64,seeds:6},evidence});
console.log(JSON.stringify({review:'PASS',oracle_sha256:hash(model),contract_sha256:hash(contract),seeds:evidence.map(e=>({seed:e.seed,nodes:e.nodes,normal_inputs:e.normal_inputs}))}));
