(function(){'use strict';
const $=q=>document.querySelector(q),R=ArcadeRules,C=window.LoopCommunity;
const q=new URLSearchParams(location.search),slug=q.get('game')||'reaction-rush',game=R.CONFIG[slug]?slug:'reaction-rush';
const capture=q.get('capture')==='1',cfg=R.CONFIG[game],canvas=$('#game'),renderer=new ArcadeRenderer(canvas,game);
const copy={
 'reaction-rush':{subtitle:'NEON SIEGE',pilot:'PIX / CITY SENTINEL',title:'Break the swarm.',text:'Tap drones. Avoid red mines. Manage heat, collect energy and break the boss shield.',how:['Tap teal scouts and violet armor drones. Red X mines damage your shield.','Green batteries cool your weapon and charge energy. 8 energy unlocks PULSE.','The Aegis boss arrives at 45 seconds. Hit its core only while exposed.'],objective:'Survive 60 seconds. Destroy the Aegis for a large score bonus.',action:'PULSE · 8 ENERGY',hint:'Tap drones. X / button = pulse. P = pause.'},
 'perfect-timing':{subtitle:'SKYFORGE',pilot:'AXIS / SKY BUILDER',title:'One clean drop.',text:'Align moving skyblocks. Build 24 floors. Three perfect drops repair a little lost width.',how:['Tap the game or press Space to drop the moving block. Only the overlapping part survives.','Chain three perfect drops to restore width. Miss the tower completely and lose one shield.','The moving block speeds up as you climb. Build 24 floors within 60 seconds.'],objective:'Reach the 24th floor. Trade quick drops against a perfect chain.',action:'DROP BLOCK',hint:'Tap canvas / Space / button to drop. P = pause.'},
 'dont-press':{subtitle:'REACTOR SHIFT',pilot:'CORE / SHIFT OPERATOR',title:'Know when to stop.',text:'Read each cycle: hold, tap once, tap twice or do not touch. Cyan is your action window.',how:['The rule below the reactor changes: HOLD, TAP ONCE, TAP TWICE, or DO NOT TOUCH.','Act only during the cyan window. Release a hold before the window closes.','Avoid red-seal inputs and build a clean cycle streak. Windows accelerate as the shift continues.'],objective:'Keep the reactor alive for 60 seconds. Clean cycles build your multiplier.',action:'HOLD / TAP',hint:'Mouse, touch or Space. Release before cyan closes.'}
}[game];
document.title=cfg.title+' — LoopJolt';document.body.classList.toggle('capture',capture);document.body.classList.add(game==='perfect-timing'?'theme-timing':game==='dont-press'?'theme-reactor':'theme-reaction');
$('#title').textContent=copy.subtitle;$('#edition').textContent=cfg.title.split(' · ')[0].toUpperCase()+' / RANKED EDITION';$('#pilot').textContent=copy.pilot;$('#sideTitle').textContent=copy.title;$('#description').textContent=copy.text;$('#resultTitle').textContent=copy.title;$('#resultText').textContent=copy.text;$('#objective').textContent=copy.objective;$('#action').textContent=copy.action;$('#hint').textContent=copy.hint;$('#version').textContent='LoopJolt Arcade 3 · '+cfg.version;
for(const text of copy.how){const li=document.createElement('li');li.textContent=text;$('#instructions').append(li);}
$('#classic').href='/games/'+game+'/';$('#boardLink').href=$('#viewScore').href='/community/?game='+game;$('#countryLink').href='/community/?game='+game+'&scope=nations';
let state=R.create(game,125904),seed=125904,active=false,paused=false,busy=false,queue=[],inputs=[],last=0,acc=0,run=null,attempt=0,soundOn=false,audio=null,callUntil=0,ready=false,pointerHeld=false,clock=RankedClock.create();
let best=0;try{best=Number(localStorage.getItem('lj3_best_'+cfg.version)||0)||0;soundOn=localStorage.getItem('lj3_sound')==='on';}catch{}$('#best').textContent=best.toLocaleString();
function track(event,props={}){window.LJTelemetry?.track(event,game,cfg.version,props);}
function tone(kind){if(!soundOn)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;const bad=['mine','escape','fault','drop-miss'].includes(kind);o.type=bad?'sawtooth':'triangle';o.frequency.setValueAtTime(bad?150:kind==='perfect'?880:kind==='boss-down'?400:650,t);o.frequency.exponentialRampToValueAtTime(bad?65:1200,t+.14);g.gain.setValueAtTime(.026,t);g.gain.exponentialRampToValueAtTime(.0001,t+.17);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.18);}catch{}}
function setSound(){$('#sound').textContent=soundOn?'Sound on':'Sound off';$('#sound').setAttribute('aria-pressed',String(soundOn));}setSound();
$('#sound').onclick=()=>{soundOn=!soundOn;setSound();try{localStorage.setItem('lj3_sound',soundOn?'on':'off');}catch{}tone('perfect');};
function setMotion(){$('#motion').textContent=renderer.reduced?'FX reduced':'FX on';$('#motion').setAttribute('aria-pressed',String(!renderer.reduced));}setMotion();$('#motion').onclick=()=>{renderer.reduced=!renderer.reduced;setMotion();};
function hud(){$('#score').textContent=state.score.toLocaleString();$('#time').textContent=Math.max(0,(cfg.ticks-state.tick)/60).toFixed(1);$('#combo').textContent=state.combo;$('#life').textContent=state.health;$('#lifeLabel').textContent=game==='dont-press'?'INTEGRITY':'SHIELDS';if(game==='reaction-rush'){$('#action').textContent='PULSE · '+state.energy+'/8';$('#action').classList.toggle('charged',state.energy>=8);}$('#action').disabled=!active||paused;}
function send(a){if(active&&!paused&&state.alive&&queue.length<4)queue.push(a);}
function coords(e){const r=canvas.getBoundingClientRect();return[Math.max(0,Math.min(1000,Math.round((e.clientX-r.left)/r.width*1000))),Math.max(0,Math.min(1000,Math.round((e.clientY-r.top)/r.height*1000)))];}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(e.button!==0&&e.pointerType==='mouse')return;canvas.setPointerCapture?.(e.pointerId);if(game==='reaction-rush')send(['tap',...coords(e)]);else if(game==='perfect-timing')send(['drop']);else{pointerHeld=true;send(['down']);}});
function release(){if(pointerHeld){pointerHeld=false;send(['up']);}}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);window.addEventListener('pointerup',release);
$('#action').addEventListener('pointerdown',e=>{e.preventDefault();if(game==='reaction-rush')send(['pulse']);else if(game==='perfect-timing')send(['drop']);else{pointerHeld=true;send(['down']);}});
$('#action').addEventListener('pointerup',release);$('#action').addEventListener('pointercancel',release);
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||!active)return;if(e.code==='KeyP'&&!e.repeat){e.preventDefault();pause();}if(e.repeat)return;if(e.code==='Space'){e.preventDefault();send(game==='reaction-rush'?['pulse']:game==='perfect-timing'?['drop']:['down']);}if(game==='reaction-rush'&&e.code==='KeyX'){e.preventDefault();send(['pulse']);}});
window.addEventListener('keyup',e=>{if(game==='dont-press'&&e.code==='Space'){e.preventDefault();send(['up']);}});
function status(text){$('#status').textContent=text;}
async function account(){if(!C){ready=true;status('Account service unavailable. Guest practice is ready.');return;}try{const data=await C.config();seed=data.seed||seed;if(!active&&!busy)state=R.create(game,seed);if(C.authenticated){await C.me();if(C.profile)$('#identity').textContent=C.flag(C.profile.country)+' '+C.profile.handle;}ready=!!data.rankedGames?.some(g=>g.game===game&&g.version===cfg.version);status(capture?'CAPTURE MODE · genuine gameplay, practice only, analytics disabled':ready?'Verified competition ready. Guests can also play instantly.':'Guest practice ready. Ranked activation is pending.');}catch{ready=false;status('Guest practice ready. Ranking service is unavailable.');}hud();}
async function launch(){if(busy)return;busy=true;const thisAttempt=++attempt;$('#start').disabled=true;$('#start').textContent='Preparing…';run=null;let message='Guest practice. Sign in before a run to submit a score.';
 try{if(!capture&&ready&&C?.authenticated){await C.me();if(C.profile){run=await C.api('start',{game});if(run.version!==cfg.version)throw Error('version_mismatch');message='Ranked run · server verifies all inputs.';}}}catch{run=null;message='Ranking unavailable. This run is practice; no unverified score will be published.';}
 if(thisAttempt!==attempt)return;state=R.create(game,run?run.seed:seed);inputs=[];queue=[];pointerHeld=false;paused=false;active=true;clock=RankedClock.create();acc=0;last=performance.now();busy=false;$('#start').disabled=false;$('#start').textContent='Play again →';$('#overlay').hidden=true;$('#resultLinks').hidden=true;$('#pause').disabled=false;$('#pause').textContent='Pause';$('#mode').textContent=capture?'REAL GAMEPLAY CAPTURE':run?'RANKED · '+cfg.version:'GUEST PRACTICE';status(message);track('game_start',{ranked:!!run});canvas.focus({preventScroll:true});hud();}
$('#start').onclick=launch;
function pause(){if(!active)return;paused=!paused;queue=[];pointerHeld=false;if(state.held)queue.push(['up']);acc=0;last=performance.now();if(run){run=null;$('#mode').textContent='PRACTICE · PAUSED RUN';}$('#pause').textContent=paused?'Resume':'Pause';$('#overlay').hidden=!paused;$('#resume').hidden=!paused;$('#start').hidden=paused;if(paused){$('#resultTag').textContent='PAUSED';$('#resultTitle').textContent='Take a breath.';$('#resultText').textContent='Pausing or switching tabs converts this attempt to practice. Your score stays local.';$('#saveState').textContent='Press Resume or P to continue.';$('#resultLinks').hidden=true;}hud();}
$('#pause').onclick=pause;$('#resume').onclick=pause;document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused)pause();});
function react(events,now){renderer.effects(events,now);const messages={'perfect':'PERFECT DROP','restore':'WIDTH RESTORED','boss':'AEGIS INCOMING','boss-down':'AEGIS DESTROYED','pulse':'PULSE WAVE','overheat':'COOL THE WEAPON','stabilize':'CYCLE STABLE','fault':'SEAL BREACH','drop-miss':'MISSED THE TOWER','complete':'ROUND COMPLETE'};for(const e of events){if(messages[e.kind]){$('#callout').textContent=messages[e.kind];callUntil=now+750;}if(['destroy','perfect','stabilize','fault','mine','boss-down','drop-miss'].includes(e.kind))tone(e.kind);}}
async function finish(){if(!active)return;active=false;busy=true;$('#pause').disabled=true;$('#overlay').hidden=false;$('#resume').hidden=true;$('#start').hidden=false;$('#start').disabled=true;$('#resultLinks').hidden=false;$('#resultTag').textContent=state.won?'ROUND COMPLETE':'TRY A NEW APPROACH';$('#resultTitle').textContent=state.score.toLocaleString()+' points';$('#resultText').textContent=game==='reaction-rush'?state.hits+' hits · '+state.maxCombo+' best chain · '+state.bossKills+' boss defeated':game==='perfect-timing'?state.floor+' floors · '+state.perfects+' perfect drops · '+state.width+' width left':state.hits+' stable cycles · '+state.maxCombo+' best chain';
 best=Math.max(best,state.score);try{localStorage.setItem('lj3_best_'+cfg.version,String(best));}catch{}$('#best').textContent=best.toLocaleString();hud();track('game_finish',{ranked:!!run,score:state.score,ticks:state.tick});
 const finishedRun=run;run=null;$('#saveState').textContent=finishedRun?'Verifying the full run on the server…':'Practice best saved on this browser. Sign in before your next run to compete.';
 try{if(finishedRun){const response=await C.api('finish',{runId:finishedRun.runId,actions:inputs,ticks:state.tick});$('#saveState').textContent=response.saved?'Verified · '+response.score.toLocaleString()+' points saved to game and championship boards.':'Submission not saved.';}}catch{$('#saveState').textContent='Local best saved, but ranked submission failed. No unverified score was published.';}
 finally{busy=false;$('#start').disabled=false;}
}
$('#share').onclick=async()=>{const text=cfg.title+' — I scored '+state.score+' in a practice/verified arcade run. Try your own run.';const url=new URL(location.href);url.searchParams.delete('capture');try{if(navigator.share)await navigator.share({title:cfg.title,text,url:url.href});else{await navigator.clipboard.writeText(text+' '+url.href);$('#share').textContent='Link copied';}}catch{status('Copy this page URL to share.');}};
function frame(now){if(active&&!paused&&state.alive){const elapsedMs=Math.max(0,now-last);if(run&&!RankedClock.observe(clock,elapsedMs)){run=null;$('#mode').textContent='PRACTICE · FRAME STALL';status('Frame timing became unstable. This attempt is practice only; try reduced FX for your next ranked run.');}acc+=Math.min(.1,elapsedMs/1000);let count=0;while(acc>=1/60&&count++<6&&state.alive){const a=queue.shift()||null;if(a)inputs.push([state.tick,...a]);R.step(state,a);acc-=1/60;react(state.events,now);}hud();if(!state.alive)finish();}last=now;renderer.draw(state,now);if(now>callUntil)$('#callout').textContent='';requestAnimationFrame(frame);}
window.LoopJoltSnapshot=()=>JSON.parse(JSON.stringify({state,active,paused,ranked:!!run,inputCount:inputs.length}));
track('page_view');track('game_open');account();requestAnimationFrame(frame);
})();
