'use strict';
const fs=require('node:fs'),path=require('node:path');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function html(s){
 const states=Object.entries(s.counts||{}).map(([k,v])=>`<li><b>${esc(v)}</b><span>${esc(k)}</span></li>`).join('')||'<li><b>0</b><span>NO JOBS</span></li>';
 const incidents=(s.incidents||[]).map(i=>`<tr><td>${esc(i.severity)}</td><td>${esc(i.code)}</td><td>${esc(i.game_id)}</td><td>${i.owner_action?'YES':'NO'}</td></tr>`).join('')||'<tr><td colspan="4">No incidents.</td></tr>';
 const jobs=(s.jobs||[]).map(j=>`<tr><td>${esc(j.game_id)}</td><td>${esc(j.title)}</td><td>${esc(j.state)}</td><td>${esc(j.repair_attempt)}</td><td>${esc(j.decision.action)}</td><td>${esc(j.metrics.state)}</td></tr>`).join('')||'<tr><td colspan="6">No factory jobs yet.</td></tr>';
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PlayJolt Factory Control Plane</title><style>body{font:14px system-ui;background:#0b1114;color:#e8f0ea;margin:0;padding:28px;max-width:1180px}h1{font-size:28px}small{color:#8fa09a}.banner{padding:14px;border:1px solid #3c5149;border-radius:10px;background:#111b1e}.warn{color:#ffd38a}.cards{display:flex;gap:10px;flex-wrap:wrap;padding:0}.cards li{list-style:none;border:1px solid #263a34;padding:12px 18px;border-radius:9px;display:grid}.cards b{font-size:22px}.cards span{font-size:10px;color:#9fb1aa}table{width:100%;border-collapse:collapse;margin:12px 0 28px}th,td{text-align:left;padding:9px;border-bottom:1px solid #22302c}th{color:#9fb1aa;font-size:10px}code{color:#a7f2cb}section{margin-top:28px}</style></head><body><h1>PlayJolt Autonomous Publishing OS</h1><p><small>Snapshot ${esc(s.generated_at)} · Policy ${esc(s.policy_version)} · ${esc(s.mode)}</small></p><div class="banner"><b>Factory intake:</b> ${s.automation.can_create?'READY':'HOLD'} · <code>${esc(s.automation.reason)}</code><br><b>Production auto-ship:</b> OFF · <b>Owner action:</b> ${s.owner_action_required?'<span class="warn">REQUIRED</span>':'none'}</div><section><h2>Factory states</h2><ul class="cards">${states}</ul></section><section><h2>Exceptions</h2><table><thead><tr><th>Severity</th><th>Code</th><th>Game</th><th>Owner</th></tr></thead><tbody>${incidents}</tbody></table></section><section><h2>Jobs</h2><table><thead><tr><th>ID</th><th>Title</th><th>State</th><th>Repairs</th><th>Next</th><th>Phase 2 data</th></tr></thead><tbody>${jobs}</tbody></table></section><p><small>This is a generated supervisory artifact, not a public operations API. READY_TO_SHIP is not a production approval.</small></p></body></html>`;
}
function write(snapshot,outDir){fs.mkdirSync(outDir,{recursive:true});fs.writeFileSync(path.join(outDir,'snapshot.json'),JSON.stringify(snapshot,null,2)+'\n');fs.writeFileSync(path.join(outDir,'dashboard.html'),html(snapshot));return outDir;}
module.exports={html,write};
